src/frontend/src/components/bullet-list.tsx
=> #108 - css

src/backend/src/prisma/manual.ts
=> #110 - added scripts

tsconfig.build.json
Updated the include and exclude options for tsconfig.
Closes #6
=> #6 - Updated tsconfig.build.json

src/backend/src/controllers/risks.controllers.ts, src/backend/src/routes/risks.routes.ts
=> #66 - Risk Create Endpoint

src/frontend/src/tests/layouts/NavTopBar/NavTopBar.test.tsx
Just fix the test since Anthony already updated the name to FinishLine
Closes #128
=> #128 - update test to FinishLine

.vscode/settings.json, .yarn/plugins/@yarnpkg/plugin-workspace-tools.js, .yarnrc.yml, src/backend/jest.config.js, src/backend/src/prisma/seed-data/change-requests.ts, src/frontend/config-overrides.js, src/frontend/src/setupTests.ts, src/frontend/src/stylesheets/index.css, src/frontend/src/stylesheets/layouts/NavTopBar/NavUserMenu.module.css, src/frontend/src/stylesheets/layouts/PageBreadcrumbs.module.css
Noticed that my CSS files weren't being formatted by prettier so now I fixed it with covering more file types with prettier. Also applied prettier to all files.
Closes #125
=> #125 fix prettier configs

src/frontend/src/pages/HomePage/UpcomingDeadlines.tsx, src/frontend/src/pages/HomePage/WorkPackagesByTimelineStatus.tsx, src/frontend/src/stylesheets/pages/Home.module.css
It looks as though the JSON CSS wasn't working properly. It would get recognized properly because when I changed it to "min-width" instead of minWidth, it complained at me. But when doing inspect element, min-width wasn't showing up in the styles attribute despite the margin stuff showing up. Very strange.
Duplicate CSS across the two components made it obvious that abstraction would be better, so I lifted it out into the Home CSS file and pulled it in from both components and bing bam it worked.
working again
Please request reviewers …
=> #124 - updated home page to fix scroll

src/backend/src/utils/change-requests.utils.ts, src/backend/src/utils/projects.utils.ts, src/backend/src/utils/teams.utils.ts, src/backend/src/utils/users.utils.ts, src/backend/src/utils/work-packages.utils.ts, src/backend/tests/projects.test.ts, src/backend/tests/users.test.ts, src/frontend/src/tests/TestSupport/TestData/ChangeRequests.stub.ts, src/frontend/src/tests/TestSupport/TestData/Users.stub.ts, src/shared/src/types/user-types.ts
Adjust the user model
Closes #138
=> #138: iykyk

yarn.lock
=> #100: what does this ticket even mean

src/frontend/src/apis/misc.api.ts, src/frontend/src/layouts/Sidebar/Sidebar.tsx, src/frontend/src/pages/SettingsPage/Settings.tsx, src/frontend/src/stylesheets/layouts/Sidebar/Sidebar.module.css, src/frontend/src/utils/Urls.ts
added version number to settings page
Closes #18
=> #18: added version number to settings page

package.json, yarn.lock
added a package that lets me delete folders
Closes #131
=> #131: Reset script is os agnostic

.github/pull_request_template.md, README.md, docs/About.md, docs/ContributorGuide.md, docs/Deployment.md, docs/Onboarding.md, docs/OnboardingWindows.md, docs/PrismaMigrationTools.md
=> #158: changed the docs

.vscode/extensions.json
Just Prettier formatting cuz it looked ugly
Please review the [contributor guide](https://github.com/Northeastern-Electric-Racing/FinishLine/blob/develop/docs/ContributorGuide.md) and reach out to your Tech Lead if anything is unclear.
Closes #170
=> #170 - Apply prettier formatting

src/backend/package.json, src/backend/src/controllers/change-requests.controllers.ts, src/backend/src/integrations/slack.ts, src/backend/src/integrations/slack.utils.ts, src/backend/src/prisma/manual.ts, src/backend/src/utils/change-requests.utils.ts, yarn.lock
Slack notifications will be sent in the appropriate team's Slack channel. Properly @ing people in Slack is not really possible without user Slack IDs being incorporated into FinishLine, so I made the notification messages not ping people. I think this will be fine since the pings are going into public channels.
Scope CRs (issue, definition change, or other) will only include the project name in the notification, regardless of whether the CR is for the project or a work package within the project.
Currently, I have it set up such that change request submission will error if the associated project is not properly linked to a team, but I'm open to changing that. We could instead make it such that Slack pings only happen when a team properly exists, but I'm slightly concerned that setting it …
=> #77 submit cr slack notification

src/backend/src/prisma/manual.ts
Creating a manual script for pulling stats for PM folks. I'm indifferent on what we do with this code, just wanna save it somewhere not locally so I can do other stuff.
Whatever else PM folks ask for.
Please review the [contributor guide](https://github.com/Northeastern-Electric-Racing/FinishLine/blob/develop/docs/ContributorGuide.md) and reach out to your Tech Lead if anything is unclear.
Closes #172
=> #172 - create baseline manual script for PM stats pull

src/frontend/src/pages/ChangeRequestDetailPage/ChangeRequestDetailsView.tsx, src/frontend/src/pages/CreateWorkPackagePage/CreateWPForm.tsx, src/frontend/src/pages/CreateWorkPackagePage/CreateWPFormView.tsx, src/frontend/src/tests/pages/CreateWorkPackagePage/CreateWPForm.test.tsx, src/frontend/src/tests/pages/CreateWorkPackagePage/CreateWPFormView.test.tsx, src/frontend/src/utils/Pipes.ts
added some params to the create wp page and now when you click create new wp it auto fills the wbs and crid for you
Closes #35
=> #35: Create new WP Query Params

src/backend/src/controllers/change-requests.controllers.ts, src/backend/src/routes/change-requests.routes.ts
Added an endpoint for adding a new proposed solution
I updated the route in the backend (change-requests.routes.ts), so it now accepts the change request id instead of the scope change request id from the frontend. 
- Case A
**Sent** a POST request to the endpoint with the following body:
{
"submitterId": 2,
"crId": 2,
"description": "hey there. Testing",
"scopeImpact": "222 for test",
"timelineImpact": 12,
"budgetImpact": 522	
}
**Result** (status: 200 OK):
{
"message": "Successfully created the proposed solution #1c7c12b3-ca01-4dd3-b432-f7307f0ece5f"
}
Also confirmed that a proposed solution data was added to the database's proposed solution table 
- improve code design/structure if needed
It can be helpful to check the `Checks` and `Files …
=> #88-Added-a-new-endpoint-for-adding-proposed-solution

.github/pull_request_template.md
changed the template to add more details about UI screenshots
Closes #220
=> #220: Pull Request Template

.github/ISSUE_TEMPLATE/epic.yml, .github/ISSUE_TEMPLATE/feature-request.yml, .github/ISSUE_TEMPLATE/other.yml, .github/ISSUE_TEMPLATE/task.yml
Updated the issue templates a lot
closes #132
=> #132: updating issue templates

src/backend/tests/projects.test.ts, src/backend/tests/test-data/projects.test-data.ts, src/backend/tests/test-data/users.test-data.ts, src/backend/tests/users.test.ts, src/backend/tests/work-packages.test.ts
refactored common objects, took out jest.fn calls, and reset mocks after each test
closes #236
=> #236: better backend jest practices

src/frontend/src/pages/LoginPage/LoginPage.tsx
Updated Cookies Disclaimer text
No other notes
1) Normal Sized
2) smallest Size
#Checkcklist
Closes #229 (issue #229)
=> #229 Update Cookies Disclaimer

src/backend/src/controllers/change-requests.controllers.ts, src/backend/src/routes/change-requests.routes.ts, src/frontend/src/pages/CreateChangeRequestPage/CreateChangeRequestView.tsx, yarn.lock
- Removed scope/timeline/budget from change requests route file.
- Changed scope/timeline/budget in controller to defaults for prisma (no longer pulled from user)
- Unsure how to test this removal - please reject change with where/how I should test if I need them 
Closes #212
=> #212 remove scope timeline budget

src/backend/src/controllers/change-requests.controllers.ts, src/frontend/src/apis/ChangeRequests.api.ts, src/frontend/src/hooks/ChangeRequests.hooks.ts, src/frontend/src/pages/ChangeRequestDetailPage/ChangeRequestDetailsView.tsx, src/frontend/src/pages/ChangeRequestDetailPage/ProposedSolutionForm.tsx, src/frontend/src/pages/ChangeRequestDetailPage/ProposedSolutionsList.tsx, src/frontend/src/pages/ChangeRequestDetailPage/ReviewChangeRequest.tsx, src/frontend/src/pages/ChangeRequestDetailPage/ReviewChangeRequestView.tsx, src/frontend/src/pages/CreateChangeRequestPage/CreateChangeRequest.tsx, src/frontend/src/pages/CreateChangeRequestPage/CreateChangeRequestView.tsx, src/frontend/src/pages/CreateChangeRequestPage/CreateProposedSolutionsList.tsx
wired up everything! This is the final proposed solution experience tm as it's the last thing we need to finish!
closes #86
=> #86: Wiring Up

src/frontend/package.json, src/frontend/src/app/AppContextTheme.tsx, src/frontend/src/components/EditableTextInputList.tsx, src/frontend/src/layouts/PageBlock.tsx, src/frontend/src/pages/CreateChangeRequestPage/CreateChangeRequestView.tsx, src/frontend/src/pages/CreateProjectPage/CreateProjectFormView.tsx, src/frontend/src/pages/CreateWorkPackagePage/CreateWPFormView.tsx, src/frontend/src/pages/HomePage/UpcomingDeadlines.tsx, src/frontend/src/pages/LoginPage/LoginDev.tsx, yarn.lock
Migrate a shit ton of forms to MUI
I think I folded in LocalizationProvider, I forget
I should add
Please review the [contributor guide](https://github.com/Northeastern-Electric-Racing/FinishLine/blob/develop/docs/ContributorGuide.md) and reach out to your Tech Lead if anything is unclear.
Closes #142
=> #142 MUI migration -- forms

src/backend/src/prisma/manual.ts
=> #339: desc bullet migration script

src/frontend/src/components/NERButton.tsx, src/frontend/src/pages/ChangeRequestDetailPage/ChangeRequestDetailsView.tsx
=> Add NER Button

src/backend/src/controllers/users.controllers.ts, src/backend/tests/users.test.ts
Added a test for updateUserSettings
- Works as it is supposed to
#262
=> #262-tested-update-user-settings

src/frontend/src/pages/ProjectDetailPage/ProjectEditContainer/ProjectEditContainer.tsx
changed the default project edit crID field to be empty instead of -1
n/a
check if the field can't be negative
check if the field remains empty when refreshing
check that a value has to be manually added to the field
nah we chillin
Closes #310
=> #310 adjusted the crId field in project edits to be empty instead of -1

src/frontend/src/pages/ProjectsPage/ProjectsTable.tsx
Added a custom sorting method to sort duration by integer values instead of strings to fix the issue of durations not always sorting correctly.
#48
=> #48 Add custom sorting for durations

src/backend/src/routes/change-requests.routes.ts, src/backend/src/utils/validation.utils.ts, src/frontend/src/pages/WorkPackageDetailPage/ActivateWorkPackageModalContainer/ActivateWorkPackageModal.tsx
It's not submitting for some reason rn, trying to figure out why, lmk if it's something obvious
new:
Fix submit
=> #401 activate work package modal m UI

src/frontend/src/pages/ChangeRequestDetailPage/ProposedSolutionSelectItem.tsx, src/frontend/src/pages/ChangeRequestDetailPage/ReviewChangeRequestView.tsx
Changed change request review modal to use MUI
Check it in light and dark mode
=> #392 mui reviewchangerequestview

src/frontend/src/pages/ChangeRequestsPage/ChangeRequestsTable.tsx
Closes #280 
@callmejim1226 @anthonybernardi @RChandler234
=> #280: Changed to MUI Button. Uses NER attributes, but cannot use NERButton.

src/frontend/src/pages/HomePage/WorkPackagesByTimelineStatus.tsx
Changed Work Packages By Timeline Status from react-bootstrap to MUI
Closes #397  (issue #)
=> #397 m UI work packages by timeline status

src/frontend/src/pages/ChangeRequestsPage/ChangeRequestsTable.tsx
Removed react-bootstrap stuff, it looks basically the same.
Closes #395  (issue #)
=> #395 - remove react bootstrap change request table

src/frontend/src/pages/WorkPackageDetailPage/WorkPackageEditContainer/EditModeOptions.tsx
Transitioned file to MUI
Closes #436  (issue #)
=> #436 mui edit mode options

src/frontend/public/index.html, src/frontend/src/pages/ChangeRequestDetailPage/ChangeRequestDetailsView.tsx, src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/ProjectDetails.tsx, src/frontend/src/pages/WorkPackageDetailPage/WorkPackageViewContainer/WorkPackageDetails.tsx, src/frontend/src/utils/Themes.ts
Change fonts from Anton (headings) and Oswald (normal) to Barlow Semi Condensed semi-bold and Lato, respectively.
Fix spacing in the details page where words are overflowing to the next grid in smallest width.
MUI doesn't let me set default fonts in `nerThemeOptions` (it works in the main `createTheme` object though), so I manually set Lato for all non-headings.
I chose to keep subtitles as Barlow because it fits the existing code and the style specs better. I don't think subtitles are used anywhere in the codebase currently.
Please …
=> #443 - New fonts in MUI for new club style

src/frontend/src/pages/ChangeRequestDetailPage/ProposedSolutionsList.tsx, src/frontend/src/pages/CreateChangeRequestPage/CreateChangeRequest.tsx, src/frontend/src/pages/CreateChangeRequestPage/CreateChangeRequestView.tsx, src/frontend/src/pages/CreateChangeRequestPage/CreateProposedSolutionsList.tsx
fixed the create cr form and it fully works
so the only hiccup is that I have to use the NativeSelect thing which does kinda look uglier but `<Select>` and `<TextField select>` both don't work with the react-hook-form useFieldArray and I cannot fix it for the life of me. (it also works with just normal `<select>` and `<input>` but then we get pure html woohoo so I think the NativeSelect is a goood enough middleground)
very annoying but I'm not sure it's worth spending more than the 30 minutes I've already spent trying to fix it. Also the NativeSelect won't change based on variation or styling or whatever so idrk what to do with that
Closes #455
=> #455: MUI Create CR Form

src/backend/src/controllers/projects.controllers.ts, src/backend/src/controllers/work-packages.controllers.ts, src/backend/src/routes/work-packages.routes.ts, src/frontend/src/layouts/PageBlock.tsx, src/frontend/src/pages/CreateProjectPage/CreateProjectForm.tsx, src/frontend/src/pages/CreateProjectPage/CreateProjectFormView.tsx, src/frontend/src/pages/CreateWorkPackagePage/CreateWPForm.tsx, src/frontend/src/pages/CreateWorkPackagePage/CreateWPFormView.tsx, src/frontend/src/pages/ProjectDetailPage/ProjectEdit/ProjectEditDetails.tsx, src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/RiskLog.tsx, src/frontend/src/pages/WorkPackageDetailPage/WorkPackageViewContainer/WorkPackageViewContainer.tsx, src/frontend/src/utils/axios.ts
I went through every single pr since the mui branch was opened and made sure all the changes were incorporated into this branch because we lost a few things in all the merges we did.
also i fixed a lot of stuff like the work package and project create forms
Closes #468
=> #468: Add All Frontend Features

src/frontend/src/components/CheckList.tsx, src/frontend/src/pages/WorkPackageDetailPage/WorkPackageViewContainer/WorkPackageViewContainer.tsx
A tooltip appears when you hover over a checked item in CheckList.
Closes #187
=> #187 - Added WPP Tooltip

src/frontend/src/components/ChangesList.tsx, src/frontend/src/layouts/PageTitle/PageBreadcrumbs.tsx, src/frontend/src/pages/ChangeRequestDetailPage/ChangeRequestDetailsView.tsx, src/frontend/src/pages/ChangeRequestDetailPage/ImplementedChangesList.tsx, src/frontend/src/pages/SettingsPage/UserSettings/UserSettingsEdit.tsx, src/frontend/src/pages/SettingsPage/UserSettings/UserSettingsView.tsx, src/frontend/src/pages/TeamsPage/TeamSummary.tsx, src/frontend/src/tests/pages/CreateProjectPage/CreateProjectForm.test.tsx, src/frontend/src/tests/pages/CreateProjectPage/CreateProjectFormView.test.tsx, src/frontend/src/tests/pages/CreateWorkPackagePage/CreateWPForm.test.tsx, src/frontend/src/tests/pages/CreateWorkPackagePage/CreateWPFormView.test.tsx
Removed all possible instances of href to use either internal react router or the ExternalLinks component.
tests are failing, I don’t know why, mostly because I don’t know about front end tests the new linkings work though.
User settings changed to a div with flex display for using external links
Change Request Page:
Teams Page:
fix tests ig
- [ x] All commits are tagged with the ticket number …
=> #496 Remove href and use External Links and React Router Dom

src/frontend/src/pages/ChangeRequestsPage/ChangeRequestsTable.tsx, src/frontend/src/pages/ProjectsPage/ProjectsTable.tsx
Made it so that the page size uses a state variable that changes rather than fixed value of ‘15’
Closes #504 (issue #)
=> #504 Add useState for page size

src/frontend/src/pages/ChangeRequestsPage/ChangeRequestsTable.tsx, src/frontend/src/pages/ProjectsPage/ProjectsTable.tsx
Created good enough temp solution for fixing all the column filtering. Flatten some data into types that MUI can handle, add type specification for columns, and disable filtering on columns that are simply too complex.
Pair programmed with Peyton! We dug into figuring out how MUI Data Grids work and decided that this temp solution would be best to get features working for users. I think that at some future point it would be awesome to investigate creating custom filter operators for the more complex data types (WBS Numbers, Users, etc.) as well as adding the quick filter in with custom quick filter functions for columns. Both those are noted in #505.
Lol none.
n/a …
=> #509 - fix mui column filtering as temp solution

src/backend/src/controllers/users.controllers.ts, src/backend/tests/users.test.ts, src/frontend/src/pages/AdminToolsPage/AdminTools.tsx, src/frontend/src/pages/AdminToolsPage/AdminToolsUserManagement.tsx
Added security checks
Simplified the react and made more readable linebreaks
Made it so that when you select a user, it auto chooses their role which imo reduces James' point about wanting their role in the dropdown which I tried but was very cluttered
Did some other small stuff to make the flow better
closes #259
=> #259: User Roles Acceptance Testing

src/frontend/src/pages/WorkPackageDetailPage/WorkPackageViewContainer/WorkPackageViewContainer.tsx
=> #466: added project name to work package breadcrumbs

.github/ISSUE_TEMPLATE/bug-form.yml, .github/ISSUE_TEMPLATE/spike.yml, .github/workflows/prettier-check.yml, .github/workflows/run-tests.yml, .prettierignore, package.json, src/backend/src/controllers/risks.controllers.ts, src/frontend/src/hooks/teams.hooks.ts, src/frontend/src/layouts/PageTitle/PageBreadcrumbs.tsx, src/frontend/src/pages/SettingsPage/UserSettings/UserSettingsEdit.tsx, src/frontend/src/pages/SettingsPage/UserSettings/UserSettingsView.tsx, src/frontend/src/tests/test-support/test-data/work-packages.stub.ts
prettier formatting check for PRs
Closes #528
=> #528: add prettier formatting check

src/frontend/src/components/NERAutocomplete.tsx, src/frontend/src/pages/AdminToolsPage/AdminToolsUserManagement.tsx, src/frontend/src/pages/CreateChangeRequestPage/CreateChangeRequest.tsx, src/frontend/src/pages/CreateChangeRequestPage/CreateChangeRequestView.tsx
abstracted out the autocomplete to a common component file and made the dropdown for the cr creation
Not sure i like how the type box lines up with this, open to suggestions here.
Closes #526
=> #526: Added Dropdown for CR Creation

src/backend/src/controllers/change-requests.controllers.ts, src/backend/src/services/change-request.services.ts, src/frontend/src/pages/CreateChangeRequestPage/CreateChangeRequest.tsx
Fixed proposed solution bug.
Its either this or we change what creating the standard change requests returns to just be the crId. 
Closes #521  (issue #)
=> #521 Proposed solution bug fixes

src/backend/src/controllers/description-bullets.controllers.ts, src/backend/src/prisma-query-args/description-bullets.query-args.ts, src/backend/src/prisma-query-args/work-packages.query-args.ts, src/backend/src/routes/description-bullets.routes.ts, src/backend/src/services/description-bullets.services.ts, src/backend/src/transformers/description-bullets.transformer.ts, src/backend/src/transformers/work-packages.transformer.ts, src/backend/src/utils/description-bullets.utils.ts
Separated controller function into service and turn into a class.
threw new exceptions accordingly
moved transformer and args to new files
Closes # (issue #487
=> #487: put changes on new branch

src/frontend/src/layouts/PageBlock.tsx, src/frontend/src/layouts/Sidebar/Sidebar.tsx, src/frontend/src/pages/CreateChangeRequestPage/CreateChangeRequestView.tsx, src/frontend/src/pages/CreateProjectPage/CreateProjectFormView.tsx, src/frontend/src/pages/HomePage/UpcomingDeadlines.tsx, src/frontend/src/pages/HomePage/WorkPackagesByTimelineStatus.tsx, src/frontend/src/pages/TeamsPage/TeamSummary.tsx, src/frontend/src/stylesheets/layouts/sidebar/sidebar.module.css, src/frontend/src/tests/pages/HomePage/UpcomingDeadlines.test.tsx
Starting with a couple small things (fixing version number, team summary blocks, and size of collapsed pageblocks). Tried making the default scrollbar for the whole app look cooler, but wasn't having much luck. Gonna keep going through the rest as I have time.
Closes #469  (issue #)
=> #469 - more visual cleanup

.github/ISSUE_TEMPLATE/bug-form.yml
Update versions to prod and develop
N/A
N/A
N/A
N/A
Closes #497
=> #497 Bug Template Versions Update

src/frontend/src/app/AppAuthenticated.tsx, src/frontend/src/pages/CreditsPage/Credits.tsx, src/frontend/src/pages/CreditsPage/CreditsPage.tsx, src/frontend/src/utils/routes.ts
Added a bare-bones credits page
Willing to up the snark level on the snark button
Closes #495
=> #495-added a credits page

src/backend/src/services/change-request.services.ts, src/backend/tests/change-requests.test.ts
Check for deleted description bullets when reviewing a stage gate cr
Closes #546 (issue #)
=> #546 Check for deleted description bullets

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
Added a line for the credits page with my name and color choice.
I love Zack Roth <3
N/A
included below.
<3
#
- [ Y] All commits are tagged with the ticket number
- [ Y] No linting errors / newline at end of file warnings
- [ Y] All code follows repository-configured prettier formatting
- [ Y] No merge conflicts
- [ Y] All checks passing
- [ Y] Screenshots of UI changes (see Screenshots section)
- [ Y] Remove any non-applicable sections of this …
=> #556 Added my name to credits

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
added my name to credits
Closes #557
=> #557 added my name to credits

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
Added my name and color to line 30 
Closes #573
=> #573 Added my name to credits

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
Add Jonathan Chen to `names` array in credits page.
Hex color was fun
Closes #597
=> #597 - Add Jonathan Chen to credits page

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
Added my name to the name array in CreditsPage.tsx
Closes #570 (issue #)
=> #570: Added my name to credits.

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
_I added my name and my favorite color on credit page_
Closes #562
=> #562 ray kong credits

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
Added another name entry to the array of names in CreditsPage.tsx with my name so it shows on the credits page.
N/A
Closes #568
=> #568: Added my name to credits

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
added my name to credits
My first pull request :)
Closes #579
=> #579: added my name to the credits

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
Added my name to the credits
- Case A
- Edge case
- ...
_If you made UI changes you must po
st a screenshot of the whole page for each change in 1) a normal sized window and 2) the smallest possible window_
Closes #569
=> #569-Added-my-name-to-the-credits

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
=> #566:  Added my name to credits page

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
1st commit added my own name and color to credits, 2nd commit modifies color to make it more readable.
N/A
1ST COMMIT:
2ND COMMIT: …
=> #567: Added name to the credits

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
I added my name to the credits list
None
Closes #576
=> '#576-MokkhMitsuntisuk-credits'

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
Added my name to the credits page and wrote it in purple
Closes #559
=> #559 hamsini malli credits

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
Added my name to the credits section of FinishLine homepage.
Closes #580  (issue #)
=> #580 Added my name to credits

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
_I put my name in the credits with the Egyptian blue color_
_Yeah I had a rough time getting the commit to work but eventually it worked out_
Closes #571
=> #571 Added my name to credits

.env, src/frontend/src/pages/CreditsPage/CreditsPage.tsx
_If you made UI changes you must post a screenshot of the whole page for each change in
1) 
2) the smallest possible window_
Closes #584
=> #584 Added my name to credits

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
I added my name to the credits section
- Case A
- Edge case
- ...
Closes #555
=> #555: added my name to credits

src/frontend/src/pages/LoginPage/LoginPage.tsx
Change login page logic to display only dev login in develop environment and only Google auth login in production.
No tests written
Closes #545
=> #545: Hide Google login button in dev

src/frontend/src/pages/CreditsPage/CreditsPage.tsx, yarn.lock
Added my name to credits
Closes #616
=> #616 Added my name to credits

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
added my name to the credits page 
Closes #630
=> #630: added my name to the credit page

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
=> #649 added name

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
_added name to the array_
- Case A
- Edge case
- ...
Closes # (issue #646)
=> #646 Added my name to credits

src/backend/src/prisma/seed-data/users.seed.ts, src/backend/src/prisma/seed.ts
I left in Thomas Emrax, Joe Shmoe, and Joe Blow. Then added a bunch of users for some variety. Ideally there are some things we would do differently, but I'll get to that later once everything is refactored
Closes #629
=> #629 - User Seed Data

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
Changed my name color.
It looks much better now.
Closes #656
=> #656 - Changed My Name Color

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
I added my name to the credits page.
Added it to `CreditsPage.tsx`.
Closes #660
=> Add my name to credits

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
added name to credits
Closes #631
=> #631: added my name to the credits page

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
_I added my name in bright pink to the list of names_
_I had a few issues, mainly concerning adding quotations at places that I did not expect them to be needed. Additionally, I did not realize I was not logged in so I had issues from saving to doing the pull request, as I had not realize. I then had to save again and log in so that it functioned correctly._
Updated with screenshots: 
Please review the contributor guide and reach out to your Tech Lead if anything is unclear.
Closes #655
=> #655 Added my name to credits

src/frontend/src/pages/TeamsPage/TeamMembersPageBlock.tsx
Fixed a bug with cancelling not resetting the description useState constant
Did not discover cause of bug on prod, but think it has something to do with the console warnings maybe possibly. 
- Fix Prod bugs
Closes #654  (issue #)
=> #654 Fix Cancel Button bug

src/backend/src/controllers/projects.controllers.ts, src/backend/src/integrations/slack.ts, src/backend/src/prisma-query-args/projects.query-args.ts, src/backend/src/routes/projects.routes.ts, src/backend/src/services/projects.services.ts, src/backend/src/transformers/projects.transformer.ts, src/backend/src/utils/projects.utils.ts, src/backend/tests/change-requests.test.ts, src/backend/tests/projects.test.ts, src/backend/tests/risks.test.ts, src/backend/tests/test-data/projects.test-data.ts, src/backend/tests/test-data/wbs-element.test-data.ts, src/backend/tests/work-packages.test.ts, src/frontend/src/pages/CreateProjectPage/CreateProjectForm.tsx, src/frontend/src/pages/ProjectDetailPage/ProjectEdit/ProjectEditContainer.tsx, src/frontend/src/utils/urls.ts
Did all the refactoring and stuff
- I took out the debug logging for the slack package thank god, didn't realize it was on and it's been annoying me so much
- for some reason we had two different query args related to projects and I was able to cut one out which made a bunch of things a lot cleaner
- forgot that we can and should take userId out of all queries from the frontend now but that could be good easy beginner tickets
Closes #488
=> #488: Project Refactoring

src/frontend/src/components/NERFailButton.tsx, src/frontend/src/components/NERSuccessButton.tsx, src/frontend/src/pages/TeamsPage/TeamMembersPageBlock.tsx
Created component for cancel button
Closes #694  (issue #)
=> #694 Standard Cancel Button Comp

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
Added my name to the credits
Had some trouble running the site, went through the software onboarding a second time from the start and made sure docker was connected but still getting an error stating that there's a failure to compile
- Case A
- Edge case
- ...
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to …
=> #565: added my name to credits again

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
Added my name "Isaac Levine" to the credits
Closes #560
=> #560 Added my name to credits

src/backend/index.ts, src/backend/src/controllers/change-requests.controllers.ts, src/backend/src/controllers/description-bullets.controllers.ts, src/backend/src/controllers/projects.controllers.ts, src/backend/src/controllers/risks.controllers.ts, src/backend/src/controllers/teams.controllers.ts, src/backend/src/controllers/users.controllers.ts, src/backend/src/controllers/work-packages.controllers.ts, src/backend/src/services/users.services.ts, src/backend/src/utils/auth.utils.ts, src/backend/src/utils/utils.ts
- Create `auth.utils.ts`
- Move auth related utils from `utils.ts` to `auth.utils.ts`
- Update imports
(all tests pass)
Closes #482
=> #482 Move auth utils to separate file

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
Added my name with color in the names array
Closes #748
=> #748: Added my name to the credits page

src/backend/src/services/users.services.ts
Removed the any type from users.services under defaultTheme and replaced it with ThemeName type.
Closes #701
=> #701: Removed any type from users.services.

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
Added my name to credits
Closes #772 (issue #)
=> #772 Added my name to credits page

src/frontend/src/pages/ProjectsPage/ProjectsTable.tsx
make rowCount so that its persistent to the user's preference
Closes #653
=> #653 Row Count Persistent

src/frontend/src/app/AppPublic.tsx
Changed type any to AppRenderInput
Closes #667
=> #667 Removed any type from AppPublic

src/frontend/src/pages/ProjectsPage/ProjectsTable.tsx
I removed the 'any' type from the ProjectsTable.tsx file, replaced with a created interface
#666
=> #666 Removed the any type from ProjectsTable.tsx

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
Added name to Credits
- Case A
- Edge case
- ...
Closes #806 (issue #)
=> #806 Added my name to credits

src/frontend/src/pages/WBSDetails.tsx
Removed "any" type and replaced it with "unknown" + corresponding error msg
Closes # 678
=> #678: Remove any type from WBSDetails

src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/RiskLog.tsx
Replaced alert() with useToast() in RiskLog
Closes #639
=> #639 Replaced alert() with useToast() in RiskLog

src/frontend/src/pages/CreateChangeRequestPage/CreateChangeRequestView.tsx
Changed buttons to use NERFail and NERSuccess buttons
- Use of submit button adds change request to list of requests
- Use of cancel button brings back to Create Change Request page
Closes #718
=> #718 change create change request buttons

src/backend/src/services/change-requests.services.ts
Changed the return type from an object type Number to a primitive type number.
Closes #742
=> #742:changed the return type

src/frontend/src/pages/ChangeRequestDetailPage/ProposedSolutionForm.tsx
Refactored the Proposed Solution Form so that the timeline placeholder reads "# of weeks needed" instead of "# of weeks"
This was a one line change
N/A
Closes #623
=> #623 Refactored the wording of timeline impact placeholder

src/backend/src/services/users.services.ts, src/backend/src/utils/users.utils.ts, src/frontend/src/pages/LoginPage/LoginDev.tsx, src/shared/index.ts, src/shared/src/rank-user-role.ts
Users on dev login lists now sorted depending on their role, last name, first name, and user id with decreasing priority
Copied over rankUserRole to shared folder so it could be used for frontend
- Case A
- Edge case
- ...
Closes #662
=> #662: finished ticket, users now properly sorted

src/frontend/src/pages/AdminToolsPage/AdminToolsUserManagement.tsx
imported toast, created a variable for it and called it when alert was called.
Small SS
Big SS
Closes #636
=> Added useToast()

src/backend/tests/change-requests.test.ts
Wrote unit tests for some of the cases of the addProposedSolution endpoint
-  CR not found
-  User Access Denied
-  CR deleted
-  CR already accepted
-  ScopeCR not found
-  Accepted proposed solution
Closes #245
=> #245: Tests for AddProposedSolution

src/frontend/src/components/NERAutocomplete.tsx, src/frontend/src/pages/AdminToolsPage/AdminToolsUserManagement.tsx, src/frontend/src/pages/CreateChangeRequestPage/CreateChangeRequestView.tsx
Removing any data type and replace it with appropriate data type
Closes #669, #673
=> '#669-MokkhMitsuntisuk-RemoveAny'

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
Added my name to credits
Closes #850
=> #850 Added my name to credits

src/backend/tests/risks.test.ts
Added two tests for editRisk:
- The risk that is trying to be edited does not exist
- The user does not have permissions to edit the risk
The tests pass:
- When the risk to be edited does not exist, an appropriate exception is thrown.
- When the user does not have permissions to edit the risk, an appropriate exception is thrown.
- The risk that is trying to be edited does not exist
- The user does not have permissions to edit the risk
Closes #241
=> #241: Test editRisk Endpoint Failures

src/frontend/src/layouts/NavTopBar/NavUserMenu.tsx, src/frontend/src/pages/LoginPage/LoginPage.tsx
Changed logout button to logic it had before
Not sure if this works on prod, does work on dev. 
Closes #816  (issue #)
=> #816 Fix Logout Button

src/backend/index.ts, src/backend/src/controllers/change-requests.controllers.ts, src/backend/src/prisma-query-args/change-requests.query-args.ts, src/backend/src/prisma-query-args/projects.query-args.ts, src/backend/src/prisma-query-args/work-packages.query-args.ts, src/backend/src/routes/change-requests.routes.ts, src/backend/src/services/change-requests.services.ts, src/backend/tests/change-requests.test.ts
Created CR Delete Endpoint
Closes #825  (issue #)
=> #825 CR Delete Endpoint

src/backend/src/prisma/migrations/20230212180548_add_wp_stage/migration.sql, src/backend/src/prisma/migrations/20230214001747_add_wp_stage_and_tasks/migration.sql, src/backend/src/prisma/schema.prisma, src/backend/src/prisma/seed-data/work-packages.seed.ts, src/backend/src/transformers/projects.transformer.ts, src/backend/src/transformers/work-packages.transformer.ts, src/backend/tests/test-data/projects.test-data.ts, src/backend/tests/test-data/work-packages.test-data.ts, src/shared/src/types/project-types.ts, src/shared/src/types/work-package-types.ts
Updated schema, shared types, and seed data
Closes #839  (issue #)
=> #839 - update schema, types, and seed data

src/frontend/src/pages/CreditsPage/CreditsPage.tsx, yarn.lock
Added name to CreditsPage.tsx
Closes #866
=> #866: Added my name to the credits page

src/frontend/src/pages/TeamsPage/TeamSpecificPage.tsx
Added teams page to the breadcrumbs so it reads as Home / Teams / Team 
- Opened team ravens and went back to teams apge
Closes #750
=> #718: added teams page to the breadcrumbs

src/backend/src/services/work-packages.services.ts
Changed all types with "any" to actual data type in the work-packages-services file
Closes #702
=> #702 removed any from work-packages-services

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
Added one more names object in the credits.page.tsx
Added name to end of the credits pages
- [x ] All commits are tagged with the ticket number
- [ x] All code follows repository-configured prettier formatting
- [ x] No merge conflicts
- [ x] All checks passing
- [ x] Screenshots of UI changes (see Screenshots section)
- [ x] Remove any non-applicable sections of this template
- [ x] Assign …
=> #881: Added my name to credits

src/frontend/src/layouts/NavTopBar/NavUserMenu.tsx
Changed user settings menu to use MUI icons.
Could not find the Admin tools option to add icon for
Closes #804
=> #804 updated user menu to use MUI icons

src/frontend/src/pages/InfoPage.tsx
replaced font awesome icons to mui icons & removed instances of font awesome
Closes # (issue #847)
=> replaced icons

src/frontend/src/layouts/NavTopBar/NavUserMenu.tsx, src/frontend/src/layouts/Sidebar/Sidebar.tsx
Moved admin tools to the user menu
Closes #787
=> #787: moved admin tools to user menu

src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/ProjectViewContainer.tsx
Add MUI Icon to action menu on individual project page
Closes #807
=> '#807-Mokkh-ProjectPageActionMenu'

src/backend/src/prisma/seed.ts
Add a variety of cool seed data in all the projects.
The only file changed is seed.ts, the rest are recent stuff from develop branch
I tried to follow restrictions on who can make tasks and who can be assigned tasks. Unfortunately all the current projects are Huskies only and the Huskies only have 3 people. If desired we can add more projects featuring other teams. 
Time zones should follow Eastern time (except for Vibration Tests which I left in UTC-5 which is central daylight time, yay i18n). Does it matter? Who knows
Please request reviewers …
=> #794 - Add Task List Seed Data

src/backend/src/controllers/tasks.controllers.ts, src/backend/src/routes/tasks.routes.ts, src/backend/src/services/tasks.services.ts, src/backend/tests/tasks.test.ts, src/backend/tests/test-data/tasks.test-data.ts
Create the edit task assignees endpoint.
(not done yet)
- Successful edit
- Unsuccessful edit (invalid permissions, task deleted, task doesn't exist, assignees don't exist)
Closes #791
=> Edit task assignees

src/backend/src/controllers/tasks.controllers.ts, src/backend/src/routes/tasks.routes.ts, src/backend/src/services/tasks.services.ts, src/backend/tests/tasks.test.ts, src/backend/tests/test-data/tasks.test-data.ts
Changed the task.route file to accommodate for a post delete request
Created a delete task method that looked at user permissions and deleted a given task
I still have one test failing and am not quite sure how to solve it. 
Closes #793
=> deleting tasks while considering user permissions

src/backend/src/routes/change-requests.routes.ts, src/frontend/src/apis/change-requests.api.ts, src/frontend/src/hooks/change-requests.hooks.ts, src/frontend/src/pages/CreateChangeRequestPage/CreateChangeRequest.tsx
removed the any
- manually tested that creation still works
closes #706 #686
=> #706: Remove Any Change Request Hook

src/frontend/src/apis/projects.api.ts, src/frontend/src/hooks/projects.hooks.ts, src/frontend/src/pages/ProjectDetailPage/DeleteProject.tsx, src/frontend/src/pages/ProjectDetailPage/DeleteProjectView.tsx, src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/ProjectViewContainer.tsx, src/frontend/src/utils/urls.ts
Created the dropdown item to delete
created the modal to make sure they want to delete
delets
Closes #421
=> #421: delete project modal

src/frontend/src/pages/GanttPage/GanttPageFilter.tsx
Fixed overlapping filters.
Closes #907
=> #907 - Fixed Overlapping Gantt Filters

src/frontend/src/pages/ProjectDetailPage/ProjectEdit/ProjectEditContainer.tsx
Changed alert() method with useToast() method in projectEditContainer
Closes #638
=> #638: replaced alert() with useToast() in projectEditContainer

.github/workflows/lint-check.yml, .github/workflows/prettier-check.yml, .github/workflows/run-tests.yml
adding timeouts and caching of yarn stuff which should hopefully make it run faster
Closes #946
=> #946: GitHub Actions Improvements

src/frontend/src/pages/GanttPage/GanttPackage/components/gantt/gantt.tsx, src/frontend/src/pages/GanttPage/GanttPage.tsx
make gantt chart start today
turns out it was a prop
Closes #781
=> #781: make gantt chart start today

src/frontend/src/pages/GanttPage/GanttPackage/components/gantt/gantt.tsx
Refactored the rgba values to updated blue color.
Closes #815
=> #815 - Updated todayColor for Gantt Chart

src/backend/src/routes/teams.routes.ts
Validated that the userId's is an array and an integer greater than 0
Passing when using an array of numbers greater than 0:
Failing when using a negative int:
Failing when it is not an array:
Failing when using an array of strings:
images.githubusercontent.com/76594216/222289297-f57312d1-3708-448f-89c7-b86c11a1ab47.png">
Closes #883
=> #883 Validated the set team members route

src/backend/tests/change-requests.test.ts, src/frontend/src/pages/ProjectsPage/HCPC.java
created a test for getAllChangeRequests
it works when there are change requests
possibly more tests needed
Closes #247
=> #247-ShreeSinghal-TestgetAllChangeRequests

src/frontend/src/layouts/NavTopBar/NavUserMenu.tsx, src/frontend/src/pages/ProjectDetailPage/ProjectEdit/ProjectEditContainer.tsx, src/frontend/src/pages/SettingsPage/Settings.tsx, src/frontend/src/pages/SettingsPage/UserSettings/UserSettingsView.tsx
So when we moved the menu item inside of the google logout, we forgot to add the onclick={renderProps.onclick) function, so we never actually called the google logout button. Now we do and it works (i dont think trickster mode works on dev but does that really matter?)
Closes #961 (issue #)
=> #961 fix logout button

src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/TaskListNotesModal.tsx
Removed frontend requirement for creating notes
Closes #980  (issue #)
=> #980 Remove Requirement for notes/assignees

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
Not exactly sure if I did this right.
Closes #996
=> #996 added my name to the credits

src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/ProjectDetails.tsx
links on project details page open in a new tab 
Closes #975
=> #975: links open in different tabs

src/frontend/src/pages/WorkPackageDetailPage/ActivateWorkPackageModalContainer/ActivateWorkPackageModal.tsx
Changed the layout of the form for the Work packages, such that it was no longer skinny, and the fields were beside each other
Still think it looks a bit off, width and height wise, and the title Activate's font size still seems small compared to the layout
Closes #927
=> #927-improve-layout-of-form-fields

src/frontend/src/pages/HomePage/UpcomingDeadlines.tsx, src/frontend/src/pages/HomePage/WorkPackageCard.tsx, src/frontend/src/pages/HomePage/WorkPackagesByTimelineStatus.tsx, src/frontend/src/tests/pages/HomePage/UpcomingDeadlines.test.tsx, src/frontend/src/tests/pages/HomePage/WorkPackagesByTimelineStatus.test.tsx
some ui changes
Closes #898  (issue #)
=> #898 revamp work package cards

src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/TaskList.tsx, src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/TaskListTabPanel.tsx
Fixed Task Perms and Weird toast display that displayed success no matter what. 
Closes #1020 (issue #)
=> #1020 Fix Permissions and Toast Display

src/frontend/src/pages/CreateProjectPage/CreateProjectFormView.tsx
Import MouseEventHandler from react
Removed any from onCancel
- yarn test:backend
- yarn test:frontend
Closes #674
=> #674: Import MouseEventHandler remove any from CreateProjectFormView

src/backend/tests/risks.test.ts, src/backend/tests/test-data/risks.test-data.ts
Added desired test for deleteRisk, also added two new risk test data for these test
the target risk doesn't exist
the target risk has already been deleted
the user doesn't have permissions to delete the risk
it works as intended
Closes #242 (issue #)
=> #242 added all test

src/frontend/src/pages/ProjectDetailPage/ProjectPage.tsx, src/frontend/src/pages/WorkPackageDetailPage/WorkPackagePage.tsx
After edit mode, the url is reset
doesn't exactly reset the Boolean to false like we talked about, but take it out of edit mode permanently. 
Closes #290
=> #290 - Update ProjectPage.tsx

src/frontend/src/layouts/Sidebar/Sidebar.tsx, src/frontend/src/pages/ChangeRequestsPage/ChangeRequestsTable.tsx
=> #1007: Open Change Request in new tab

src/frontend/src/pages/GanttPage/GanttPackage/components/other/Tooltip.tsx, src/frontend/src/utils/gantt.utils.ts
- Fixed "No Team" Gantt filter.
- Refactored Gantt Tooltip.
Closes #969, #994
=> #969, #994 - Gantt Fixes

src/frontend/src/pages/WorkPackageDetailPage/WorkPackageViewContainer/WorkPackageDetails.tsx
Changed Project Lead and Project Manager to Lead and Manager in WorkPackageDetails
Changes in a normal sized window:
Changes in the smallest window size:
Closes #1037
=> #1037 Switched Project Lead to Lead on WPDetails

src/backend/src/controllers/users.controllers.ts
=> #692 Changed any type with request and response

src/frontend/src/components/ReactHookEditableList.tsx
Changed the two any types to more specific types.
The first worked, the second any type (append) created issues in other files and wouldn't work despite the work of Megan and  Ari.
register still has an any type within the UseFormRegister and could still possibly be narrowed down. append would likely use UseFieldArrayAppend but was creating issues with other files, so it is still an any type. This is currently a draft and in need of help from other people (Anthony).
- Narrow down the type going into UseFormRegister
- Fix the issues with UseFieldArrayAppend so that it can be used as the type for append
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) …
=> #670: replace all any type (draft)

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
Added my name to the credits page (+ a little gradient)
Did this a little late oops
Closes #1016
=> #1016: Add my name to credits page

src/backend/src/utils/work-packages.utils.ts
Changed two instances of any in the work-packages.utils.ts file to not be any.
I think I did this correctly, but not 100% sure so please provide feedback if necessary.
Closes #705
=> 705: Removed any from work-packages.utils.ts

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
- Case A
- Edge case
- ...
Normal Window:
Smallest Possible Window:
N/A
Closes #1069 (issue #)
=> #1069-EthanMouri-credits

src/shared/src/backend-supports/projects-get-all.ts
removed the any type on line 20 and replaced it with a WP array
Closes #711
=> #711: removed any type from projects-get-all

src/frontend/src/pages/CreateChangeRequestPage/CreateChangeRequestView.tsx
I changed the explain box on the change request file so that it expands as you type
Used the mui multiline prop to make the text box expandable.
Closes #1033
=> #1033: Made Explain Text Expandable

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
Added my name to the credits.
No extra notes
No test cases
Closes #1092  (issue #1092)
=> #1092 Added my name to credits

src/frontend/src/apis/work-packages.api.ts, src/frontend/src/pages/CreateWorkPackagePage/CreateWorkPackageForm.tsx
changed all any types from work-packages.api.ts into the proper data type (CreateWorkPackageFormInputs)
Closes #710
=> #710 changed any type to a given interface

src/frontend/src/components/ChangeRequestDetailCard.tsx, src/frontend/src/pages/ChangeRequestsPage/ChangeRequestsTable.tsx
Card For Change Requests
Closes #1038  (issue #)
=> #1038 Change Request Card

src/frontend/src/app/AppAuthenticated.tsx, src/frontend/src/app/AppPublic.tsx, src/frontend/src/pages/HomePage/Home.tsx, src/frontend/src/pages/HomePage/SetUserPreferences.tsx
they have no choice, they can't go to any webpage if it isn't set
i guess they could set a fake one though
Closes #1115
=> #1115: force users to set slack ids

src/backend/src/prisma/migrations/20230501182137_finance/migration.sql, src/backend/src/prisma/schema.prisma
Finance schema
Closes #1117 (issue #)
=> #1117 Finance Schema

src/frontend/src/pages/WorkPackageDetailPage/WorkPackageViewContainer/WorkPackageViewContainer.tsx
added tabs to wp detail page
Closes #1121 (issue #)
=> #1121 - add tabs

src/backend/src/utils/change-requests.utils.ts
Restricted approved change requests to only be valid for 5 days. Now, if users try to tie changes to CR that is reviewed more than 5 days, the error message will pop up.
**All available CRs on the date 05/17/2023:**
**Note that CR 3 is reviewed recently while 2 is outdated**
**Editing the project by tieing the changes to change request 3 works:**
**Editing the project by tieing the changes to change request 2 doesn't work:**
=> #922: restricted approved change requests to only be valid for 5 days

src/frontend/src/hooks/users.hooks.ts, src/shared/src/types/user-types.ts, yarn.lock
Created database UserRole to replace two mentions of datatype 'any' within the file users.hooks
Closes #689 (issue #689)
=> #689-RemoveAnyTypeFrom-users.hooks

src/frontend/src/pages/ProjectDetailPage/ProjectEdit/ProjectEditContainer.tsx, src/frontend/src/pages/ProjectDetailPage/ProjectEdit/ProjectEditDetails.tsx
Made the drop downs into autocompletes
doesn't successfully edit the project manager or lead
Closes #1034
=> #1034 project edit user select auto complete

src/backend/src/controllers/reimbursement-requests.controllers.ts, src/backend/src/routes/reimbursement-requests.routes.ts, src/backend/src/services/reimbursement-requests.services.ts, src/backend/tests/reimbursement-requests.test.ts, src/backend/tests/test-data/reimbursement-requests.test-data.ts
1. Created new reimbursement request route
2. Created new reimbursement request controller to handle the updating
3. Created new reimbursement request service to process the update
4. Created tests
Closes #1130
=> 1130 finance mark delivered endpoint

src/backend/src/controllers/reimbursement-requests.controllers.ts, src/backend/src/routes/reimbursement-requests.routes.ts, src/backend/src/services/reimbursement-requests.services.ts, src/backend/tests/reimbursement-requests.test.ts
Get All Expense Types Endpoint
Closes #1145 (issue #)
=> #1145 get all expense types

src/backend/src/controllers/reimbursement-requests.controllers.ts, src/backend/src/routes/reimbursement-requests.routes.ts, src/backend/src/services/reimbursement-requests.services.ts, src/backend/tests/reimbursement-requests.test.ts, src/backend/tests/test-data/reimbursement-requests.test-data.ts, src/backend/tests/test-data/users.test-data.ts
Created get Single Reimbursement Request Endpoint
Closes #1129  (issue #)
=> #1129 Get Single Reimbursement Request

src/frontend/src/pages/ChangeRequestsPage/ChangeRequestsOverview.tsx
CRs that are marked as accepted will show up in the accepted CRs section even if theyre not implemented
It works
Closes #1228  (issue #)
=> #1228 Fix Accepted Bug

src/frontend/src/pages/CreateWorkPackagePage/CreateWorkPackageForm.tsx, src/frontend/src/pages/CreateWorkPackagePage/CreateWorkPackageFormView.tsx, src/frontend/src/tests/pages/CreateWorkPackagePage/CreateWorkPackageForm.test.tsx, src/frontend/src/tests/pages/CreateWorkPackagePage/CreateWorkPackageFormView.test.tsx
Played around with the values of md and xs in the code to see what fit.
Commented out Work package stage
I forgot to uncomment the work package stage, will make another commit once I create this pull request
Closes #926
=> #926 new work package form

src/frontend/src/apis/finance.api.ts, src/frontend/src/hooks/finance.hooks.ts, src/frontend/src/pages/FinancePage/ReimbursementRequestDetailPage/ReimbursementRequestDetailsView.tsx, src/frontend/src/utils/urls.ts
Same as the other one but for mark delivered instead of delete
Closes #1262  (issue #)
=> #1262 - add confirm mark delivered modal

src/frontend/src/apis/finance.api.ts, src/frontend/src/hooks/finance.hooks.ts, src/frontend/src/pages/FinancePage/ReimbursementRequestDetailPage/ReimbursementRequestDetailsView.tsx, src/frontend/src/utils/urls.ts
Added this modal that pops up when you try to delete a reimbursement request. Wired up to the delete endpoint in the backend
Closes #1261  (issue #)
=> #1261 - add and hook up delete modal

src/backend/src/transformers/auth-user.transformer.ts, src/backend/src/utils/google-integration.utils.ts, src/backend/src/utils/reimbursement-requests.utils.ts, src/frontend/src/apis/finance.api.ts, src/frontend/src/hooks/finance.hooks.ts, src/frontend/src/pages/FinancePage/FinanceComponents/PendingAdvisorListModal.tsx, src/frontend/src/pages/FinancePage/FinancePage.tsx, src/frontend/src/pages/FinancePage/ReimbursementRequestForm/ReimbursementRequestForm.tsx, src/frontend/src/utils/reimbursement-request.utils.ts, src/frontend/src/utils/urls.ts, src/shared/src/types/reimbursement-requests-types.ts, src/shared/src/types/user-types.ts
Created the Pending Advisor List Modal
Closes #1221  (issue #)
=> #1221 Pending Advisor List

src/backend/src/controllers/users.controllers.ts, src/backend/src/routes/users.routes.ts, src/backend/src/services/users.services.ts, src/frontend/src/apis/finance.api.ts, src/frontend/src/apis/users.api.ts, src/frontend/src/hooks/finance.hooks.ts, src/frontend/src/hooks/users.hooks.ts, src/frontend/src/pages/FinancePage/ReimbursementRequestDetailPage/ReimbursementRequestDetailsView.tsx, src/frontend/src/pages/FinancePage/ReimbursementRequestDetailPage/SubmitToSaboModal.tsx, src/frontend/src/pages/FinancePage/ReimbursementRequestForm/ReimbursementFormView.tsx, src/frontend/src/utils/reimbursement-request.utils.ts, src/frontend/src/utils/urls.ts, src/shared/src/types/reimbursement-requests-types.ts, src/shared/src/types/user-types.ts
Clicking approve on the detail page opens the modal (only enabled if you're a finance team member, and the RR hasn't been sabo submitted yet). Once open, the finance team member would input all this info into the sabo form then hit 'Sabo to Sabo' when they're done, marking the RR as submitted to sabo (or pending advisor).
Closes #1222  (issue #)
=> #1222 review reimbursement request

src/backend/src/routes/reimbursement-requests.routes.ts, src/frontend/src/apis/finance.api.ts, src/frontend/src/pages/FinancePage/ReimbursementRequestForm/ReimbursementFormView.tsx, src/frontend/src/pages/FinancePage/ReimbursementRequestForm/ReimbursementRequestForm.tsx
You can now upload pdfs! Should work with generate all receipts as well. Trying out some stuff with the Multer config j to see what it does on prod, not really sure that that'll fix anything
Closes #1291  (issue #)
=> #1291 upload pdf as receipt

.github/workflows/tsc-check.yml, .prettierignore, .vscode/settings.json, .vscode/tasks.json, package.json, src/backend/src/services/reimbursement-requests.services.ts, src/backend/tests/test-data/projects.test-data.ts, src/backend/tests/test-data/work-packages.test-data.ts, src/frontend/src/layouts/PageTitle/PageBreadcrumbs.tsx, src/frontend/src/layouts/PageTitle/PageTitle.tsx, src/frontend/src/pages/FinancePage/CreateReimbursementRequest.tsx, src/frontend/src/pages/FinancePage/EditReimbursementRequest/EditReimbursementRequest.tsx, src/frontend/src/pages/FinancePage/ReimbursementRequestForm/ReimbursementFormView.tsx, src/frontend/src/pages/FinancePage/ReimbursementRequestForm/ReimbursementProductTable.tsx, src/frontend/src/pages/WorkPackageDetailPage/ActivateWorkPackageModalContainer/ActivateWorkPackageModal.tsx, src/frontend/src/pages/WorkPackageDetailPage/WorkPackageEditContainer/WorkPackageEditDetails.tsx, src/frontend/src/tests/hooks/Users.hooks.test.tsx, src/frontend/src/tests/layouts/PageTitle/PageBreadcrumbs.test.tsx, src/frontend/src/tests/test-support/mock-hooks.ts, src/frontend/src/tests/test-support/test-data/projects.stub.ts, src/frontend/src/tests/test-support/test-data/test-utils.stub.ts, src/frontend/src/tests/test-support/test-data/users.stub.ts, src/frontend/src/tests/test-support/test-data/work-packages.stub.ts, tsconfig.build.json
Added VSCode TS Checker + Cleaned up all code
Closes #1302  (issue #)
=> #1302 add ts checker

src/frontend/src/pages/FinancePage/ReimbursementRequestDetailPage/ReimbursementRequestDetailsView.tsx, src/frontend/src/pages/FinancePage/ReimbursementRequestsSection.tsx, src/frontend/src/tests/utils/pipes.utils.test.ts, src/frontend/src/utils/pipes.ts
Add box to RR page. Refactor some pipes for undefined dates.
It's all alone on the left side, MUI Grid doesn't naturally allow for it to be centered but maybe there's a trick idk
See screenshots.
- No Sabo (placeholder ----)
- No Sabo but marked as delivered (displays date)
- Before delivery but after Sabo: (displays placeholder ----)
- After delivery and Sabo (date shows up)
Undefined pipes on Request Table
Small screen
Closes #1306
=> #1306 - Add Date Delivered Box to RR Detail Page

src/backend/src/controllers/reimbursement-requests.controllers.ts
Not sure if cors is already doing this automatically in the backend, but couldn't hurt to try this
=> add Access-Control-Allow-Origin to express respone

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
Added my name to credits.
My name is yellow.
Closes #1337
=> #1337 Added my name to credits

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
I've added my name to the credits page
N/A
Closes #1339
=> #1339 - Added my name to credits

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
added a new entry of my name and favorite color on line 98 along with adding a comma after the entry of line 97
closes #1351
=> #1351: Added my name to credits

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
Added my name and a color for it to the end of the names array in CreditsPage.tsx.
Full Screen
Little Screen
Closes #1354
=> #1354: Added my name to the credits page

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
Added my name in my selected color.
Closes #1348
=> #1348 added my name to credits

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
Added my name to line 98 of the code
Closes #1353
=> #1353-AmaniScarborough-credits

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
=> #1363: added my name to credits page

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
Added name to credits
My name is in turquoise!
Closes #1343
=> #1343 Added my name to credits

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
Added my name to the end of the credits page!
- Case A
- Edge case
- ...
Closes #1360
=> #1360: Added my name to credits

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
added my name to the credits
Closes #1370 (issue #)
=> #1370 Added my name to credits

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
Added my name to CreditsPage typescript file 
N/A
Closes #1371
=> #1371 Added my name to the credits page

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
added my name to the credits page
- Case A
- Edge case
- ... …
=> #1396: added my name to the credits page

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
=> #1382 Added my name to credit

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
=> #1340 Added my name to credits

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
Added my name to credits page
Closes #1392
=> #1392 added my name to credits

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
It took me a few tries to get the right command
Closes #1385
=> #1385: added my name to the credits page

README.md, src/frontend/src/pages/CreditsPage/CreditsPage.tsx
Went to FinishLine\src\frontend\src\pages\CreditsPage\CreditsPage.tsx and added 
`{ name: 'Teera Tesharojanasup', color: '#DC143C', sx: { px: 1, backgroundColor: '#E8D8CC', borderRadius: 10 } }`
on line 98.
Closes #1375
=> #1375 teera tesharojanasup credits

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
=> #1374 added my name

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
It's red color 
Closes #1379  (issue #)
=> #1379: added my name to the credits page

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
Added my name to credits
Closes #1373  (issue #)
=> #1373-SamanthaMoy-credits

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
Normal Sized Window:
Smallest Possible Window:
Closes #1388
=> #1388 Added my name to credits

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
It was okay. As I had no experience with Git, it was naturally challenging. I do feel that I have a basic grasp of how to use Git because of this activity. 
Closes #1372
=> #1372: Added my name to credits

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
I added my name to the credits page
Closes #1377  (issue #)
=> #1377: Added my name to credits

.env, src/frontend/src/pages/CreditsPage/CreditsPage.tsx
=> #1381 Added my name to credits

src/frontend/src/pages/FinancePage/ReimbursementRequestForm/ReimbursementRequestForm.tsx
I changed the default account value from CASH to BUDGET
N/A
Closes #1276
=> #1276 - Updated default account value

src/frontend/src/pages/ChangeRequestDetailPage/ChangeRequestDetailsView.tsx
Added the Review and Delete Icons to the Action dropdown in an unreviewed Change Request.
Closes #1057
=> #1057 Added icons to dropdown on CR detail page of unreviewed CR

src/frontend/src/pages/ChangeRequestDetailPage/ProposedSolutionForm.tsx
Changed Add button from type Button to type NERSuccessButton and removed button import
- [x ] All commits are tagged with the ticket number
- [ x] All code follows repository-configured prettier formatting
- [ x] No merge conflicts
- [ x] All checks passing
- [ x] Screenshots of UI changes (see Screenshots section)
- [ x] Remove any non-applicable sections of this template
- [ x] Assign the PR …
=> #716 jake wu chen buttonchange

src/frontend/src/pages/FinancePage/ReimbursementRequestForm/ReimbursementFormView.tsx
Filtered expense types to only show ones that are allowed on the create reimbursement page.
Closes #1279
=> #1279: Filtered out expense types to only include allowed ones.

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
=> #1386 Added my name to credits

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
Added my name to the credits array
- Case A
- Edge case
- ...
Closes #1435
=> #1435 Added my name to credits

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
=> #1446: added my name to the credits page

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
Added my name and color to the credits array.
Closes #1380
=> #1380 added my name to credits

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
I added my name to credits.
Closes #1470
=> #1470: Added my name to credits

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
Added my name to credits page.
Closes #1467
=> 1467 Added my name to credits

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
Added name to credits
Closes #1463
=> #1463: added my name to credits

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
added name to credits
Closes #1442
=> #1442: added my name to credits

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
Added my names for credits
Closes #1395  (#)
=> #1395 Added my name to credits

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
Added my name to credits.
I kind of struggled as I have minimal experience on github. I ran into some issues in the pull request as it was not giving me the option to make one when I would select my issue. Eventually I got it to work, but I am not sure if that caused me to make a pull request incorrectly.
_If you made UI changes you must post a screenshot of the whole page for each change in 1) a normal sized window and 2) the smallest possible window.
Closes #1341
=> #1341 added my name to the credits page.

src/frontend/src/pages/SettingsPage/UserSecureSettings/UserSecureSettings.tsx, src/frontend/src/pages/SettingsPage/UserSettings/UserSettings.tsx, src/frontend/src/tests/pages/SettingsPage/UserSettings/UserSettings.test.tsx
Moved the save and cancel button in user settings and user secure settings to the bottom of the form on mobile screens
Mobile Screens:
Laptop Screens:
Closes #1309
=> #1309 moved Cancel and Save button to the bottom of the form on mobile devices

src/frontend/src/pages/CreateChangeRequestPage/CreateChangeRequestView.tsx, src/frontend/src/tests/utils/validate-wbs.test.ts, src/shared/src/validate-wbs.ts
Added functionality for the CR create page to sort its dropdown for projects by wbs number
Closes # (issue #536)
=> 536 cr creation sort the wbs dropdown

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
Added my name to the credits.
1)
2)
Closes #1461
=> #1461 Added my name to credits

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
=> #1476 Added my name to credits

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
Added name to credits
Closes #1457
=> #1457 Added name to credits

src/frontend/src/pages/FinancePage/ReimbursementRequestForm/ReimbursementFormView.tsx, src/frontend/src/pages/FinancePage/ReimbursementRequestForm/ReimbursementRequestForm.tsx
Tests for if the current user has secure settings set in ReimbursementRequestForm.tsx and passes it as a prop to ReimbursementFormView component. In ReimbursementFormView.tsx,  if secure settings aren't set, disable submit button and custom toast warning with a link to settings page is conditionally rendered.
I made a custom toast in the ReimbursementFormView.tsx rather than using the toast hook we already have since the message property could only be a string and a link was needed in the message. This toast doesn't have an onClose, let me know if it should.
Warning (full screen)
Warning (small screeen)
No Warning (same as before since user has their secure settings set) …
=> #1310 enforce secure settings on create rr form

src/frontend/src/pages/FinancePage/ReimbursementRequestForm/ReimbursementProductTable.tsx, src/frontend/src/pages/FinancePage/ReimbursementRequestForm/ReimbursementRequestForm.tsx
Changed placeholder to "Select a Project" and a form label to "Project" in the reimbursement product table file
Removed the allWbsElements constant. Created a new constant, projectDropdown, to only show projects and not work packages in the dropdown menu
Closes #1277
=> #1277 only proj reimbursement

src/frontend/src/layouts/NavTopBar/NavTopBar.tsx
Got rid of "by NER" in the title when on mobile/smaller windows.
Closes #1480
=> #1480: Shortened title on smaller screens

src/backend/src/utils/google-integration.utils.ts, src/frontend/src/pages/FinancePage/ReimbursementRequestForm/ReimbursementRequestForm.tsx
See Ticket for details
Closes #1550  (issue #)
=> #1550 - Display Errors from Google API better

src/backend/src/controllers/teams.controllers.ts, src/backend/src/routes/teams.routes.ts, src/backend/src/services/teams.services.ts, src/backend/tests/teams.test.ts, src/frontend/src/apis/teams.api.ts, src/frontend/src/hooks/teams.hooks.ts, src/frontend/src/pages/TeamsPage/TeamMembersPageBlock.tsx, src/frontend/src/utils/urls.ts
Made an endpoint to be able to edit a teams lead
I'm back
Tested in postman
Before
Post
Closes #1244
=> #1244: set teams lead

src/frontend/src/layouts/NavTopBar/NavTopBar.tsx
=> fix color of nav top bar

src/backend/src/prisma/seed.ts, src/frontend/src/pages/FinancePage/ReimbursementRequestForm/ReimbursementFormView.tsx
Added a sort method to the allVendors list, sorting by alphabetical order (ReimbursementFormView.tsx line 122)
Added multiple vendors to test alphabetical order(seed.ts line 688)
Did not use localeCompare, instead created own comparison function for efficiency purposes.
- none
Closes #1424
=> #1424 vendors alphabetical sort

src/backend/src/services/reimbursement-requests.services.ts, src/backend/src/utils/reimbursement-requests.utils.ts, src/backend/tests/reimbursement-requests.test.ts, src/frontend/src/pages/FinancePage/FinancePage.tsx
Basically, Brody wants all the Finance team members to have all the perms because he said they all might need to interact with Sabo at some point, and also bc that's an easy list for him to add/ remove from. We can fine tune this later if we want, but for now he said ppl on his team like his assistant treasurer can't do what they need to do bc they aren't head of finance, so I wanna roll this out asap
Closes #1568  (issue #)
=> #1568 - all finance members have all perms

src/backend/src/prisma/seed-data/users.seed.ts, src/backend/src/prisma/seed.ts
Added 9 more "people" to the users.seed.ts file and then added those people to the orioles team in the seed.ts file
Closes #1532
=> #1532 added seed data to orioles

src/backend/src/prisma/seed-data/users.seed.ts, src/backend/src/prisma/seed.ts
I added 8 mock users to the user.seed.ts and seed.ts. Specifically to the ravens team
Closes #976
=> #976 added 8 members to team ravens

src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/ProjectDetails.tsx, src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/ProjectViewContainer.tsx
Added team name to the project page. 
There are multiple teams in the Finishline database that created projects. So every project is tagged with the creator of the project which is the team. It's under the Project details page under the overview tab.  …
=> #965 Added team name to project page

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
Added name to the Credits Page.
Closes #1589
=> #1589-Added name to credits

src/backend/src/prisma/seed.ts
The frontend only allows projects to be products on a reimbursement request now, but the seed data wasn't updated to reflect that and caused an error on the frontend when a work package was set as a product.
Found this when reviewing a PR
=> fix seed data

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
I added my name to the credits page on the FinishLine website. 
- since I'm on windows, I didn't know that I had to use single quotes to name my branch
- to view the changes I made, I learned that I had to have Dockser running in the background so that my computer had access to the database to open the website
Closes #1627 (issue #)
=> #1627: added my name to the credits

src/frontend/src/pages/FinancePage/ReimbursementRequestDetailPage/SubmitToSaboModal.tsx
Changed SubmitToSaboModal to display total cost in dollars instead of cents
=
Closes #1607
=> #1607: Changed cents to dollars for TotalCost

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
Added name to credits
Had to deal with merge conflict 
Closes #1631 (issue #)
=> #1631 bradford derby credits

src/backend/src/prisma/migrations/20231011234802_add_bom/migration.sql, src/backend/src/prisma/schema.prisma
=> #1479 typo fix

src/frontend/src/components/ReactHookEditableList.tsx, src/frontend/src/pages/CreateWorkPackagePage/CreateWorkPackageFormView.tsx, src/frontend/src/pages/ProjectDetailPage/ProjectEdit/ProjectEditContainer.tsx, src/frontend/src/pages/WorkPackageDetailPage/WorkPackageEditContainer/WorkPackageEditContainer.tsx
I changed the new ReactHookEditableList component to reflect the work done in [this](https://github.com/Northeastern-Electric-Racing/FinishLine/pull/1571) PR. I incorporated changes from that PR, including changing "title" to "bulletName", making widths percentage based, removing unecessary styling, and having the title be set where ReactHookEditableList is called, rather than in the EditableList itself. 
I did change the WorkPackageEditContainer, even though it is on another ticket, simply to reflect the change from "title" to "bulletName" other than that it is the same as it is on [this](https://github.com/Northeastern-Electric-Racing/FinishLine/pull/1571) PR.
The form looks like the Mock, except that the button is below the list, as requested in the other PR
Boxes stack in a grid
Boxes …
=> #1324 Changed ReactHookEditableList and associated forms

src/frontend/src/components/ReactHookEditableList.tsx, src/frontend/src/pages/ProjectDetailPage/ProjectEdit/ProjectEditContainer.tsx, src/frontend/src/pages/WorkPackageDetailPage/WorkPackageEditContainer/WorkPackageEditContainer.tsx
Expected activities and deliverables look like the mocks and looks better
Removed page blocks for the both
scrolls when there are more than 3 lines
Closes #1328
=> #1328-work package redesign, activities and deliverables

src/backend/src/prisma/migrations/20231019013832_add_bom/migration.sql, src/backend/src/prisma/schema.prisma
=> fixed spelling in schema

src/frontend/src/pages/ProjectsPage/ProjectsTable.tsx
When you click in, the all projects table is sorted so Active projects are at the top.
Closes #1458
=> #1458: All Projects Table filtered by ACTIVE

src/frontend/src/pages/FinancePage/ReimbursementRequestForm/ReimbursementRequestForm.tsx
Allowed products to be an item worth less than $1 in the create/edit reimbursement request form.
Closes #1657
=> #1657 Allowed product cost to be less than 1

src/backend/src/prisma/seed-data/teams.seed.ts, src/backend/src/prisma/seed-data/users.seed.ts, src/backend/src/prisma/seed.ts, src/frontend/src/layouts/Sidebar/Sidebar.tsx
-Created a team in teams.ts in seed data 
-Created 12 users in users.ts in seed data
-Added all the users into the team in seed.ts
Made a team and added 12 users as a seed.
Closes #1533
=> #1533 create new team with 12 members

src/frontend/src/pages/FinancePage/ReimbursementRequestsSection.tsx, src/frontend/src/utils/reimbursement-request.utils.ts
…ered column
Added a new column called Date submitted to sabo to the finance reimbursement request section and removed the date delivered column. Created a new util function to find the .dateCreated of the sabostatus object
Ran the yarn:frontend test and it passed
Closes #1580
=> #1580: added "Date Submitted to sabo" to reimbursement section

src/frontend/src/pages/FinancePage/ReimbursementRequestForm/ReimbursementProductTable.tsx, src/frontend/src/pages/FinancePage/ReimbursementRequestForm/ReimbursementRequestForm.tsx
Displays error messages below cost and description fields for products in finance form.
Closes #1666
=> #1666 Added error message for cost and description of products on finance form

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
I added my name to the credits page.
Closes #1679 (issue #)
=> #1679 Added my name to credits

src/frontend/src/components/VerticalDetailDisplay.tsx, src/frontend/src/pages/FinancePage/ReimbursementRequestDetailPage/ReimbursementRequestDetailsView.tsx
I modified VerticalDetailDisplay.tsx in the frontend to account for text-overflow, switched the font size from px to rem, and added a new style for scrollbars on the page.
I added a new style for scrollbars to tie the theme of the page together.
NOTE: I'm not sure about the scrollbar style compatibility with different web browsers, so that's something to check later
https://github.com/Northeastern-Electric-Racing/FinishLine/assets/90310958/9de63d08-9465-4666-8b12-73cbda875028
Please request reviewers and ping on slack only after you've gone …
=> #1297 : Implementing first overflow option

src/frontend/src/hooks/finance.hooks.ts
Replaced the any keyword in src/frontend/src/hooks/finance.hooks.ts
Closes #1489
=> #1489 remove any keyword from finance.hooks.ts

src/frontend/src/components/ChangeRequestDropdown.tsx, src/frontend/src/components/NERAutocomplete.tsx, src/frontend/src/pages/ProjectDetailPage/ProjectEdit/ProjectEditContainer.tsx, src/frontend/src/pages/WorkPackageDetailPage/WorkPackageEditContainer/WorkPackageEditContainer.tsx, src/frontend/src/pages/WorkPackageDetailPage/WorkPackageEditContainer/WorkPackageEditDetails.tsx, src/frontend/src/pages/WorkPackageDetailPage/WorkPackageEditContainer/WorkPackageFormDetails.tsx
Changed WorkPackageEditDetails to WorkPackageFormDetails, changed all references to old name to match, modified fields inside of said file to match mock-up, and manipulated the NERAutocomplete and ChangeRequestDropdown file's height and width to match mock and also removed page block.
I think a potential issue is that I might need to make the changes I did in autocomplete and the dropdown optional inorder to not mess up any other page's design.
UPDATE: …
=> #1327 work package redesign details

src/backend/src/prisma/seed-data/users.seed.ts, src/backend/src/prisma/seed.ts, yarn.lock
Added 8 new users and added them to the husky team. 
Closes #1530
=> added 8 husky members to the huskies team

src/backend/src/prisma/seed-data/users.seed.ts, src/backend/src/prisma/seed.ts
I added more justice league character seed data to seed.ts and initialized them on users.seed.ts. 
I ran yarn test:frontend and yarn test:backend and saw the green pass symbol. I didn't create any new tests for my edits. 
- ...
Closes #1529
=> #1529: Added more data to seed.ts and initialized them on users.seeds.ts

src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/TaskList/TaskList.tsx
updated the code so that members are now able to create tasks for a project
Dick Grayson, who is a member of the Huskies team, can now create tasks for his project.
Closes #1512
=> Fixes Issue #1512: Members of a team should be able to create tasks

src/backend/src/controllers/work-packages.controllers.ts, src/backend/src/routes/work-packages.routes.ts, src/backend/src/services/work-packages.services.ts, src/backend/src/transformers/work-packages.transformer.ts, src/backend/tests/work-packages.test.ts
Created a new work packages endpoint.
Having trouble testing the endpoint. Still not too sure if the code works properly.
- [x ] All commits are tagged with the ticket number
Closes # (issue #1417 )
=> #1417 - get many work packages endpoint

src/backend/src/controllers/projects.controllers.ts, src/backend/src/prisma-query-args/manufacturers.query-args.ts, src/backend/src/routes/projects.routes.ts, src/backend/src/services/projects.services.ts, src/backend/src/transformers/manufacturer.transformer.ts, src/backend/tests/projects.test.ts, src/shared/src/types/project-types.ts
Made route, controller function, service function, transformer, query args, tests
Postman had it return [], don't think thats right
works properly
Closes #1519
=> #1519 get all manufacturers endpoint

src/frontend/src/pages/ProjectDetailPage/ProjectEdit/ProjectEditContainer.tsx
Got rid of page blocks
no idea if I need to do anything else? Mock was made a while ago and Zach said it looks good?
Closes #1323
=> #1323: removed page block

src/backend/src/services/reimbursement-requests.services.ts, src/backend/src/utils/reimbursement-requests.utils.ts, src/backend/tests/reimbursement-requests.test.ts, src/frontend/src/pages/FinancePage/ReimbursementRequestDetailPage/ReimbursementRequestDetailsView.tsx
Allowed any member of the finance team to edit RR's.
Closes #1658
=> #1658 Allowed finance team to edit all RR's

src/frontend/src/pages/FinancePage/ReimbursementRequestForm/ReimbursementFormView.tsx
Added a maxHeight property so that the left side will not expand at all. Created a constant variable to store the value.
Closes #1660
=> #1660 no expansion with too many products

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
I added my name and color to the names array
did not struggle that much
Closes #1668
=> #1668 added my name to the credits page

src/frontend/src/pages/SettingsPage/Settings.tsx, src/frontend/src/pages/SettingsPage/UserSettings/UserSettingsView.tsx, src/frontend/src/tests/pages/SettingsPage/UserSettings/UserSettingsView.test.tsx, src/frontend/src/utils/pipes.ts
Created displayEnum pipe that takes in string and changes it to lowercase. Example: IN_PROGRESS -> In Progress. Applied pipe to settings page
Closes #1249   (issue #)
=> #1249 Created displayEnum pipe and applied to settings page

src/backend/src/controllers/projects.controllers.ts, src/backend/src/prisma/migrations/20231116035430_material_name_prop_edit/migration.sql, src/backend/src/prisma/migrations/20231119042617_add_bom/migration.sql, src/backend/src/prisma/schema.prisma, src/backend/src/routes/projects.routes.ts, src/backend/src/services/projects.services.ts, src/backend/src/utils/errors.utils.ts, src/backend/src/utils/projects.utils.ts, src/backend/tests/projects.test.ts, src/backend/tests/test-data/projects.test-data.ts
Added material edit endpoint in 
- project routes
- project controller
- project service
Added tests for edit material endpoint
- updateMaterial (6)
✓ Update material fails if the given material does not exists
✓ Update material fails if the given material deleted
✓ Update material fails if the project of the material does not exists
✓ Update material fails if the project of the material deleted
✓ Update material fails if the submitter is not a leader or part of project team
✓ Update material successfully works
**Create new material for testing purposes:**
**The payload for the update material endpoint:**
**Update the material successfully:** …
=> #1526 edit material endpoint

src/backend/src/controllers/projects.controllers.ts, src/backend/src/prisma/migrations/20231116012435_material_type_date_deleted/migration.sql, src/backend/src/prisma/migrations/20231119054311_add_bom/migration.sql, src/backend/src/prisma/schema.prisma, src/backend/src/routes/projects.routes.ts, src/backend/src/services/projects.services.ts, src/backend/tests/projects.test.ts, src/backend/tests/test-data/projects.test-data.ts
- Created a delete material type route
- Created a controller
- Created a service function
- Tested the endpoint
Testing to delete a material
Deleting a material that does not exist
Deleting a material with a user without admin permissions
Closes #1524
=> 1524 Created the delete materials type endpoint and tested it

src/backend/src/controllers/projects.controllers.ts, src/backend/src/prisma-query-args/material-type.query-args.ts, src/backend/src/prisma/seed.ts, src/backend/src/routes/projects.routes.ts, src/backend/src/services/projects.services.ts, src/backend/src/transformers/manufacturer.transformer.ts, src/backend/src/transformers/material-type.transformer.ts, src/backend/tests/projects.test.ts, src/shared/src/types/project-types.ts
Added get all material types endpoints in
- project routes
- project controllers
- project services
Added tests for get all material types endpoint in project test file
✓ Get all Material Types fails from guest
✓ Get all Material Types works
=> #1520: added get all material types endpoint with the tests

src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/BOM/BOMTable.tsx, src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/BOM/MaterialForm/MaterialForm.tsx, src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/BOM/MaterialForm/MaterialFormView.tsx, src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/BOMTab.tsx, src/frontend/src/utils/bom.utils.ts
We were handling money as cents, need to do it as dollars as far as the user is concerned. Also moved up the assembly cost into their titles. It simplifies the page and kinda just makes sense
Closes #1723  (issue #)
=> #1723 - display as dollars

src/backend/src/services/reimbursement-requests.services.ts, src/frontend/src/apis/finance.api.ts, src/frontend/src/hooks/finance.hooks.ts, src/frontend/src/pages/FinancePage/ReimbursementRequestDetailPage/ReimbursementRequestDetailsView.tsx, src/frontend/src/utils/reimbursement-request.utils.ts, src/frontend/src/utils/urls.ts
Added an option in the individual reimbursement request page dropdown that allows someone on the finance team to mark a reimbursement request as denied.
Closes #1611
=> #1611 Deny Reimbursement Request Frontent

src/frontend/src/pages/WorkPackageDetailPage/DeleteWorkPackageModalContainer/DeleteWorkPackage.tsx
Work Package Delete Toast made it seem like you'd deleted a project
Closes #1739  (issue #)
=> #1739 - correct toast msg on wp delete

src/frontend/src/components/Tabs.tsx, src/frontend/src/layouts/PageTitle/PageTitle.tsx, src/frontend/src/pages/ChangeRequestsPage/ChangeRequestsTable.tsx
Redesigned the all CR page and moved up the tabs
Closes #1638  (issue #)
=> #1638 all cr redesign

src/frontend/src/pages/ChangeRequestDetailPage/ChangeRequestDetailsView.tsx, src/frontend/src/pages/ChangeRequestDetailPage/OtherChangeRequestsPopupTabs.tsx
new popup tab for same wbs crs
Closes #1642
=> #1642 cr popup same wbs

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
_Added my name to the credits page_
_Added a screenshot_
_
_
Closes #1734
=> #1734: added name to credits

src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/BOM/MaterialForm/MaterialForm.tsx, src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/BOM/MaterialForm/MaterialFormView.tsx
Apologies for the no-ticket/ me doing this. Want the Engineers to actually use this since we asked them to at the meeting Monday. I fixed an error where we weren't validating that the manufacturer name was filled out, so you could submit without it and get an error. Also went ahead and just added the ability for a user to add a manufacturer which we'd discussed previously.
=> Users can now add manufacturers in the bom form

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
Added my name to the credits.
Inspiration from Kaan Tural. Fingers crossed I don't bring down the entire website.
Closes #1774
=> #1774: added my name to credits

src/backend/src/transformers/material.transformer.ts, src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/BOM/BOMTable.tsx, src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/BOM/MaterialForm/EditMaterialModal.tsx, src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/BOM/MaterialForm/MaterialForm.tsx, src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/BOM/MaterialForm/MaterialFormView.tsx
Some more BOM bugs from Kevin, the main one here is that PDMFileName wasn't showing up in the table or the edit form. I also caught a floating point error when I tried to submit with a price of 2.30, and another one cause I accidentally set quantity to 2.3 and realized we weren't confirming that that fields and integer. My finance page also weirdly crashed pretty randomly one of the last times I was testing this, so if y'all can recreate that at all please lmk, cause that's not great.
Please request reviewers and ping on slack only after you've …
=> pdmFileName shows up now, caught a floating point error with price

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
Added my name and favorite color to credits.tsx
None :)
Closes #1800 (issue #1800)
=> #1800 Added my name to credits

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
added my name to the "names" array in CreditsPage.tsx
I had some issues with the database, so I deleted the database and reset it according to the env setup instructions.
- [X ] All commits are tagged with the ticket number
- [ X] No linting errors / newline at end of file warnings
- [X ] All code follows repository-configured prettier formatting
- [X ] No merge conflicts
- [X ] All checks passing
- [X ] Screenshots of UI changes (see Screenshots …
=> #1803-AnyaDasgupta-credits

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
Added the name Aahil Nishad to the credits page. 
No struggles :)
Closes #1834
=> #1834-AahilNishad-credits

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
Added the name Caio DaSilva to the credits
No major struggles.
Closes #1836
=> #1836-CaioDaSilva-credits

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
Added my name to the names array. Styled it with horizontal padding and gradient background.
N/A
- [ X] No linting errors / newline at end of file warnings
- [X ] All code follows repository-configured prettier formatting
- [X ] No merge conflicts
- [X ] All checks passing
- [X ] Screenshots of UI changes (see Screenshots section)
- [X ] Remove any non-applicable sections of this template
- [ X] Assign the PR to yourself
- [X ] No `yarn.lock` changes …
=> #1805-DaoHo-credits

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
added my name to the credits page in purple
Closes #1830
=> #1830-WaverlyHassman-credits

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
added a line in the credits file where i put my name and the color in turquoise!
Closes #1847
=> #1847-AarushGarg-credits

src/frontend/src/apis/finance.api.ts, src/frontend/src/hooks/finance.hooks.ts, src/frontend/src/pages/AdminToolsPage/FinanceConfig/AccountCodeFormModal.tsx, src/frontend/src/pages/AdminToolsPage/FinanceConfig/CreateVendorModal.tsx, src/frontend/src/pages/AdminToolsPage/FinanceConfig/EditVendorModal.tsx, src/frontend/src/pages/AdminToolsPage/FinanceConfig/VendorFormModal.tsx, src/frontend/src/pages/AdminToolsPage/FinanceConfig/VendorsTable.tsx, src/frontend/src/utils/urls.ts
Created a VendorFormModal
Created a CreateVendorForm based off that
Created an Edit one as well
added vendor payload
added vendor hook and api for Editing (not sure if I did correctly)
Closes #1451
=> #1451-edit-vendor-modal

src/frontend/src/pages/FinancePage/FinancePage.tsx
Disabled the "report refund" button for guests in the actions dropdown within the Finance page.
No notes.
- Disabled with Guest (Suki)
- Not disabled with App Admin (Thomas Emrax)
No steps remain.
Closes #1791
=> #1791: disabled report refund button for guests on finance page

src/frontend/src/apis/finance.api.ts, src/frontend/src/hooks/finance.hooks.ts, src/frontend/src/pages/FinancePage/ReimbursementRequestDetailPage/ReimbursementRequestDetailsView.tsx, src/frontend/src/utils/urls.ts
added an option to mark a RR as reimbursed in `ReimbursementRequestDetailsView.tsx`
- the user must be on the finance team, else the button is disabled
- the reimbursement request must not be denied or reimbursed, else the button is disabled
a non-reimbursed RR ui (full and min screen)
a reimbursed RR ui, i.e. button should be disabled (full and min screen)
Closes #1613
=> #1613 Add mark as reimbursed action button

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
=> #1858: added my name

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
Added name to names array
Closes #1842
=> #1842-DanielMa-credits

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
=> #1878: added my name to credits page

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
added name to credits 
Closes #1861
=> #1861: Added my name to credits

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
Added my name into the credits page
Checklist
It can be helpful to check the Checks and Files changed tabs.
[ ] All commits are tagged with the ticket number
[ ] No linting errors / newline at end of file warnings
[ ] All code follows repository-configured prettier formatting
[ ] No merge conflicts
[ ] All checks passing
[ ] Screenshots of UI changes (see Screenshots section)
[ ] Remove any non-applicable sections of this template
[ ] Assign the PR to yourself
[ ] No yarn.lock changes (unless dependencies have …
=> #1887 Added my name to credits

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
Added name to credits page with desired color
1) Normal Size Window
2) Smallest possible Window
Closes …
=> #1868 sarah zhang credits

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
I added my name.
Closes #1839  (issue #)
=> #1839 Added my name to credits

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
Added my name to the credits page. 
Struggled a little, but learned a lot.
Closes #1908
=> #1908 Added my name to the credits page.

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
Added name to the credits page
Struggled for a bit but pulled through and completed it.
Closes #1907
=> #1907: added my name to the credits page

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
Added Name to credits page
Closes #1909
=> #1909: added my name to credits

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
added my name to the credits page
no issues
Closes #1915
=> #1915 Add my name to credits

src/frontend/src/pages/CreditsPage/CreditsPage.tsx, yarn.lock
I have changed the credits page with my name added
Closes #1885 (issue #1885 )
=> #1885 Added my name to credits

src/frontend/src/pages/CreditsPage/CreditsPage.tsx, yarn.lock
Added name to Credits
-
Closes #1914
=> #1914 Added my name to credits

src/frontend/src/pages/CreditsPage/CreditsPage.tsx, yarn.lock
Added my name to credits.
Closes #1920
=> #1920 Added my name to credits

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
added my name to the credits page
Closes #1942
=> '#1942 added my name to the credits page'

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
=> #1954 Added my name to credits.

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
added my name to creditspage.tsx
Closes #1958
=> #1958: Added my name to credits

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
Added my name to the CreditsPage.tsx file and my favorite color
No additional notes needed
Wasn't sure how to tick all of these - but i have gone through them all, and everything seems fine.
Closes #1955
=> #1955 armaan mehra credits

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
Added name to credits page
N/A
N/A
N/A
Closes #1974
=> #1974 Added name to credits page

src/frontend/src/pages/AdminToolsPage/FinanceConfig/CreateVendorModal.tsx, src/frontend/src/pages/AdminToolsPage/FinanceConfig/EditVendorModal.tsx, src/frontend/src/pages/AdminToolsPage/FinanceConfig/VendorFormModal.tsx, src/frontend/src/pages/AdminToolsPage/FinanceConfig/VendorsTable.tsx
Added to yup schema to test if the vendor name is in the list of vendors already
included the vendors when making the vendor form modal
Closes #1444
=> #1444: yup alert if duplicate vendor names

src/frontend/src/pages/SettingsPage/Settings.tsx
Deleted Email ID from settings page, and slightly adjusted spacing to look normal
the wierd md(3) is somehow necessary
medium view:
Closes #1793
=> #1793 - Remove Email ID from Settings Page

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
Added my name to credits page and ran prettier 
- [done] All commits are tagged with the ticket number
- [done] No linting errors …
=> #1945 Added my name to credits page

src/frontend/src/pages/FinancePage/ReimbursementRequestsSection.tsx, src/frontend/src/utils/reimbursement-request.utils.ts
Added vendor property to reimbursement-request.utils.ts and then added Vendor column to Finance dashboard
Closes #1585
=> #1585: added vendor column

src/frontend/src/pages/CreateChangeRequestPage/CreateChangeRequest.tsx
changed error message
- Edited error message to say "at least one proposed solution is required!"
- Stops change request if there's no solution proposed
Already fixed issue, just changed the wording a bit. 
Closes #1778
=> error message

src/frontend/src/tests/app/AppContext.test.tsx
Changed props type from "any" to other values that made more sense in the file "AppContext.test.tsx".
Closes #1499
=> #1499: replaced instances of 'any' in AppContext.test.tsx

src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/BOMTab.tsx
I changed it so if the user is a guest then they can not make a new entry on BOM tab but it still works for other users
The button is disabled for all guest users
For Guest user:
For other users Ex. Admin:
Closes #1787
=> #1787-bom-new-entry-should-be-disabled-for-guests

src/backend/src/services/reimbursement-requests.services.ts, src/backend/tests/reimbursement-requests.test.ts
Checked if we already have a vendor with the same name in backend
edited tests and created new one
- If vendor already exists
Closes #1445
=> #1445 Duplicate vendor backend check and test

src/frontend/src/app/AppAuthenticated.tsx, src/frontend/src/app/SessionTimeoutAlert.tsx
- Created the SessionTimeoutAlert.tsx file with the error popup alert
- Updated the AppAuthenticated.tsx file to display the SessionTimeoutAlert when the user's session times out
- yarn test:backend + frontend pass all tests
None yet
- Manually test on FinishLine
Closes #1598
=> #1598 session timeout error popup

src/frontend/src/pages/FinancePage/ReimbursementRequestDetailPage/SubmitToSaboModal.tsx
_Changed sabo form index to be the correct account number when approved_
_
_
Closes #1608
=> #1608-finance-fixes-form-index-should-be-the-refund-source-not-just-the-same-number

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
Added my name to credits page
Closes #2025
=> #2025 Added my name to credits

src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/TaskList/TaskList.tsx, src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/TaskList/TaskListDataGrid.tsx
Made Notes an action menu item instead of its own column
Closes #1727
=> #1727: Made notes an action menu item

src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/TaskList/TaskListComponents.tsx
removed the singular instance of type 'any' for the appropriate reference and typing of 'o'
Had trouble looking for a 'replacement' for 'any' when the solution was to remove 'any'.
Code may have been updated mid-ticket, had trouble keeping track of changes. 
- [-] Screenshots of UI changes (see Screenshots section)
Closes #1497
=> #1497-remove-type-any-from-TaskListComponents.tsx

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
added my name to the credits page!
I had a few issues but figured them out!
Closes #2040 (issue #)
=> #2040 added my name to credits

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
Added my name to credits page
Closes # (issue #2058 )
=> #2058 Added my name to credits

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
added my name to credits
Closes #2070
=> #2070 addd my name to credits

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
Added my name and set color on the credits page
- [✓] All commits are tagged with the ticket number
- [✓] No linting errors / newline at end of file warnings
- [✓] All code follows repository-configured prettier formatting
- [✓] No merge conflicts
- [✓] All checks …
=> #2054: Added my name to the credits page

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
Added credits to page for first ticket
Closes #2072
=> #2029 Added my name to credits

src/backend/src/controllers/reimbursement-requests.controllers.ts, src/backend/src/routes/reimbursement-requests.routes.ts, src/backend/src/services/reimbursement-requests.services.ts, src/backend/src/utils/errors.utils.ts, src/backend/tests/reimbursement-requests.test.ts, src/backend/tests/test-data/reimbursement-requests.test-data.ts
I added an endpoint to change a reimbursement that only allows the creator to edit their reimbursement. It takes in an amount and date as a payload.
Currently adding backend tests
- when the user isn't the one who submitted the refund
- when the reimbursement doesn't exist
- when all the conditions have been met
Case: when the user is not the submitter of the reimbursement:
Success Case: when the user is the submitter and the reimbursement exists
Case: when the reimbursement doesn't exist
Please request reviewers and ping on slack only after …
=> #1582: added the endpoint and started doing the tests

src/frontend/src/hooks/finance.hooks.ts, src/frontend/src/pages/FinancePage/FinanceComponents/GenerateReceiptsModal.tsx, src/frontend/src/pages/FinancePage/FinancePage.tsx
Changed the name of the receipt to be receipt-STARTDATE-ENDDATE.pdf instead of receipt-CURRENTDATE.pdf
Closes #1938
=> #1938 - changed the name of the reciepts download

src/backend/src/integrations/slack.ts, src/backend/src/prisma/migrations/20240203205255_add_slack_threads_to_change_request/migration.sql, src/backend/src/prisma/schema.prisma, src/backend/src/services/change-requests.services.ts, src/backend/src/utils/change-requests.utils.ts, src/backend/tests/change-requests.test.ts
added new Slack utils to send messages as replies to other messages in a thread, sends replies to threads of the original CR notification in Slack with the new status (approved, implemented) and reacts to the message
new column in table from schema migration
slack notification on CR approved
slack notification on CR denied
Closes #1518
=> #1518 Reply to Slack thread on CR approved/implemented

src/backend/src/controllers/projects.controllers.ts, src/backend/src/prisma/migrations/20240205031253_changed_material_notes_to_optional/migration.sql, src/backend/src/prisma/schema.prisma, src/backend/src/prisma/seed.ts, src/backend/src/routes/projects.routes.ts, src/backend/src/services/projects.services.ts, src/backend/src/transformers/material.transformer.ts, src/backend/tests/projects.test.ts, src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/BOM/MaterialForm/MaterialForm.tsx, src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/BOM/MaterialForm/MaterialFormView.tsx, src/frontend/src/utils/bom.utils.ts, src/shared/src/types/bom-types.ts, yarn.lock
- made migration after editing schema to make notes optional
- made some backend changes with material classes and projects route
- made some frontend changes with the text to display "notes (optional)".
Closes # (issue #2001 )
=> #2001 made notes optional

src/frontend/src/pages/FinancePage/ReimbursementRequestForm/ReimbursementFormView.tsx
Added placeholder value to account code in reimbursement form view. 
Closes #1873
=> #1873 added a placeholder value to the account code

src/frontend/src/pages/ChangeRequestsPage/ChangeRequestsTable.tsx
I changed the color of the change requests table to a darker red
none
Closes #1957
=> #2088-table-highlight

src/backend/src/services/projects.services.ts, src/backend/tests/projects.test.ts, src/frontend/src/apis/projects.api.ts, src/frontend/src/hooks/projects.hooks.ts, src/frontend/src/pages/AdminToolsPage/AdminToolsPage.tsx, src/frontend/src/pages/AdminToolsPage/AdminToolsProjectsConfig.tsx, src/frontend/src/pages/AdminToolsPage/FinanceConfig/AccountCodeFormModal.tsx, src/frontend/src/pages/AdminToolsPage/ProjectsConfig/CreateLinkTypeModal.tsx, src/frontend/src/pages/AdminToolsPage/ProjectsConfig/LinkTypeFormModal.tsx, src/frontend/src/pages/AdminToolsPage/ProjectsConfig/LinkTypeTable.tsx, src/frontend/src/utils/types.ts, src/frontend/src/utils/urls.ts
Added a projects config component on the admin tools page to display the linktype, a button to create a new linktype is offered to the admins to create a new linktype.
1. Normal size admin tools:
2. Smallest size admin tools:
3. Normal size create modal:
4. Smallest size create modal:
The modal is scrollable.
5. Created linktype:
Closes #1544
=> #1544: added create LinkType frontend tool

src/backend/src/utils/auth.utils.ts
removed any types in auth.utils.ts using the types NextFunction from express and JwtPayload and VerifyErrors from 'jsonwebtoken'.
uses the VerifyCallback type in the index.d.ts file for err and decoded types in the jwt.verify function call.
the (err: any, decoded: any) argument is a VerifyCallback which means the decoded can be a string | JwtPayload | undefined, but only the JwtPayload would have a userId, so I threw an error if it wasn't a JwtPayload. …
=> #1502: removed any types in auth.utils.ts

src/backend/src/services/reimbursement-requests.services.ts, src/backend/src/utils/slack.utils.ts, src/backend/tests/reimbursement-requests.test.ts
Sends a notification in Slack for when a reimbursement request is denied. 
Ran locally 
Closes #1941
=> #1941 send a notif for deny reimbursement

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
added name to credits
Closes #2033
=> #2033 added name to credits

src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/BOM/BOMTable.tsx, src/frontend/src/utils/bom.utils.ts
Assembly materials are now hidden until their associated assembly is clicked, at which point they drop down. Created a Misc section for materials with no associated assembly. DataGrid updated to hold up to 100 values on 1 page. Arrows for dropdowns are just unicode characters, they can be easily changed.
Tested with up to 100 assemblies to ensure they stayed on 1 page, and with over 100 to ensure that switching between pages is still possible with the dropdowns.
Attaching a smallest possible window screenshot but like, please don't use the assemblies datagrid in a small window.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your …
=> #1950 made dropdowns for assemblies

src/frontend/src/hooks/finance.hooks.ts
moved invalidateQueries function into onSuccess command
I don't know how to test if it works
- [x ] All commits are tagged with the ticket number
- [ x] All code follows repository-configured prettier formatting
- [ x] No merge conflicts
- [ x] All checks passing
- [ x] Remove any non-applicable sections of this template
- [x ] Assign the PR to yourself
- [ x] No `yarn.lock` changes (unless …
=> #1768 moved invalidate queries into onSuccess

src/frontend/src/pages/FinancePage/ReimbursementRequestForm/ReimbursementFormView.tsx
- added a placeholder value for the refund source
- now displays "Select Refund Source" when no refund source is selected
[
]
Closes #1874 (issue #)
=> #1874 added placeholder for refund source

src/backend/src/controllers/users.controllers.ts, src/backend/src/routes/users.routes.ts, src/backend/src/services/users.services.ts, src/backend/src/transformers/user-schedule-settings.transformer.ts, src/backend/tests/test-data/users.test-data.ts, src/backend/tests/users.test.ts, src/shared/src/types/user-types.ts
added route to users that returns the specified user's schedule settings
user has no schedule settings
Successful Case:
User doesn't have settings
Submitter isn't the user
Closes #2009
=> #2009 added get user schedule settings endpoint

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
Added my name to Credits Page
Closes #2056  (issue #2056 )
=> Marcus Yi - Credits

src/frontend/src/pages/FinancePage/ReimbursementRequestForm/ReimbursementProductTable.tsx
Changed any to ReimbursementProductFormArgs
Closes #1493
=> #1493 refactoring remove any type from srcfrontendsrcpagesfinancepagereimbursementrequestformreimbursementproducttabletsx

src/backend/src/controllers/design-review.controllers.ts, src/backend/src/routes/design-review.routes.ts, src/backend/src/services/design-review.services.ts, src/backend/tests/design-reviews.test.ts
Get all design reviews endpoint
Get All Design Reviews works when there are change requests
Closes #2061
=> #2061 get all design reviews endpoint

src/backend/src/prisma/seed-data/teams.seed.ts, src/backend/src/prisma/seed-data/users.seed.ts, src/backend/src/prisma/seed.ts
Added a 'Finance' Team based on the makeup of the Justice League, adding team definition in teams.seed.ts, updating user.seed.ts with 8 members, and establishing roles in seed.ts as follows:
- monopolyMan (lead)
- mrKrabs (lead)
- richieRich (lead)
- johnBoddy (member)
- villager (member)
- francis (member)
- victorPerkins (member)
- kingJulian (member)
Also, removed the previous lines in seed.ts where 'Finance' team was being set to 'Justice League' (writing to the env file).
Please let me know if any other changes need to be made (adding more characters, if I need to keep the env code, etc.)! Also, first commit has the wrong issue number, that's on me.
Closes #2083
=> #2083 add finance team to seed data

src/frontend/src/pages/AdminToolsPage/AdminToolsPage.tsx
made the admin tools tabs instead of page blocks
currently a terrible implementation, we'll see if my brain can think of a better one
Closes #2128
=> #2128 admin tools tabs 

src/backend/src/prisma/migrations/20240313041159_add_iconname_to_teamtype/migration.sql, src/backend/src/prisma/schema.prisma, src/backend/tests/test-data/design-reviews.test-data.ts, src/shared/src/types/design-review-types.ts
Added iconName to TeamType schema
Closes #2199
=> #2199 add iconName to TeamType schema

src/backend/tests/test-data/projects.test-data.ts
added new manufacturer test data to projects.test-data.ts
Closes #2100
=> #2100: added manufacturer test data

src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/BOM/MaterialForm/MaterialFormView.tsx, src/frontend/src/utils/pipes.ts
Changed the manufacturer selection from a regular dropdown to an autocomplete.
N/A
Closes #2004
=> #2004 - Make BOM manufacturer select an autocomplete

src/frontend/src/pages/CalendarPage/CalendarPage.tsx, src/frontend/src/pages/CalendarPage/DesignReviewAttendeeModal.tsx, src/frontend/src/pages/FinancePage/FinanceComponents/ColumnHeader.tsx
Added a popup displaying the confirmation status of invitees
Closes #2227
=> #2227 Attendee Confirmation popup

src/frontend/src/components/Tabs.tsx, src/frontend/src/pages/AdminToolsPage/AdminToolsBOMConfig.tsx, src/frontend/src/pages/AdminToolsPage/AdminToolsFinanceConfig.tsx, src/frontend/src/pages/AdminToolsPage/AdminToolsPage.tsx, src/frontend/src/pages/AdminToolsPage/AdminToolsProjectsConfig.tsx, src/frontend/src/pages/AdminToolsPage/BOMConfig/ManufacturerTable.tsx, src/frontend/src/pages/AdminToolsPage/BOMConfig/MaterialTypeTable.tsx, src/frontend/src/pages/AdminToolsPage/BOMConfig/UnitTable.tsx, src/frontend/src/pages/AdminToolsPage/FinanceConfig/AccountCodesTable.tsx, src/frontend/src/pages/AdminToolsPage/FinanceConfig/VendorsTable.tsx, src/frontend/src/pages/AdminToolsPage/ProjectsConfig/LinkTypeTable.tsx
No more page blocks
Closes #2152
=> #2152 removed page blocks from project config

src/backend/src/services/design-reviews.services.ts, src/backend/src/utils/slack.utils.ts, src/frontend/src/apis/design-reviews.api.ts, src/frontend/src/hooks/design-reviews.hooks.ts, src/frontend/src/pages/SettingsPage/UserScheduleSettings/Availability/AvailabilityEditModal.tsx, src/frontend/src/pages/SettingsPage/UserScheduleSettings/UserScheduleSettings.tsx, src/frontend/src/pages/SettingsPage/UserScheduleSettings/UserScheduleSettingsEdit.tsx, src/frontend/src/pages/SettingsPage/UserScheduleSettings/UserScheduleSettingsView.tsx, src/frontend/src/utils/urls.ts
Added in flow on the user settings page to confirm availability for a design review
Closes #2228  (issue #)
=> #2228 - update slack ping, setup confirm availability flow

src/frontend/src/pages/AdminToolsPage/AdminToolsPage.tsx, src/frontend/src/pages/AdminToolsPage/AdminToolsUserManagement.tsx, src/frontend/src/pages/AdminToolsPage/TeamsTools.tsx
Removed page blocks from the user management tab
Closes #2140
=> #2140 rm page blocks from user management

src/frontend/src/pages/AdminToolsPage/AdminToolsAttendeeDesignReviewInfo.tsx, src/frontend/src/pages/AdminToolsPage/AdminToolsPage.tsx, src/frontend/src/pages/AdminToolsPage/AdminToolsSlackUpcomingDeadlines.tsx
Removed page blocks from the misc tab
Closes #2142
=> #2142 Removed Page Blocks form the Misc Tab of Admin Tools

src/frontend/src/apis/design-reviews.api.ts, src/frontend/src/hooks/design-reviews.hooks.ts, src/frontend/src/pages/CalendarPage/DesignReviewDetailPage/DesignReviewDetailPage.tsx, src/frontend/src/utils/urls.ts
hook and api for deleteDesignReview
After using the delete icon / modal
Closes #2028
=> #2028 use delete design review hook

src/frontend/src/pages/AdminToolsPage/AdminToolsAttendeeDesignReviewInfo.tsx
Added attendee tracking admin tool 
Some of this code is hella inefficient
Closes #2238
=> #2238 Attendee Tracking

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
added my name to the credits array in the CreditsPage.tsx
It can be helpful to check the Checks and Files changed tabs.  
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.  
☐ All commits are tagged with the ticket number
☐ No linting errors / newline at end of file warnings
☐ All code follows repository-configured prettier formatting
☐ No merge conflicts
☐ All checks passing
☐ Screenshots of UI changes (see Screenshots section)
☐ Remove any non-applicable sections of this template
☐ Assign the PR to yourself
☐ No yarn.lock changes (unless dependencies have …
=> #2239 Added my name to credits.

src/backend/tests/design-reviews.test.ts
I removed the date from the test. Now it just uses the current date, ensuring it will always pass.
Closes #2257
=> #2257 removed set date from design review succeeds test

src/frontend/src/components/ChangeRequestRow.tsx, src/frontend/src/pages/ChangeRequestsPage/ChangeRequestsOverview.tsx, src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/ChangeRequestTab.tsx, src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/ProjectViewContainer.tsx, src/shared/src/types/change-request-types.ts
Added a change request tab to each project
In this tab there is a list of change requests for this project
List of change requests are in card format split into approved and unreviewed
Closes #2106
=> #2106: added related change request tab

src/frontend/src/app/AppAuthenticated.tsx, src/frontend/src/layouts/Sidebar/Sidebar.tsx, src/frontend/src/pages/HomePage/WorkPackagesByTimelineStatus.tsx, src/frontend/src/tests/layouts/Sidebar/Sidebar.test.tsx
The width of the main container is now determined based on whether the sidebar is open or not. Moved sidebar state logic outside of the sidebar component. Width of the container is calculated based on the size of the screen and the width of the sidebar.
Closes #1369
=> #1369 remove horizontal scroll bar

src/frontend/src/pages/ChangeRequestDetailPage/ProposedSolutionForm.tsx, src/frontend/src/pages/ChangeRequestDetailPage/ProposedSolutionView.tsx, src/frontend/src/pages/ChangeRequestDetailPage/ProposedSolutionsList.tsx, src/frontend/src/pages/CreateChangeRequestPage/CreateProposedSolutionsList.tsx, src/frontend/src/tests/pages/ChangeRequestDetailPage/ProposedSolutionForm.test.tsx, src/frontend/src/tests/pages/ChangeRequestDetailPage/ProposedSolutionView.test.tsx, src/frontend/src/utils/form.ts
You can now edit proposed solutions when creating a CR
- You have multiple proposed solutions
- You edit a PS multiple times
- You edit multiple PS
Closes #1728
=> #1728 added proposed solutions edit

src/backend/src/prisma/seed.ts, src/backend/src/services/design-reviews.services.ts, src/backend/tests/mocked/design-reviews.test.ts
- Was previously getting an error saying `TypeError: dateScheduled.toDateString is not a function`
- Fixed create design review error
Closes #2298
=> #2298 fixed date schedule error

src/backend/src/utils/auth.utils.ts
Corrected the route checking in the auth middleware for the notifications endpoints
Closes #2302
=> #2302 Edit auth middleware to check correct route

src/backend/src/prisma/seed-data/teams.seed.ts, src/backend/src/prisma/seed-data/users.seed.ts, src/backend/src/prisma/seed.ts
added a team in the seed data named Mean Girls
Closes #2076
=> #2076: made seed data for slackbot testing

src/frontend/src/components/TableCustomToolbar.tsx, src/frontend/src/pages/ChangeRequestsPage/ChangeRequestsTable.tsx, src/frontend/src/pages/ProjectsPage/ProjectsTable.tsx
Made project table look like CR table
Closes #1956
=> #1956 Make project table look like change request table

src/backend/src/prisma/seed.ts
added three team test data
Closes #2293 (issue #)
=> #2293 team types seed data

src/frontend/src/components/ActionsMenu.tsx, src/frontend/src/pages/CalendarPage/CalendarPage.tsx
On the calendar page, the My Unconfirmed DRS dropdown button doesn't have anything. I just added a disabled button that that says "My Unconfirmed DRS" as a place holder. 
Closes #2256
=> #2256 Added the No Unconfirmed DRS button

src/frontend/src/pages/CreditsPage/CreditsPage.tsx
Added name with color of choice to Credits
Added screenshot with smallest size possible and assigned myself to the PR
N/A
N/A
N/A
Closes # (issue #2338 )
=> #2338 put my name on credits page

src/backend/src/prisma/schema.prisma, src/backend/src/services/design-reviews.services.ts
fixed comments to accurately represent 
Closes #2340
=> #2340-fixed-comments-for-design-review-time-descriptions

src/frontend/src/hooks/change-requests.hooks.ts
updated created standard cr hook
=> #2352 updated create standard cr hook

src/frontend/src/app/AppAuthenticated.tsx
I accidently set a limit on the size of the main container. I removed that limit.
Closes #2351
=> Removed limit on main container size

src/backend/src/controllers/reimbursement-requests.controllers.ts, src/backend/src/routes/reimbursement-requests.routes.ts, src/backend/src/services/reimbursement-requests.services.ts, src/backend/tests/mocked/reimbursement-requests.test.ts
=> #1932: Delete Vendor Endpoint

src/frontend/src/components/CopyToClipboardButton.tsx, src/frontend/src/components/DetailDisplay.tsx, src/frontend/src/pages/FinancePage/ReimbursementRequestDetailPage/SubmitToSaboModal.tsx
Created CopyToClipboard const to handle the copying logic and displaying the icon. 
Added new copy component for each sabo field 
add copy to clipboard component to its own file? 
Closes #2280
=> #2280 Added Buttons to Copy to Clipboard

src/backend/src/services/change-requests.services.ts, src/backend/src/utils/validation.utils.ts, src/frontend/src/pages/ProjectDetailPage/ProjectForm/ProjectCreateContainer.tsx, src/frontend/src/pages/ProjectDetailPage/ProjectForm/ProjectEditContainer.tsx, src/frontend/src/pages/WorkPackageForm/WorkPackageForm.tsx, src/frontend/src/pages/WorkPackageForm/WorkPackageFormView.tsx, src/shared/src/types/change-request-types.ts
weeeeeee
Closes #1904  (issue #)
=> #1904 - add in project edit

src/frontend/src/apis/team-types.api.ts, src/frontend/src/apis/teams.api.ts, src/frontend/src/hooks/team-types.hooks.ts, src/frontend/src/hooks/teams.hooks.ts, src/frontend/src/pages/TeamsPage/SetTeamTypeModal.tsx, src/frontend/src/pages/TeamsPage/TeamSpecificPage.tsx, src/frontend/src/utils/urls.ts
- Added the set team type hook
- Set up the set team type modal
- Connected the modal to the teams specific page
- Set up default values
- Tested hook
Closes # (issue #2327 )
=> #2327 frontend for set team type modal and hook

src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/BOM/BOMTableCustomCells.tsx, src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/BOM/BOMTableWrapper.tsx, src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/TaskList/TaskListDataGrid.tsx
instead of a column, made notes and links into icons
Closes #1877
=> Put columns into icons for BOMS

src/frontend/src/pages/GanttPage/GanttChart.tsx, src/frontend/src/pages/GanttPage/GanttChartTeamSection.tsx
Removed the project button from the Gantt Chart
=> Removed project button from gantt chart

src/backend/src/services/change-requests.services.ts, src/backend/src/services/work-packages.services.ts, src/frontend/src/pages/ChangeRequestDetailPage/DiffSection/DiffPanel.tsx, src/frontend/src/pages/GanttPage/GanttChartComponents/AddProjectModal.tsx, src/frontend/src/pages/GanttPage/GanttChartComponents/AddWorkPackageModal.tsx, src/frontend/src/pages/GanttPage/GanttChartComponents/GanttChangeModals/GanttProjectCreateModal.tsx, src/frontend/src/pages/GanttPage/GanttChartComponents/GanttTaskBar/GanttTaskBar.tsx, src/frontend/src/pages/GanttPage/GanttChartComponents/GanttTaskBar/GanttTaskBarEdit.tsx, src/frontend/src/pages/GanttPage/GanttChartComponents/GanttTaskBar/GanttTaskBarView.tsx, src/frontend/src/pages/GanttPage/GanttChartPage.tsx, src/frontend/src/pages/GanttPage/GanttChartSection.tsx, src/frontend/src/pages/GanttPage/GanttChartTeamSection.tsx, src/frontend/src/utils/gantt.utils.ts
All teams should be shown on the Gantt Chart regardless of whether they have any projects - Peyton
Requesting reviewers on CRs is broken - Peyton
Blocker deadline change not called in auto implementing - Peyton
Work package stage not set from create on gantt chart - Peyton
=> Feature verification

.github/workflows/task-deadline-notifications.yml
Set environment to give actions access to the GitHub secret
Closes #2631
=> #2631 Set environment for action to allow access to secret

.github/workflows/task-deadline-notifications.yml
GitHub actions cron job now runs at 14 UTC (9 EST) instead of 9 UTC. Merge to main branch
Will be closed on merge to develop
=> #2641 Send notifications at 9am EST - Main branch
