src/frontend/src/pages/CreateChangeRequestPage/create-change-request-view.tsx

…mpact
Added checks for integer values when creating change requests to prevent decimal inputs in Timeline/Budget Impact fields.
None (tests for create change request page seem scarce?)
None? Does it make sense for things to only be integers? Should we allow people to add 1.5 weeks or a couple of cents to the budget?
Closes Northeastern-Electric-Racing/FinishLine#81

added integer checks for budget and timeline impact inputs

---

src/frontend/src/pages/ProjectDetailPage/project-view-container/project-details.tsx

Since fields "Expected Progress" and "Timeline Status" are unused in the project details page, they have been completely removed.
Related import into project-details.ts has also been removed.
Closes #114

#114 removed expected progress and timeline status from project-details

---

src/backend/src/controllers/work-packages.controllers.ts

Added checks in work package create and edit endpoints to stop requests where the dependencies include the package's own project or itself.
Could possibly instead use an OR instead of two passes through the dependencies in the edit endpoint. Let me know if this is preferred.
Closes #52

#52 stop self reference in dependency wp

---

src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/ProjectViewContainer.tsx

Moved up risk log visibly on the page
Very small change, physically just reordering things on the page
s
- Case A
- Edge case
- ...
_Any relevant screenshots go here_
Please review the [contributor guide](https://github.com/Northeastern-Electric-Racing/FinishLine/blob/develop/docs/ContributorGuide.md) and reach out to your squad if anything is unclear.

#133 - moving the risk log below summary above gantt chart

---

src/backend/src/controllers/risks.controllers.ts
src/backend/src/routes/risks.routes.ts
src/backend/src/utils/risks.utils.ts

adding the endpoint
This image shows me first editing just the detail, then resolving it (note that resolved by and time are now populated), then editing it but keeping it resolved (note that the resolved time doesn't change), then unresolving it (note that resolved by and time are now null)
Closes #69 nice

#69: Edit Risk Endpoint

---

src/backend/src/utils/projects.utils.ts

Now uses proper duration calculation function for project transformer return
why was this function just sitting there in utils
Another grueling ticket.
able)
Closes #24

#24-now-uses-proper-duration-util-function

---

src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/ProjectViewContainer.tsx

Updated the projects page so the WPs block appears above the changes block 
N/A
Have confirmed that WPs block is located above the changes block (screenshots are attached for reference)
N/A
Please review the [contributor guide](https://github.com/Northeastern-Electric-Racing/FinishLine/blob/develop/docs/ContributorGuide.md) and reach out to your squad if anything is unclear.

#149 Make WPs block appear above the changes block in projects page

---

src/backend/src/controllers/change-requests.controllers.ts
src/backend/src/routes/change-requests.routes.ts

The existing endpoint for approving change request needs to be modified to reflect the N-Proposed Solutions model. 
Added another check for approving to require that at least one proposed solution has been selected (`proposedSolution.approved`). Throws a 401 error if there is no solutions proposed, or none of the solutions are selected.
Approving process for other change requests are untouched.
Change Request has been modified to ...
Sending a POST request to the `/review` endpoint with:
```JSON
{
"reviewerId": 3,
"crId": 1,
"reviewNotes": "test",
"accepted": true
"psId": "1"
}
```
The result should be:
`Status 200: OK`
```JSON
{
"message": "Change request #1 successfully reviewed."
}
``` 
And update the `approved` field of the given proposed solution (psId: 1) to `true`.
Sending a POST …

#87: modifed endpoint for approving change requests

---

src/backend/src/controllers/work-packages.controllers.ts
src/backend/src/utils/projects.utils.ts
src/backend/src/utils/teams.utils.ts
src/backend/src/utils/users.utils.ts
src/backend/tests/work-packages.test.ts

We added some tests to the work-packages.test.ts file, mainly tests with checking for a valid WBS Element ID and tests checking for null dependencies.
Other changes included: 
in wp controller : `throw TypeError` replaced with `return res.status(400)`
in `userTransformer`, `projectTransformer`, `teamTransformer`:  `TypeError` check for null input removed because TypeScript enforces that the input cannot be null
Not sure if there's much else to do, but we'd like to double check before finalizing everything.
Closes #98

#98 backend errors 4xx

---

src/backend/src/prisma/migrations/20220929015048_make_description_bullets_checkable/migration.sql
src/backend/src/prisma/schema.prisma

Add `userChecked` (User relation) and `dateTimeChecked` (DateTime) to schema for Description_Bullet and made new migration
User relation isn't in the section labelled "Relation references" in `Description_Bullet` schema because it fits better with the checked DateTime than with the other relations
None
Closes #213

#213 - Update Description_Bullet with checked info

---

src/frontend/src/pages/ChangeRequestDetailPage/ProposedSolutionsList.tsx
src/frontend/src/pages/CreateChangeRequestPage/CreateProposedSolutionsList.tsx

Added an if-else statement so that if the user is a 'GUEST', the add proposed solution button would not be visible.
Had to refer to the string 'GUEST' instead of the role enum because enum would not function correctly
Tested logging in with each type of user to ensure the button was visible appropriately.
Closes #289

#289 hid add proposed solution button for guests

---

src/backend/src/utils/projects.utils.ts
src/backend/tests/projects.test.ts
src/backend/tests/projects.utils.test.ts

Write test cases for `createRulesChangesJson`
I'm mainly looking for feedback as I'm not sure this is ready to be merged yet. `createRulesChangesJson` is returning undefined in the tests, and the breakpoints I am setting in the function seem to never be getting hit. I'm not sure whether it's an issue with the tests or something with the setup on my computer, but looking at the tests, I'm not quite sure what the issue with them would be. Just want to make sure I'm not missing something or am otherwise misunderstanding something.
- Old rules and new rules are both empty
- Old rules is empty and new rules is not
- New rules is empty and old rules is not
- Both old rules and new rules are not empty
Please review the …

#253: Write tests for createRulesChangesJson

---

src/frontend/src/tests/components/ActionButton.test.tsx
src/frontend/src/tests/components/BulletList.test.tsx
src/frontend/src/tests/layouts/NavTopBar/NavNotificationsMenu.test.tsx
src/frontend/src/tests/layouts/NavTopBar/NavUserMenu.test.tsx
src/frontend/src/tests/layouts/PageBlock.test.tsx
src/frontend/src/tests/layouts/PageTitle/PageBreadcrumbs.test.tsx
src/frontend/src/tests/layouts/PageTitle/PageTitle.test.tsx
src/frontend/src/tests/layouts/Sidebar/NavPageLinks.test.tsx
src/frontend/src/tests/pages/HomePage/Home.test.tsx
src/frontend/src/tests/pages/ProjectDetailPage/ProjectEditContainer/ProjectEditContainer.test.tsx
src/frontend/src/tests/pages/ProjectDetailPage/ProjectViewContainer/RulesList.test.tsx
src/frontend/src/tests/test-support/mock-hooks.ts

Look at how many lines I'm able to delete!!!!
basically we can use jest.spyOn which is only one line each and we can save the mock values in another file which makes this super compact and we only ever have to write the mock for each hook once.
If we like this we can turn this into a lot of tickets
closes #294

#294: Better Frontend Testing

---

src/backend/src/controllers/work-packages.controllers.ts
src/frontend/src/utils/Pipes.ts

1. makes the date pipe do the right conversions (very weird just trust me or read my documentation)
2. makes the work package setting the date not have weird not have weird UTC to EDT issues by making it be midday instead of 00:00. basically when you edit a wp to start on 10/08/2022 that gets set as 10/08/2022 at 00:00 am UTC in the db. Then, when this gets sent back to the frontend, it converts to EDT which is -4 hours so it bcomes 10/07/2022 at 8:00 pm which is weird so adding 12 hours gets rid of this problem with most or all time zones. idk it works for all the main ones
overall pretty happy with this because i think it covers the main issues. Probably still some more to it but whatever, should get rid of the biggest weird stuff
- if you edit a work package but it goes from the same …

#204: Fixing Dates

---

src/backend/src/controllers/risks.controllers.ts

Currently, risks are too restrictive. Let's change that.
Creating risks previously required the user to be one of:
- APP_ADMIN, ADMIN, or LEADERSHIP
- The project lead or project manager of the project for the risk to be added to
This will be changed to be open to anyone who is not a GUEST.
Deleting risks had the same requirement as creating risks - this will be changed so that you can delete your own risk, no matter your role.
Conditions:
- Project 1 has 2 risks, both created by user `1`. The project lead is user `4`, and manager is user `5`. 
- User `6` is a MEMBER, User `7` is a GUEST.
Sending a POST request to `/risks/create` endpoint with:
```JSON
{
"projectId": 1,
"createdById": 6,
"detail": "this is a test."
}
```
The result should be:
`Status 200: OK`
```JSON
{
"message": …
```

#232: Make Risks Less Restrictive

---

src/backend/src/utils/projects.utils.ts
src/frontend/src/apis/Transformers/Projects.transformers.ts
src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/ProjectDetails.tsx
src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/WorkPackageSummary.tsx
src/frontend/src/tests/pages/ProjectDetailPage/ProjectViewContainer/WorkPackageSummary.test.tsx
src/frontend/src/tests/pages/WorkPackageDetailPage/WorkPackageViewContainer/WorkPackageDetails.test.tsx
src/frontend/src/tests/test-support/test-data/projects.stub.ts
src/frontend/src/utils/Pipes.ts
src/shared/src/backend-supports/project-supports.ts
src/shared/src/types/project-types.ts

Migrate the calculation of the project end date to the back-end where it belongs. Ensure the following happens:
Was a bit unsure how to edit the project-stubs.ts. All I did was manually put in an end date.
Closes #25  (issue #25 )

#25: end date calculation of logic moved to back-end

---

src/backend/tests/test-data/change-requests.test-data.ts
src/backend/tests/work-packages.test.ts

Added tests for edge cases of getChangeRequestReviewState function
- getChangeRequestReviewState returns null when changeRequest is not found
- getChangeRequestReviewState returns false when changeRequest has not been reviewed
Closes #264 (issue #264)

#264 backend test CreateWorkPackage endpoint part 2

---

src/backend/src/utils/work-packages.utils.ts
src/backend/tests/work-packages.test.ts

If there is no bullets, returned 0 for progress.
Created test to make sure it worked.
- if it returns zero when there is no bullets
Closes #379

#379-calculated-WP-progress-if-no-bullets

---

src/frontend/src/layouts/PageTitle/PageTitle.tsx
src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/ProjectViewContainer.tsx

Converted Project Details Actions Button from Boostrap to MUI
Closes #276

#276 - Converted Project Actions Button from Boostrap to MUI

---

src/frontend/src/components/CheckList.tsx

Added custom sort function ensure items being properly sorted, first based on whether bullet point is checked, and then based on alphanumeric order. Sorting based on resolved parameter ensures that even if bullet unchecked after being checked, will sort properly
Pre-Change:
Post-Change:
Closes #336

#336 Sort items before passing to checklist

---

src/frontend/src/pages/ChangeRequestsPage/ChangeRequestsTableView.tsx

Before, if the text didn't fit within the cell of the Change Requests table, the text would overflow onto the next column. Now, the text wraps and will go onto a new line if it overflows.
Full screen:
Smallest window:
Closes #22

#22: Add text wrapping to Change Requests table

---

src/frontend/src/pages/ProjectsPage/ProjectsTable.tsx

Similar deal to Change Requests table. Table now has word wrapping so text will go to the next line if it's about to overflow onto the next column.
Full Screen
Smallest Window
Closes #21

#21- Add text wrapping to Projects table

---

src/backend/index.ts
src/backend/src/controllers/risks.controllers.ts
src/backend/src/controllers/users.controllers.ts
src/backend/src/utils/utils.ts
src/frontend/src/utils/axios.ts

this pr will actually prevent people from impersonating other users in requests which might be the last step in our auth journey. well, except we have to replace every instance of the userid in a request with getting it from the res object. I did this for a few risk endpoints as an example, it's very easy. We can turn that into easy tickets which is always nice.
it can be sorta weird to understand this since we have two totally different flows for login on dev and prod but here's the easiest way to explain them:
**Dev**: choose a user to login as >> backend is cool with it as long as the user exists >> save that userId in localstorage >> send that userId as a header with every request >> backend gets the userid from the header and puts it on the res.locals
**Prod**: login with google >> …

#414 - More Auth

---

src/frontend/src/pages/WorkPackageDetailPage/StageGateWorkPackageModalContainer/StageGateWorkPackageModal.tsx

Converted stage gate WP modal to MUI
Old:
New:
Closes #402 (issue #)

#402 mui stage gate work package modal

---

src/backend/src/utils/description-bullets.utils.ts

Added another check to see if the project lead is editing the description bullets even if they are a member 
Case A: Member who is project lead checking description bullet 
Closes #409  (issue #)

#409 Allow project leads to check description bullets

---

src/frontend/src/components/WbsStatus.tsx
src/frontend/src/utils/Themes.ts

Change React Bootstrap Badge component in `WbsStatus.txt` to Material UI Chip component. (Looking at the documentation and trying both out, Chip seems more appropriate than Badge.) Increased text size from defaults for readability.
Refactor code in `WbsStatus.txt` to use mapping objects instead of local variables.
Override the theme to make Chip background gray using technique suggest in [this StackOverflow answer](https://stackoverflow.com/a/72543786). The palette's `secondary` color scheme (dark red) is very different from React Bootstrap's (gray). 
An alternative to the `textMap` object would be to do `status.toString()` and change the all-caps string representation to sentence-case. I chose textMap because it was simpler and more robust.
No tests were made for this specific MUI …

#385 - Transition to MUI WbsStatus.tsx

---

src/frontend/src/components/BulletList.tsx
src/frontend/src/components/ChangesList.tsx
src/frontend/src/layouts/PageBlock.tsx
src/frontend/src/tests/layouts/PageBlock.test.tsx

Added functionality to PageBlocks to make them collapse/expand on icon click in the upper right corner.
PageBlocks are open by default. I added a prop that allows it to be closed by default just in case it might be needed.
- Attempted to test if the content still renders when collapsed, apparently it does in the DOM but is just not visible.
Collapsed
Expanded
Collapsed (small)
Expanded (small)
Closes #103

#103 Make PageBlock Collapsable

---

src/frontend/src/layouts/Sidebar/Sidebar.tsx
src/frontend/src/stylesheets/layouts/sidebar/nav-page-links.module.css

- Removed React-Bootstrap import from Sidebar
- Changed some CSS to remove the link underlines
Removing the underline was not part of the ticket, but to be honest it looked really ugly, especially how it would turn purple if previously clicked (at least on my machine). Makes it look a lot cleaner + neater without it.
Existing tests were used.
Sidebar (Large)
Sidebar (Small)
Closes #386

#386 Transition Sidebar to MUI

---

src/frontend/src/pages/ChangeRequestsPage/ChangeRequestsTable.tsx
src/frontend/src/pages/ProjectsPage/ProjectsTable.tsx

Enabled quick filtering for data grids on the Projects Page and Change Requests Page.
n/a
n/a
Change requests page
projects page
n/a
Closes #505 (doesn't actually, cuz I just tossed this on the parent epic)

#505: add quick filters to data grids

---

src/backend/src/controllers/projects.controllers.ts
src/backend/tests/projects.test.ts

Made a check to see if the request body includes teamId. If it does not include teamId, a project is similarly created without any teamId, but if it is provided, it verifies for a valid teamId and if it is not, it will send a 404. if it is, it will create the project with the teamId. 
n/a
passed all tests
require a teamId in order to not check for an unprovided one.. transition to requiring teamIds
Closes #373

#373 newProject accounts for team

---

src/backend/src/transformers/change-requests.transformer.ts
src/backend/tests/test-data/change-requests.test-data.ts
src/frontend/src/pages/ChangeRequestDetailPage/ChangeRequestDetailsView.tsx
src/frontend/src/pages/ChangeRequestsPage/ChangeRequestsTable.tsx
src/frontend/src/tests/test-support/test-data/change-requests.stub.ts
src/shared/src/types/change-request-types.ts

Added WBS Name to cr
Restructured change request type to take in an object for wbs that includes both number and name, because you can only pass in one field to a column from what I could see. 
Closes #535  (issue #)

#535 Add Wbs Name to CRTable

---

src/frontend/src/layouts/NavTopBar/NavUserMenu.tsx
src/frontend/src/pages/LoginPage/LoginPage.tsx

Move `GoogleLogout` outside `MenuItem` so clicking anywhere on the `MenuItem` logs you out.
`GoogleLogout` with a [`render` prop seems to be a HOC](https://github.com/anthonyjgrove/react-google-login#login-props), so putting the menu item inside is okay.
(all pass)
Closes #727

#727 Fix logout button padding

---

src/frontend/src/pages/ProjectDetailPage/ProjectEdit/ProjectEditContainer.tsx

Changed the buttons of the submit and cancel to NERSuccessButton and NERFailButton. Also put the cancel on the left and the submit on the right.
Closes #713

#713: Change EditProjectPage to use NER Buttons

---

src/frontend/src/components/NERButton.tsx
src/frontend/src/pages/ChangeRequestsPage/ChangeRequestsTable.tsx
src/frontend/src/utils/themes.ts

Updated the "new change request" button to match the color of NER red and added hover functionality
Closes #549

#549 Fixed color of change requests button on default and on hover

---

src/frontend/src/pages/TeamsPage/DescriptionPageBlock.tsx
src/frontend/src/pages/WorkPackageDetailPage/StageGateWorkPackageModalContainer/StageGateWorkPackageModal.tsx
src/shared/package.json

FOR #720:
In StageGateWorkPackageModal.tsx, I first imported the new NER success and fail components on lines 23 and 24. Then, I replaced the buttons that were there with the NER buttons on lines 117-122 and gave them the appropriate properties to function.
FOR #403:
In DescriptionPageBlock.tsx I changed line 10 to include "isUnderWordCount, countWords" in the import statement. I am unsure if this fixed the problem as the problem did not go away until the second change but I digress. In package.json, I changed "dist/index.js" to "index.ts" which solved the problem.
This PR is most likely marked under #403 but it also includes #720 I apologize for the confusion next time I will make separate PRs! USE THE LATEST COMMIT AND DISREGARD COMMIT NAMES
Closes #403
Closes #720

#403/#720 Updated stage gate buttons and fixed crashing

---

src/frontend/src/pages/CreateWorkPackagePage/CreateWorkPackageForm.tsx
src/frontend/src/tests/pages/CreateWorkPackagePage/CreateWorkPackageForm.test.tsx

Changed alert() to useToast()
Used the useToast() hook to define toast, and then used toast.error, which does the same thing as alert.
Also, modified it to include the autoHideDuration property.
Lastly, added the jest.mock for the toast in CreateWorkPackageform.test
I cannot login to localhost:3000/login for some reason . It just says Students must use their Husky Google account, but I'm already using it.
Closes #637

#637-Changed Alert to Toast

---

src/frontend/src/app/AppPublic.tsx
src/frontend/src/pages/LoginPage/Login.tsx

Modify redirect to login page to use URL query strings ("query args"). Loading `https://finishlinebyner.com/a/b/c?sleep=false&abc=123` without logging in will redirect to `https://finishlinebyner.com/login?page=a&value1=b&value2=c&sleep=false&abc=123`, which will send back to the original page after logging in.
This replaces the `postLoginRedirect` prop for the `Login` component, which is removed.
Hard-coded to ignore a single `/` at the end of a path, so `https://finishlinebyner.com/a/b/c/?sleep=false&abc=123` will redirect to the same login query strings.
Because we're using `value1`, `value2`, etc... we can't use these query args anywhere else because then login page might get confused with multiple of the same query and send you to the wrong page after logging in. These are pretty …

#223 - Use URL Query Strings for Login Redirect

---

src/frontend/src/pages/ChangeRequestDetailPage/ReviewChangeRequestView.tsx

Make the modals to review CR resize with the width of the page (currently still stops at max 900x700 modal size).
I think this has the good side effect of not having the modal extend beyond the screen size on mobile devices too.
Text box height resizes only in the basic `renderModal()` box, not the more complex `renderProposedSolutionModal()` box. This allows us to view the proposed solution and the additional comments on the same screen.
No tests written :(
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Gu …

#740: Review CR Modal Responsive Layout

---

src/backend/src/controllers/change-requests.controllers.ts
src/backend/src/services/change-request.services.ts

Removed budgetimpact from the Create CR endpoint.
Closes #741

#741: Removed budgetimpact from Create CR endpoint

---

src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/ProjectDetails.tsx

Swapped from using fortawesome icons to Material UI Icons.
Made the necessary import changes.
Added stack tag formatting for alignment.
1) Before
1) After
After Version 2 (Switched slideshow to copresent)
Closes # (issue #278

switched to MUI icons && aligned them

---

src/backend/src/routes/risks.routes.ts
src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/RiskLog.tsx

Removed userId from the payload in the handleCreate function in RiskLog.tsx so that userId is no longer unnecessarily sent to the backend
#747

#747 Removed userID from payload in handleCreate function

---

src/frontend/src/pages/ChangeRequestsPage/ChangeRequestsTable.tsx

Changed it so that the Change Requests table will remember the users setting for number of rows, even if the page is left or browser is closed. The data is stored in localStorage. Still defaults to 50 if there is no data in localStorage.
Tested functionality manually
Closes #652

#652 Frontend - Make Row Count Persistent on CR Table

---

src/backend/src/controllers/projects.controllers.ts
src/backend/src/routes/projects.routes.ts
src/backend/src/services/projects.services.ts
src/frontend/src/pages/ProjectDetailPage/ProjectEdit/ProjectEditContainer.tsx

Rename `projectLead` and `projectManager` to `projectLeadId` and `projectManagerId` in the projects controller, route, service, and frontend payload.
(all pass)
Closes #744

#744 Rename to projectLeadId and projectManagerId

---

src/frontend/src/pages/ChangeRequestDetailPage/ProposedSolutionForm.tsx

Added a close button on the close modal.
Closes #751

#751 make close icon

---

src/frontend/src/pages/ChangeRequestDetailPage/ReviewChangeRequestView.tsx

Changed the request view buttons to use NERsuccess/fail buttons
Closes #717

#717 Changed the request view buttons to use NER buttons

---

src/frontend/src/pages/WorkPackageDetailPage/WorkPackageEditContainer/WorkPackageEditContainer.tsx

Changed the buttons of the submit and cancel to NERSuccessButton and NERFailButton. Also put the cancel on the left and the submit on the right.
Closes #714

#714 Updated cancel and submit buttons on the edit work package page

---

src/frontend/src/components/ExternalLink.tsx
src/frontend/src/pages/InfoPage.tsx
src/frontend/src/tests/components/ExternalLink.test.tsx

Made ExternalLink use MUI Icons instead of fontawesome icons. Had to update where this was being used in the info page. Cleaned up the info page file a bit as well.
Closes #814

#814 - removed fontawesome icons from external link

---

src/frontend/src/pages/GanttPage/GanttPackage/components/task-list/TaskListTable.tsx
src/frontend/src/stylesheets/pages/gantt-page.module.css

Prevent Gantt chart from being out of alignment with the corresponding project/work package name labels by forcing the labels to fit on one line, with any extra being cut off with ellipses.
Full name can still be read by hovering over the label text or the corresponding bar in the Gantt.
No Jest tests because I [don't think](https://stackoverflow.com/questions/72491509/react-testing-library-verify-text-truncation) Jest allows you to test whether text has been truncated (you can test if overlay is true, though). Test it manually and expect to see something like the attached screenshot.
- Task with short name displays in full
- Task with long name gets cut off …

#779 - Have Gantt Task Names Cut Off With Ellipses

---

src/frontend/src/pages/CreateWorkPackagePage/CreateWorkPackageFormView.tsx

I changed the buttons on the Create work package page to the NER buttons so that every button is consistent. Had to make changes so that the buttons were on the right side of the page.
Closes #715

#715: Changed Buttons to NER Buttons in CreateWorkPackagePage

---

src/frontend/src/pages/GanttPage/GanttPackage/components/other/Tooltip.tsx

I added the .toFixed(2) method to the progress when it's displayed, so that the progress is always rounded to 2 decimal places.
The localhost version of the page first rounds all progresses to an integer at some point, so in all testing on that version, the percentage always contained .00
I'm not sure if this needs to be addressed in the scope of this ticket.
#776

#776 Made the progress % round to 2 decimal places when displayed

---

src/frontend/src/pages/WorkPackageDetailPage/ActivateWorkPackageModalContainer/ActivateWorkPackageModal.tsx

Changed the Cancel and Submit buttons to use NERFailButton and NERSuccessButton respectively in ActivateWorkPackageModal.
Closes #719

#719: RogerHuang-ActivateWorkPackageModal changed to use NER buttons

---

src/frontend/src/pages/SettingsPage/UserSettings/UserSettings.tsx

The (FontAwesome) pencil icon on the User Settings page was replaced with a MUI pencil (Edit) icon
#848

#848 Removed FontAwesome Icon from UserSettings Page

---

src/frontend/src/pages/WorkPackageDetailPage/WorkPackageViewContainer/WorkPackageViewContainer.tsx

I added MUI icons to the 'Action' menus of the Work Package pages, so that they look like MUI 'icon lists' 
#810

#810 Added MUI icons to action menu in Work Package Page

---

src/frontend/src/pages/GanttPage/GanttPageFilter.tsx

Changes the Gantt dropdown filters to adjust their width based on the contents
Test:
The length of the dropdown is at most 50 characters
The length of the select is as many letters that can fit in it
Closes #817

#817 dynamically change the dropdown width based on the contents

---

src/frontend/src/pages/ChangeRequestDetailPage/ProposedSolutionView.tsx
src/frontend/src/pages/ChangeRequestDetailPage/ProposedSolutionsList.tsx

Change requests that have not been approved appear less opaque as compared to approved requests - similarly to how unselected change requests are translucent in the review selection modal.
Closes #333

#333 - Fade unapproved change requests

---

src/backend/tests/tasks.test.ts

Changed the strict equal to use task transformer instead of a stored variable because on init the dates might be a tiny bit off based off of when they are initialized
Succeeded 20 times in a row
Closes #910  (issue #)

#910 Use task transformer instead of shared version

---

src/backend/tests/risks.test.ts

Added two tests for createRisk:
The endpoint works as intended
The user does not have permissions to create the risk
The tests pass:
When the endpoint correctly,  and all permissions are correct
When the user does not have permissions to create the risk, an appropriate exception is thrown.
- The user creating the risk is an admin and is able to create a risk
- The user creating the risk is a guest and is not allowed to create a risk
Closes #240

#240 test create risk endpoint

---

src/frontend/src/components/WorkPackageStageChip.tsx
src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/WorkPackageSummary.tsx
src/frontend/src/pages/WorkPackageDetailPage/WorkPackageViewContainer/WorkPackageDetails.tsx
src/frontend/src/tests/apis/work-packages.api.test.ts
src/frontend/src/tests/components/ChangesList.test.tsx
src/frontend/src/tests/components/DescriptionList.test.tsx
src/frontend/src/tests/hooks/WorkPackages.hooks.test.tsx
src/frontend/src/tests/pages/ProjectDetailPage/ProjectViewContainer.test.tsx
src/frontend/src/tests/pages/WorkPackageDetailPage/WorkPackagePage.test.tsx
src/frontend/src/tests/pages/WorkPackageDetailPage/WorkPackageViewContainer/DependenciesList.test.tsx
src/frontend/src/tests/pages/WorkPackageDetailPage/WorkPackageViewContainer/WorkPackageDetails.test.tsx
src/frontend/src/tests/pages/WorkPackageDetailPage/WorkPackageViewContainer/WorkPackageViewContainer.test.tsx
src/frontend/src/tests/test-support/test-data/projects.stub.ts
src/frontend/src/tests/test-support/test-data/wbs-numbers.stub.ts
src/frontend/src/tests/test-support/test-data/work-packages.stub.ts
src/frontend/src/utils/themes.ts

Add label (new component) to work package detail page and work package preview for the stage of the work package. See the colors below.
Refactor test data a bit to name the work packages after their stages and refactor WBS numbers.
As you can see in the screenshots, putting two chips side by side doesn't look so good for the work package preview. Maybe we can try to stack them top-down when the screen gets small enough. (Thought that might be tricky because I hard coded the margin-right of the stage chip component...)
Tested in both WP detail page and WP preview (part of the project detail page tests, we can move it to a separate file if you want).
- If no stages then don't show anything
- If it has a stage then display the correct label
- Research
- Design
- Manufacturing
- Integration …

#888 - Work Package Stage Chip on Detail Page

---

src/backend/src/controllers/work-packages.controllers.ts
src/backend/src/prisma/seed-data/work-packages.seed.ts
src/backend/src/routes/work-packages.routes.ts
src/backend/src/services/work-packages.services.ts
src/frontend/src/pages/WorkPackageDetailPage/WorkPackageEditContainer/WorkPackageEditContainer.tsx
src/frontend/src/pages/WorkPackageDetailPage/WorkPackageEditContainer/WorkPackageEditDetails.tsx

Removed Status from form, from payload, and from route, controller, and service.
Closes #882

#882 Editing WP Status should no longer be allowed

---

src/backend/tests/work-packages.test.ts

Write unit tests (see Test Cases), mocking all Prisma calls.
Change `dependencies` to a WbsNumber which is what is actually used as an arg to createWorkPackage.
- the work package dependencies input has its own project as a dependency
- the endpoint completes successfully (calling the prisma create function once)
Closes #266

#266 - Add More Tests for Creating Work Packages

---

src/frontend/src/app/AppPublic.tsx

I removed the const redirectQueryArgs and removed it from the redirect for users that need to login manually, stopping them from being brought to a 404 page.
I don't see another use for redirectQueryArgs, but if there does happen to be another use, deleting it fully could have consequences.
rcontent.com/11459
6410/218940640-4a810957-fe
b7-4697-8087-90c324d43fd1.png">
#831

#831 Removed redirectQueryArgs so user is not brought to undefined page

---

src/frontend/src/pages/ChangeRequestDetailPage/StageGateDetails.tsx
src/frontend/src/tests/pages/ChangeRequestDetailPage/StageGateDetails.test.tsx

Remove the leftover budget part of stage gate details
I made it so that Work Package Done is on one line by removing max width, dont know why we need max width when using a grid?
Closes #842  (issue #)

#842 Remove Leftoer budget from SG Details

---

src/frontend/src/pages/ChangeRequestDetailPage/ReviewChangeRequest.tsx

Replaced all instances of alert() with useToast() in ReviewChangeRequest
Closes #635

#635-Replaced-alert()-with-useToast()-in-ReviewChangeRequest

---

src/backend/src/routes/change-requests.routes.ts
src/frontend/src/pages/ChangeRequestDetailPage/ProposedSolutionForm.tsx
src/frontend/src/pages/CreateChangeRequestPage/CreateChangeRequest.tsx

Fixed the bug that wouldn't allow for negative values in timelineimpact and budgetimpact
- Put a negative TLI and BI
Closes #944

#944: allow neg vals in TLI and Budget

---

src/frontend/src/pages/ChangeRequestDetailPage/ReviewChangeRequestView.tsx

Added CloseIcon button to Review CR Modal UI in the ReviewChangeRequestView.tsx file.
Copied code for CloseIcon button from the DeleteChangeRequestView.tsx file.
- Ran yarn:test frontend + backend
- Manually tested on FinishLine
Not sure if I should add anything to 'const renderModal'?
Closes #738

#738: Added X button to Review CR Modal UI

---

src/frontend/src/pages/CreateProjectPage/CreateProjectFormView.tsx

Changed the save/cancel buttons in the CreateProjectPage component to use the NERSuccessButton/NERFailButton component rather than just the plain MUI button. Cancel on the left and submit on the right. 
- yarn test:frontend
Closes #712

#712: Change CreateProjectPage to use NER Buttons

---

src/frontend/src/hooks/tasks.hooks.ts
src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/ProjectViewContainer.tsx
src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/TaskList.tsx
src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/TaskListNotesModal.tsx
src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/TaskListTabPanel.tsx
src/frontend/src/tests/pages/ProjectDetailPage/TaskList.test.tsx
src/frontend/src/tests/test-support/mock-hooks.ts
src/frontend/src/tests/test-support/test-data/projects.stub.ts
src/frontend/src/tests/test-support/test-data/tasks.stub.ts
src/frontend/src/tests/test-support/test-data/teams.stub.ts
src/frontend/src/tests/test-support/test-data/users.stub.ts

Instead of displaying loading symbol if a project has no team, display helpful text message instead.
New Task button also disabled if no team. Task edit permission is controlled *per task* now.
Refactor task list test data using mock hooks, and change task list props to pass the whole project. Plus some free task test data I didn't get to use.
I chose to display text instead of nothing to make it more user-friendly.
Did not do similar changes for `!auth.user` (will that ever happen?) or `AssigneeEdit` component (does this ever get displayed?)
- New Task Button
- Disabled if no team
- (manual) Assigning a project to a team will instantly refresh component to show table and enable button
- Displaying "no team" message
- Renders if no associated team
- No render if there is a team
Manually …

#956 - Remove Task List Loading Indicator With No Team

---

src/frontend/src/pages/WorkPackageDetailPage/StageGateWorkPackageModalContainer/StageGateWorkPackageModal.tsx
src/frontend/src/pages/WorkPackageDetailPage/StageGateWorkPackageModalContainer/StageGateWorkPackageModalContainer.tsx
src/frontend/src/tests/pages/WorkPackageDetailPage/StageGateWorkPackageModalContainer/StageGateWorkPackageModal.test.tsx

The field asking about leftover budget and all associated code has been removed.
The form will still submit correctly sans budget information.
#841

#841 Removed the 'Leftover Budget' field from the Stage Gate Modal

---

src/frontend/src/pages/ProjectsPage/ProjectsTable.tsx

Wrap the data grid row component with a link, so it gets the default link behavior (can be right clicked and opened in new tab or command clicked)
Tested manually
Closes #997

#997 Wrap project datagrid row with link

---

src/frontend/src/pages/HomePage/UpcomingDeadlines.tsx
src/frontend/src/tests/pages/HomePage/UpcomingDeadlines.test.tsx

Made the whole date range select clickable
Closes #1008  (issue #)

#1008 date range clickable

---

src/frontend/src/layouts/PageBlock.tsx
src/frontend/src/pages/GanttPage/GanttPackage/components/task-list/TaskListTable.tsx
src/frontend/src/stylesheets/pages/gantt-page.module.css

Before, Gantt chart rows would only expand if the arrow was clicked. Now, it will expand if you click anywhere in the Name column. I moved the expansion onClick to be on the Name column rather than just the arrow, and changed the CSS to apply a pointer cursor to the entire column rather than just the title.
Closes #993

#993: Allow Expansion When Clicking On Entire Title of Gantt Row

---

src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/TaskListTabPanel.tsx

Added Pagination to the task list of a project. Pagination options are 5, 10, 15, and 100.
Task list pagination in normal sized window:
Task list pagination in smallest possible window:
Closes #983

#983 Added pagination to TaskLisk

---

src/frontend/src/layouts/Sidebar/NavPageLinks.tsx
src/frontend/src/layouts/Sidebar/Sidebar.tsx
src/frontend/src/tests/test-support/test-data/test-utils.stub.ts
src/frontend/src/utils/types.ts

Replaced all instances of a font awesome icon in NavPageLinks.tsx with a corresponding version of that same icon from the library of MUI icons.
Closes #845

#845 Changed Sidebar Icons from Fontawesome

---

src/backend/src/services/change-requests.services.ts
src/backend/src/services/description-bullets.services.ts
src/backend/src/services/projects.services.ts
src/backend/src/services/risks.services.ts
src/backend/src/services/tasks.services.ts
src/backend/src/services/work-packages.services.ts
src/backend/src/utils/errors.utils.ts
src/backend/tests/change-requests.test.ts
src/backend/tests/risks.test.ts
src/backend/tests/tasks.test.ts
src/backend/tests/work-packages.test.ts

- Created a DeletedException in the errors.utils file 
- Updated all the services files + test files to use this exception when something was deleted
- yarn test:frontend + yarn test:backend passed
- FinishLine works
Closes #962

#962 create deleted exception

---

src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/ProjectViewContainer.tsx

Added Icons to the project page menu action items icon, specifically delete Icon and Group Icon
Closes #1058

#1058 Added Icons to the project page menu action items icon

---

src/frontend/src/app/AppAuthenticated.tsx
src/frontend/src/app/AppContextUser.tsx
src/frontend/src/app/AppPublic.tsx
src/frontend/src/hooks/users.hooks.ts
src/frontend/src/pages/HomePage/Home.tsx
src/frontend/src/tests/app/AppAuthenticated.test.tsx
src/frontend/src/tests/pages/HomePage/Home.test.tsx
src/frontend/src/tests/test-support/mock-hooks.ts
src/frontend/src/tests/test-support/test-data/test-utils.stub.ts

Added a very annoying alert that tells users to set their slack ID which will show up whenever they open homepage.
Also made minor changes to AppPublic.tsx
- Logged in as Damien Wayne(has no slack ID set initially) and checked if there's an alert on the homepage.
- set up Damien Wayne's slack ID locally and went back to the homepage to see if it still gives an alert.
Closes #963

#963 Alert if no Slack id

---

src/frontend/src/pages/CreateWorkPackagePage/CreateWorkPackageFormView.tsx
src/frontend/src/pages/WorkPackageDetailPage/WorkPackageEditContainer/WorkPackageEditContainer.tsx
src/frontend/src/pages/WorkPackageDetailPage/WorkPackageEditContainer/WorkPackageEditDetails.tsx
src/frontend/src/utils/form.ts

In the CreateWorkPackageFormView file, I added the prop 'shouldDisableDate={disableStartDate}' to the <DatePicker> component. The 'disableStartDate' was a function that I created (in the same file) that disables choosing a date from the date picker if a given date was a Monday. I also updated the yup validator 'startDate: yup.date().required("Start Date is required")' by adding '.test("start-date-valid", "start-date-is-not-valid", startDateTester)' to it. In the form file, I made a StartDateTester function that returned false if the given startDate was undefined or if it was a Monday, and true otherwise. 
In the WorkPackageEditDetails file, I did the same as above in terms of adding the prop/creating the function for it. In the WorkPackageEditContainer file, I updated the yup validator as …

#986 enforce monday start date

---

src/frontend/src/pages/SettingsPage/UserSettings/UserSettings.tsx

changed Cancel and Save buttons on  the UserSettings page so that they use NERFaillButton/NERSuccessButton instead of NERButton
Meets all Acceptance Criteria:
- The save/cancel buttons on UserSettingsEdit use NERSuccessButton/NERFailButton and not Button
- The save/cancel buttons on that page looks like the new success/cancel buttons (green and red contained, see the edit members section on a teams specific page to see a good example of how it looks).
- Verify nothing looks weird/ everything works as it did before.
Q - Should I delete the NERButton.tsx file since it's being replaced by NERSuccessButton/NERFailButton?
normal sized window:
smallest possible window:
Closes #685

#685 change user settings edit to use ner buttons

---

src/frontend/src/pages/LoginPage/Login.tsx
src/frontend/src/pages/LoginPage/LoginDev.tsx
src/frontend/src/pages/LoginPage/LoginPage.tsx

Removed `any` from `Login.tsx` `LoginDev.tsx` and `LoginPage.tsx`. I left `any` for `onFailure` because it needs to take in different errors and in the `GoogleLoginProps` interface in `index.d.ts`, `onFailure` takes in any.
Removing `any` from `verifyLogin` required adding a tiny bit of extra code to the function. The only way to replace any was to also include `GoogleResponseOffline` but `getAuthResponse` doesn't take in Offline therefore we needed to confirm that Offline would not be fed to `getAuthResponse`. I worked on this solution with Nezam.
Closes #676

#676 refactoring remove any type from login logindev and loginpage

---

src/frontend/src/pages/ChangeRequestDetailPage/ProposedSolutionView.tsx

The trash icon was changed to another version of the same icon from the library of MUI icons. 
BEFORE:
// no trash icon
AFTER:
// whole image
// smaller image
Closes #849

#849 changed trash icon

---

src/backend/src/services/work-packages.services.ts
src/backend/tests/work-packages.test.ts

enforced monday in backend and adjusted tests
-  added case where WP creation fails if not a monday
i would but the body was so odee
Closes #987

#987 wp creation and editing backend logic enforces monday start

---

src/frontend/src/apis/transformers/change-requests.transformers.ts

Made a new interface to change the any type of the data to MaybeActiveChangeRequest. Had to make this new interface to extend the ChangeRequest interface because sometimes the method gets and ActivationChangeRequest which has additional properties. 
The code was complicated to decipher because the method could not discern between an ActivationChangeRequest or not, so sometimes a non-ActivationChangeRequest would be passed through and the conditional that only accepted ActivationChangeRequests would blow up. 
Please request reviewers and ping on …

709-RemoveAnyTypeFromchange-requeststransforms

---

src/frontend/src/components/ReactHookTextField.tsx

Removed `any` from `ReactHookTextField.tsx`
I kept `any` for the generic types of `Control` and `Omit` because those types are basically rulesets that take in many different types to determine how the react text fields operate.
closes #671

#671 refactoring remove any type from reacthooktextfield

---

src/frontend/src/pages/ProjectDetailPage/ProjectEdit/ProjectEditContainer.tsx
src/frontend/src/pages/ProjectDetailPage/ProjectEdit/ProjectEditDetails.tsx

Do not merge yet!! 
Removed `any` types from the `ProjectEditDetails.tsx` file with no problems.
Removed `any` type from `ProjectEditContainer.tsx` however ran into a singular problem ( see todo )
Just seeking some guidance. 
If I change type rules to `string[]` I get a whole new set of errors which I am trying to work around if possible.
- [ x] PR is linked to the ticket (fill in the closes line below)
Closes # (issue #677)

#677 remove any type from project edit container project edit details

---

src/frontend/src/components/NERAutocomplete.tsx
src/frontend/src/pages/WorkPackageDetailPage/ActivateWorkPackageModalContainer/ActivateWorkPackageModal.tsx
src/frontend/src/pages/WorkPackageDetailPage/ActivateWorkPackageModalContainer/ActivateWorkPackageModalContainer.tsx
src/frontend/src/tests/pages/WorkPackageDetailPage/ActivateWorkPackageModalContainer/ActivateWorkPackageModal.test.tsx
src/frontend/src/tests/pages/WorkPackageDetailPage/ActivateWorkPackageModalContainer/ActivateWorkPackageModalContainer.test.tsx

Changed the project lead and manager selects to be NERAutocompletes
Closes #1035

#1035 Changed the project lead and manager selects to be autocomplete

---

src/backend/src/services/work-packages.services.ts
src/backend/tests/work-packages.test.ts
src/frontend/src/hooks/work-packages.hooks.ts
src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/WorkPackageSummary.tsx
src/frontend/src/pages/WorkPackageDetailPage/WorkPackageViewContainer/WorkPackageViewContainer.tsx
src/frontend/src/tests/pages/ProjectDetailPage/ProjectViewContainer.test.tsx
src/frontend/src/tests/pages/WorkPackageDetailPage/WorkPackagePage.test.tsx
src/frontend/src/tests/pages/WorkPackageDetailPage/WorkPackageViewContainer/WorkPackageViewContainer.test.tsx
src/frontend/src/tests/test-support/mock-hooks.ts

The list of dependencies is now made up of links that point to each Project/WP page
A minor change is that the WBS #s are no longer bolded—I didn't include the strong tag because I figured having them be links was a significant visual change that warranted having them look like typical links instead of being bolded. Obviously changing this is very simple if needed.
I did notice that dependencies are also listed on work packet summaries on project details pages. Not sure if we want to add to add links there for a future ticket.
#542

#542 Dependencies are Links on Work Package pages

---

src/backend/src/controllers/reimbursement-requests.controllers.ts
src/backend/src/routes/reimbursement-requests.routes.ts
src/backend/src/services/reimbursement-requests.services.ts
src/backend/src/transformers/vendor.transformer.ts
src/backend/tests/reimbursement-requests.test.ts
src/shared/src/types/reimbursement-requests-types.ts

- Added getAllVendors endpoint in the backend router with functions in reimbursement-requests controller and service
- Added vendor shared type in the backend directory
- Added vendor transformation to make the endpoint return all vendors in shared instead of prisma type
- Added a unit test for getAllVendors endpoint
Need confirmation from others with vendor shared type definition
Our initial data seed for vendor in db was empty. Thus, getAllVendors returns empty array.
Added a vendor data manually in PgAdmin4
Confirmed our getAllVendors returns all added vendor data
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead …

#1143: added getAllVendors endpoint with unit test and vendor transformation

---

src/frontend/src/pages/ProjectDetailPage/ProjectEdit/ProjectEditContainer.tsx
src/frontend/src/pages/ProjectDetailPage/ProjectEdit/ProjectEditDetails.tsx
src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/ProjectDetails.tsx
src/frontend/src/pages/WorkPackageDetailPage/StageGateWorkPackageModalContainer/StageGateWorkPackageModal.tsx

1. Changed front-facing text to say Confluence instead of Slide Deck
We decided to leave this ticket to just be front-end changes due to an eventual rework
Also I did this ticket because I'm bored in OOD rn
Closes #1166

#1166 Change Slide Deck Link to say Confluence Link

---

src/frontend/src/pages/ChangeRequestsPage/ChangeRequestsOverview.tsx

used custom wbs number comparator to check if the cr should be displayed
Closes #1197  (issue #)

#1197 Fix To Review Bug

---

src/backend/src/controllers/reimbursement-requests.controllers.ts
src/backend/src/routes/reimbursement-requests.routes.ts
src/backend/src/services/reimbursement-requests.services.ts
src/backend/tests/reimbursement-requests.test.ts
src/backend/tests/test-data/reimbursement-requests.test-data.ts

Add endpoint `/reimbursement-requests/current-user` to fetch all reimbursement requests whose recipientId matches the current user's.
- Test that the appropriate Prisma function has been called with the desired inputs.
Did not write seed data, instead I manually made the reimbursement requests like so.
Database after inserting new reimbursement:
- TEST CASE 1: Calling endpoint when Authorization = 1 (match found)
- TEST CASE 2: Calling endpoint when Authorization = 2 (match not found)
Please request reviewers and ping on slack only after you've …

#1128 - My Reimbursement Requests Endpoint

---

src/backend/src/controllers/reimbursement-requests.controllers.ts
src/backend/src/routes/reimbursement-requests.routes.ts
src/backend/src/services/reimbursement-requests.services.ts
src/backend/src/utils/errors.utils.ts
src/backend/tests/reimbursement-requests.test.ts
src/backend/tests/test-data/reimbursement-requests.test-data.ts

Endpoint made for deleting reimbursement requests
Sorry this took a while, first backend ticket and had to learn postman lol
- Request cannot be deleted by a user that did not create it
- Request cannot be deleted if it has been already
- Request cannot be deleted if an invalid id is given
- Success
Closes #1139

#1139 Delete Reimbursement Request Endpoint

---

.github/workflows/stale-issues.yml

Add workflow that marks stale issues, using [@actions/github-script](https://github.com/actions/github-script).
This workflow suffers from the **same major flaws** as a [solution](https://github.com/jonathan-chen10/react-stale-workflow-test/blob/main/proposed-workflows/update-state/stale-action.yml) using [@actions/stale](https://github.com/actions/stale) does: it depends on the issue's `updated_at` time, which changes with unimportant things like adding labels and moving milestones, yet doesn't update with important things like linking a commit or a PR. Feel free to look around the [Github issues object](https://api.github.com/repos/Northeastern-Electric-Racing/FinishLine/issues/481) to see if there are any better data to use.
This workflow does *not* automatically remove stale label on …

#481 - Add Stale Issue Workflow

---

src/backend/src/controllers/teams.controllers.ts
src/backend/src/routes/teams.routes.ts
src/backend/src/services/teams.services.ts
src/backend/tests/teams.test.ts

- Added set team head endpoint in the teams.routes.ts
- Added set team head controller in the teams.controllers.ts
- Added set team head service function in the teams.services.ts 
- Added unit test for set team head endpoint in teams.test.ts
- **Case A**
- Check the endpoint throws error when given new head's userId is not found
- **Case B**
- Check the endpoint successfully updates the given team's leader to a given user
**A team before the head update:**
**A team after the head update (new Head with userId: 9):**
**Retrieve the updated team after the update**
**A test that checks if the new head is already a leader of another team:
Note that Thomas with userId, 1 is already a leader of a certain team.**
**Rejects setting Thomas as a new leader to a certain team**
It can be helpful to …

#1176: Added Set Team Head Endpoint with the unit test

---

src/frontend/package.json
src/frontend/src/utils/types.ts
yarn.lock

Removed FontAwesome Icons as a dependency in the frontend
Closes #1242  (issue #)

#1242 - remove fontawesome icons as a depedency

---

src/frontend/src/components/CheckList.tsx
src/frontend/src/components/NERFormModal.tsx
src/frontend/src/components/NERModal.tsx
src/frontend/src/pages/ChangeRequestDetailPage/DeleteChangeRequestView.tsx
src/frontend/src/pages/WorkPackageDetailPage/StageGateWorkPackageModalContainer/StageGateWorkPackageModal.tsx

I'm trying to make a component for an NERModal, so we can use it for all these finance modals. Lmk if you think the NERFormModal is overkill, I made it cause a lot of our modals that have forms have that bit of code that's the same every time.
I only migrated 3 of the modals to show how we can use this component. I think migrating the rest of the modals would be good tickets for the fall.
Closes #1258  (issue #)

#1248 - NERFormModal

---

src/backend/src/services/change-requests.services.ts
src/backend/src/utils/change-requests.utils.ts
src/frontend/src/pages/WorkPackageDetailPage/ActivateWorkPackageModalContainer/ActivateWorkPackageModalContainer.tsx

Added a check in the createActivationChangeRequest function in the change requests services file which throws an error if there are any change requests within this change request's work package that have not been reviewed yet. Added the same check in the createStageGateChangeRequest function in the services file.
- Yarn test:backend + frontend all pass
- Yarn start works fine
Closes #1146

#1146 resolve all CRs before making Activation or Stage Gate CR

---

src/backend/src/services/reimbursement-requests.services.ts

Added a one-line check that throws 400 HTTP error if expenseType.allowed is false. 
Closes #1281

 Finance Fixes - Enforce Only Allowed Expense Types for RR edit #1281 

---

src/frontend/src/components/ChangeRequestDropdown.tsx
src/frontend/src/pages/ProjectDetailPage/ProjectEdit/ProjectEditContainer.tsx
src/frontend/src/pages/WorkPackageDetailPage/WorkPackageEditContainer/WorkPackageEditContainer.tsx

Convert change request inputs to dropdowns/autocompletes so users don't have to remember CR IDs and manually type them out
New UI with label:
Closes #1027

#1027 Create change request input component

---

.github/workflows/lint-check.yml
.github/workflows/prettier-check.yml
.github/workflows/run-tests.yml
Dockerfile
package.json
src/backend/package.json
src/frontend/package.json
src/frontend/src/tests/pages/ChangeRequestDetailPage/ReviewChangeRequest.test.tsx
src/shared/package.json
yarn.lock

Migration to Vite done with #619
Other minor errors noticed in research are included in this PR
Closes #625

#625 Migrate to Node 18

---

src/backend/src/services/change-requests.services.ts
src/backend/tests/change-requests.test.ts
src/frontend/src/layouts/Sidebar/Sidebar.tsx

Because changeCreateArgs includes a wbsElement it cannot be used like this. I tried to figure out how to like determine whether or not you would return a wbsElement based on whether or not you supplied one, but the paramterized code seemed more confusing than just doing this. If you want i can show you the paramterized code and that also works, but this also works
Closes #1332  (issue #)

#1332 Fixed Change Bug

---

src/backend/src/controllers/reimbursement-requests.controllers.ts

Ok so, I am stupid, the code I added did in fact make the upload receipt endpoint send an error no matter what on local and prod (LOL, basically true is not in our acceptable list of origins). The good news is, it appears the receipts do actually upload on prod on develop rn it just acts like it errored. I'm truely not sure what caused that error we were getting, but I think this code I added should explicitly prevent it from happening again
error on local an prod:
old error:
Please request reviewers and ping on slack only after you've gone …

fix upload receipt bug

---

src/backend/src/services/work-packages.services.ts
src/frontend/src/hooks/work-packages.hooks.ts
src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/WorkPackageSummary.tsx
src/frontend/src/pages/WorkPackageDetailPage/WorkPackageViewContainer/WorkPackageViewContainer.tsx
src/frontend/src/tests/pages/ProjectDetailPage/ProjectViewContainer.test.tsx
src/frontend/src/tests/pages/WorkPackageDetailPage/WorkPackagePage.test.tsx
src/frontend/src/tests/pages/WorkPackageDetailPage/WorkPackageViewContainer/WorkPackageViewContainer.test.tsx
src/frontend/src/tests/test-support/mock-hooks.ts

This is bc of that weird forever loading bug that got reported today.
Read the ticket, but tl;dr: when blockedBy wasn't an autocomplete you could set a project as a blocker (which causes issues for our getter methods) because we weren't enforcing blockers not being projects even though every time we fetch a blocker we expect it to be a WP only (in the front and backend), so I enforced that. Also we had two hooks being used to get blockedBy WPs and now we should only have one that will hopefully give better error messages
Please request reviewers …

#1412 - Blocked By Bug

---

src/backend/src/services/tasks.services.ts
src/backend/tests/tasks.test.ts
src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/TaskList/TaskListTabPanel.tsx

**Frontend:** Went into `src\frontend\src\pages\ProjectDetailPage\ProjectViewContainer\TaskList\TaskListTabPanel.tsx` and add `auth.user.role == 'HEAD' ||` on line 126. 
**Backend:** Went into `src\backend\src\services\tasks.services.ts` and added "heads," to the AccessDeniedException message "'Only admins, app admins, heads, task creators, project leads, project managers, or project assignees can edit a task'"
**Test:** Went into `src\backend\tests\tasks.test.ts` and changed the test on line 291 so that the test for the backend AccessDeniedException message passes. 
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead …

#1187: Heads can now edit project tasks v3

---

src/frontend/src/components/NERFormModal.tsx
src/frontend/src/pages/AdminToolsPage/FinanceConfig/AccountCodeFormModal.tsx
src/frontend/src/pages/AdminToolsPage/FinanceConfig/AccountCodesTable.tsx
src/frontend/src/pages/AdminToolsPage/FinanceConfig/CreateVendorModal.tsx

Removed "disabled" props for the elements being returned in AccountCodeFormModal.tsx and CreateVendorModal.tsx and removed unnecessary variable (isValid) in both files.
- Error pop ups and "if there's a problem with any for the form fields, the modal doesn't close" seems to be already implemented; once I deleted the disabled props and tried submitting an invalid form, they seemed to work as intended without any further implementation. 
- New Change Request form had it so the error would only pop up on the first field that was invalid (i.e. there is only one error that pops up even if there's multiple sections that aren't filled out) and it is the same case with the Create and Edit Account Code Forms. I left it as is so there's consistency, but if there should be an error under every …

#1287: Vender and Account Code Forms Enabled Submit Buttons

---

src/backend/src/controllers/reimbursement-requests.controllers.ts
src/backend/src/routes/reimbursement-requests.routes.ts
src/backend/src/services/reimbursement-requests.services.ts
src/backend/tests/reimbursement-requests.test.ts
src/frontend/src/apis/finance.api.ts
src/frontend/src/hooks/finance.hooks.ts
src/frontend/src/pages/FinancePage/FinanceComponents/ReportRefundModal.tsx
src/frontend/src/pages/FinancePage/RefundsSection.tsx

Add date received field to report refund form so that it does not have to default to the current date.
Closes #1315

#1315 Add date received field to report refund form

---

src/frontend/src/layouts/Sidebar/Sidebar.tsx
src/frontend/src/stylesheets/layouts/sidebar/sidebar.module.css

I fixed the issue where the version number overlaps the sidebar when the window gets to small. I did this by changing the position of the version number from "absolute" to "relative" in the css file. I then moved it outside of the sidebar box so it stays visible as the window gets smaller. I also added some padding on top of the version number to keep the spacing.
1) Screen is really small vertically
- The side links turn into a scrollbar, so that the version number doesn't overlap the links.
Focusing on the appearance of the navigation bar and version number on the left
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech …

#1314 Version number overlaping sidebar

---

src/frontend/src/pages/FinancePage/ReimbursementRequestForm/ReimbursementFormView.tsx

Wbs dropdown on reimbursement creation and edit page now sorts the elements by number.
Closes #1358

#1358 Reimbursement page now sorts wbs elements by number

---

src/backend/src/services/reimbursement-requests.services.ts

Added a check in  the createReimbursementRequest function in services to throw an http exception if the expenseType assigned to the RR is not allowed
Closes #1280

#1280 Throws Error if expense type assigned to rr is not allowed

---

src/frontend/src/apis/finance.api.ts

removed usage of `any` type in getAllExpenseTypes function
Closes #1481

#1481: removed use of the any type

---

src/frontend/src/components/NERAutocomplete.tsx
src/frontend/src/pages/FinancePage/ReimbursementRequestForm/ReimbursementFormView.tsx

the create/edit reimbursement request form is now an autocomplete select
The create and edit forms functionality should be unaffected
NERAutocomplete now looks like NativeSelect
- Case A
- Edge case
- ...
Closes #1289

#1289 change expense type to autocomplete

---

src/frontend/src/pages/SettingsPage/Settings.tsx

On the user settings page, if the user is part of a Team or Teams, then it is displayed as "Teams: " and a list separated by commas, and if they are part are no team, "Teams: None" is displayed.
Closes #1513

#1513: added team description to user settings

---

src/frontend/src/pages/ProjectsPage/ProjectsTable.tsx

Added onFilterModelChange listener for DataGrid that stores the changed fields as a JSON string in local storage. Added filter for the initialState of DataGrid that grabs the saved fields from local storage (after parsing JSON string back into an object) and defaults to a set of default values if filter does not exist in local storage.
- Tested reloading page
- Tested going to another page on the site and going back
- Tested closing and opening in a new tab …

#1167 persistent filters for projects table

---

src/frontend/src/pages/ChangeRequestsPage/ChangeRequestsTable.tsx

Added onFilterModelChange listener for DataGrid that stores the changed fields as a JSON string in local storage. Added filter for the initialState of DataGrid that grabs the saved fields from local storage (after parsing JSON string back into an object) and defaults to a set of default values if filter does not exist in local storage.
Basically the same code as I did for #1167 but a different variable name for the filter being saved in local storage and a different default filter value.
- Tested reloading page
- Tested going to another page on the site and going back
- Tested closing and opening in a new tab
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributo …

#1168: Added persistent filters for CR table

---

src/backend/src/services/work-packages.services.ts
src/backend/src/utils/changes.utils.ts

I edited the createChange function in the changes.utils.ts file, such that when the old value is null, it will not add a null stage when the new value is null. The stage change in workpackage-services file was also changed so that a null new stage will not return 'None'.
When a workpackage is edited and the stage is not changed, it does not alert any changes to the stage.
Closes #954

#954: fixed bug with stage when editing workpackage

---

src/frontend/src/pages/FinancePage/ReimbursementRequestForm/ReimbursementProductTable.tsx

The dropdown box now automatically clears itself after the user has selected an item.
Closes # (issue #1507 )

#1507 ha nguyen wbs element search

---

src/frontend/src/pages/TeamsPage/TeamMembersPageBlock.tsx

Right aligned the pencil icon by adding `justifyContent={'flex-end'}` to the grid items 
Closes #1597

#1597 right align pencil icon

---

src/backend/src/transformers/change-requests.transformer.ts
src/backend/src/utils/change-requests.utils.ts
src/backend/tests/projects.test.ts
src/backend/tests/work-packages.test.ts
src/frontend/src/components/ChangeRequestDropdown.tsx

In both the back-end and front-end, I changed dateReviewed to dateImplemented by accessing the changeRequest's first change and using its Date.
I wasn't able to test it properly using prisma studio so i wasn't able to make sure the front-end autocomplete works as it should
Closes #1307

#1307 : Changed dateReviewed to dateImplemented

---

src/frontend/src/pages/FinancePage/ReimbursementRequestDetailPage/ReimbursementRequestDetailsView.tsx
src/frontend/src/pages/FinancePage/ReimbursementRequestsSection.tsx

I changed the the titles in the Finance Pages from 'Date Delivered' to 'Date Item Delivered.' 
Closes #1614

#1614-change-datedelivered-to-itemdelivered

---

src/backend/src/controllers/projects.controllers.ts
src/backend/src/routes/projects.routes.ts
src/backend/src/services/projects.services.ts
src/backend/tests/projects.test.ts
src/backend/tests/test-data/projects.test-data.ts

Created create manufacturer endpoint and added backend tests for this endpoint.
- Create manufacturer when User is a guest (should reject)
- Create manufacturer when manufacturer with the given name already exists (should reject)
- Create manufacturer when User is not a guest and the manufacturer's name doesn't already exist (should create manufacturer successfully)
Added tests to the projects backend tests and manually tested with Postman (see below).
createManufacturer works as intended
createManufacturer throws an error if manufacturer name already exists
createManufacturer throws an error if user is a guest
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contribu …

#1521 BOM create manufacturer endpoint

---

src/frontend/src/components/ChangeRequestDropdown.tsx
src/frontend/src/pages/CreditsPage/CreditsPage.tsx
src/frontend/src/pages/ProjectDetailPage/ProjectEdit/ProjectEditContainer.tsx
src/frontend/src/pages/WorkPackageDetailPage/WorkPackageEditContainer/WorkPackageEditContainer.tsx

Added an error message if crID isn't filled out on the work package/ project edit forms.
Closes #1554

#1554 form validation fix for crID for project/wp edit

---

src/backend/src/controllers/work-packages.controllers.ts
src/backend/src/routes/work-packages.routes.ts
src/backend/src/services/work-packages.services.ts
src/frontend/src/pages/WorkPackageDetailPage/WorkPackageEditContainer/WorkPackageEditContainer.tsx

Changed WorkPackageEditContainer.tsx and work-packages.routes.ts to incorporate projectManagerId and projectLeadId instead of projectManager and projectLead
The instructions said to change work-packages.controller.tsx as well but I'm not sure if it should be changed. Please let me know!
- [ x] All commits are tagged with the ticket number
- [ x] All code follows repository-configured prettier …

#745 used projectManagerID and projectLeadId to store numbers

---

.vscode/settings.json
src/backend/src/services/tasks.services.ts
src/backend/tests/tasks.test.ts
src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/TaskList/TaskList.tsx

Work package leads can now create tasks. In the front end, the create task button will now be available to wp leads. In the back end, the createTask permissions were updated to include wp leads.
Although wp leads can now create tasks, they still don't have permission to edit tasks (in both the front and back end). Perhaps this should be changed too.
Closes #1096

#1096 work package leads can create tasks

---

src/backend/src/controllers/reimbursement-requests.controllers.ts
src/backend/src/prisma/migrations/20230629193452_finance/migration.sql
src/backend/src/prisma/migrations/20231109224241_deny_rr/migration.sql
src/backend/src/prisma/schema.prisma
src/backend/src/routes/reimbursement-requests.routes.ts
src/backend/src/services/reimbursement-requests.services.ts
src/backend/tests/reimbursement-requests.test.ts
src/backend/tests/test-data/reimbursement-requests.test-data.ts
src/frontend/src/utils/reimbursement-request.utils.ts
src/shared/src/types/reimbursement-requests-types.ts

Added a denied reimbursement status type and endpoint to allow someone from the finance team to mark a reimbursement request as denied.
Right now you can't deny a RR if its been deleted, denied, or reimbursed, not sure if should also add if approved. 
- Deny Reimbursement Request fails if Submitter not on Finance Team
- Deny Reimbursement Request fails if Finance Team does not exist
- Deny Reimbursement Request fails if the Request does not exist
- Deny Reimbursement Request fails if the Request has been deleted
- Deny Reimbursement Request fails if the request has already been denied
- Deny Reimbursement Request fails if the request has already been reimbursed
- Deny Reimbursement Request success
Please review the …

#1610 Added deny reimbursement request endpoint

---

src/backend/src/routes/work-packages.routes.ts
src/frontend/src/apis/work-packages.api.ts
src/frontend/src/hooks/work-packages.hooks.ts
src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/WorkPackageSummary.tsx
src/frontend/src/pages/WorkPackageDetailPage/WorkPackageViewContainer/WorkPackageViewContainer.tsx
src/frontend/src/tests/pages/ProjectDetailPage/ProjectViewContainer.test.tsx
src/frontend/src/tests/pages/WorkPackageDetailPage/WorkPackagePage.test.tsx
src/frontend/src/tests/pages/WorkPackageDetailPage/WorkPackageViewContainer/WorkPackageViewContainer.test.tsx
src/frontend/src/tests/test-support/mock-hooks.ts
src/frontend/src/utils/urls.ts

Fixing a fuck up I added last release, uses new endpoint in the backend, so the useManyWorkPackages hook is a lot cleaner now. The axios get method doesn't expect a payload, so that's why it's a post request instead of a get request
Closes #1623

#1623 - work package showing wrong blockedBy bug

---

src/frontend/src/components/ChangeRequestDetailCard.tsx
src/frontend/src/pages/ChangeRequestDetailPage/ChangeRequestDetailsView.tsx
src/frontend/src/pages/ChangeRequestDetailPage/OtherChangeRequestsPopupTabs.tsx

Added a new component for the Tabs that will go on the bottom of the Change Request Details page and added the tab for other CRs submitted or reviewed by the submitter of the current CR. The popup will scroll if the size of all the CRs exceed the max width of the container. Added text for when there's no related CRs and the popup has no cards.
- ~~Can't scroll through the popup: The seed data doesn't have enough CRs that would require scrolling for the pop up for this ticket's tab, but I tested the popup with cards for each of the seeded CRs and cards get cut off and you can't scroll through them. I'm stuck on how to implement this.~~
- I had to do some weird border and margin manipulation to make it so that the active tab didn't have a bottom border so that the currently active tab looks …

#1641 other CRs from user popup

---

src/backend/src/controllers/projects.controllers.ts
src/backend/src/routes/projects.routes.ts
src/backend/src/services/projects.services.ts
src/backend/src/utils/errors.utils.ts
src/backend/tests/projects.test.ts
src/backend/tests/test-data/projects.test-data.ts

Endpoint to assign a Material on a project to a different assembly.
- material/assembly id doesnt exist
- insufficient permission
- successful change
Closes #1528

#1528 Create assign material assembly route and controller

---

src/backend/src/services/change-requests.services.ts
src/backend/tests/change-requests.test.ts

Created a new list of the old requested reviewers
Filtered out those of the new reviewers who were apart of the old reviewers
Prereq: Adding a slackbot to the .env file and changing the local finishline slackId to mine
- Case 1:  Tested if I was spam pinged by the Slackbot
- Case 2: Made sure I was spammed by doing the opposite with my filter 
Closes #1593

#1593-Made a check for old reviewers before pinging

---

src/frontend/src/pages/FinancePage/ReimbursementRequestDetailPage/ReimbursementRequestDetailsView.tsx
src/frontend/src/utils/reimbursement-request.utils.ts

Removed the image preview for the receipts (discussed in Slack) and replaced them with the the name that's also a link to the file in Google Drive and a download button. Also made the Receipts header sticky.
- ~~Will change from draft once Brody and Zach approve on Slack.~~ Design approved by Brody and Zach in Slack!
- Had to put a Z index on the Box for the Receipts header as the download buttons would overlap and appear on top of the Box for some reason
Big Screen
Sticky header in action
Small Screen
Please request reviewers and ping on slack …

#1577 receipt display update

---

src/frontend/src/pages/FinancePage/ReimbursementRequestForm/ReimbursementProductTable.tsx

There is now a visual indication when tabbing through delete and add button of the products of the reimbursement request. 
Closes #1659

#1659 visual indication when tabbing through delete and add

---

src/frontend/src/pages/ProjectDetailPage/ProjectForm/ProjectCreateContainer.tsx
src/frontend/src/pages/ProjectDetailPage/ProjectForm/ProjectEditContainer.tsx
src/frontend/src/pages/ProjectDetailPage/ProjectForm/ProjectForm.tsx
src/frontend/src/pages/WorkPackageForm/WorkPackageForm.tsx

Right now on prod, there's an issue where the crID field is not correctly populating on create/edit project and edit wp when you come from a change request page. These changes should address that problem.
Closes #1738  (issue #)

#1738 - CR correctly auto-populates on WP/Project forms now

---

src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/BOM/MaterialForm/EditMaterialModal.tsx
src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/BOMTab.tsx

- Over budget alert only appears when appropriate
- Editing a material no longer multiplies price by 100
It may be best to store material prices in cents, but this would require migration
Closes #1770

#1770 bom bug fixes

---

src/frontend/src/pages/FinancePage/ReimbursementRequestForm/ReimbursementFormView.tsx

I replaced the MUI Select with the NERAutocomplete component.
When I tried to create a reimbursement form, it returned an error "Failed to Upload Receipt(s): No access, refresh token, API key or refresh handler callback is set."
https://github.com/Northeastern-Electric-Racing/FinishLine/assets/90310958/53d5d22a-fadc-434f-a1d6-b8e84f559125
Closes #1574

#1574: autocomplete added (first attempt)

---

src/backend/src/controllers/reimbursement-requests.controllers.ts
src/backend/src/routes/reimbursement-requests.routes.ts
src/backend/src/services/reimbursement-requests.services.ts
src/backend/tests/reimbursement-requests.test.ts

added new endpoint for marking reimbursement requests as reimbursed
- is user part of the finance team
- does finance team exist
- does reimbursement request with `reimbursementRequestId` exist
- is the reimbursement request not deleted
- is reimbursement request not already marked as reimbursed
- is reimbursement request not marked as denied
functionality of adding `REIMBURSED` status
postman req:
before req:
after req:
Closes #1612

#1612 Add reimbursed status endpoint

---

src/frontend/src/pages/SettingsPage/UserSettings/UserSettings.tsx

force page to reload on theme change
- page only reloads if the theme changes, if the theme stays the same or the slack id changes but the theme doesn't change, settings will save without a page reload
N/A - run locally to see test case above
Closes #1825

#1825 Force reload page on theme change

---

src/frontend/src/pages/CreateChangeRequestPage/CreateChangeRequest.tsx

if a change request is submitted but there is no proposed solution, display a form error instead of allowing a submission with an immediate error
works by seeing if `proposedSolutions: ProposedSolution[]` is empty or not. shouldn't have to worry about malformed data entering `proposedSolutions` because of TS type annotation, i.e. if there is something in `proposedSolutions`, it is a valid proposed solution
- errors if there are no proposed solutions and a user attempts to submit the form
Please request reviewers and ping on slack only after …

#1754 Display form error if CR with no proposed solution

---

src/backend/src/controllers/projects.controllers.ts
src/backend/src/routes/projects.routes.ts
src/backend/src/services/projects.services.ts
src/backend/tests/projects.test.ts
src/backend/tests/test-data/projects.test-data.ts

created an endpoint to create new LinkType for admin and head users
- is user a head or admin+
- does a LinkType with the same name already exist
- does endpoint actually create and return a new LinkType
manual postman req
before req
after req
Closes #1542

#1542 Create LinkType endpoint

---

src/frontend/src/utils/bom.utils.ts

Changed how material.quantity and material.unitName were concatenated, adding a space in between when unitName != nothing. 
Closes #1780

#1780: Fixed unit quantity and unit name not having a space

---

src/frontend/src/pages/FinancePage/RefundsSection.tsx

Changed rows to display refunds from newest to oldest (based on date).
Closes #1758

#1758 - Finance Fix - Sort Refunds newest to oldest

---

src/backend/src/controllers/projects.controllers.ts
src/backend/src/routes/projects.routes.ts
src/backend/src/services/projects.services.ts
src/backend/src/utils/errors.utils.ts
src/backend/tests/projects.test.ts
src/backend/tests/test-data/projects.test-data.ts

Added an endpoint(route, controller, service) to change the LinkType at the specified route. Added unit tests for the Service and tested the controller through Manual testing.
- I allow APP_ADMIN to access the endpoint as the role is technically an admin, let me know if I should change that.
- Since the name is a primary key and a foreign key I only change it if no other LinkType has the same name and once the name is changed I change the foreign key in all the Links with this LinkType.
- Edit LinkType fails if the submitter is not an admin or a head
- Throws error if linkType not found
- Throws error if a linktype with the new name already exists
- LinkType edits successfully, changes its foreign key in Link objects as well
Postman testing:
before:
after:
None as far as I checked.
It can …

#1543: added endpoint and tests to edit LinkType

---

src/frontend/src/pages/FinancePage/RefundsSection.tsx

Adjusted the way PercentRefunded is calculated to properly display the percent in the progress bar.
Maybe consider adding a way to edit reported refunds as well as reimbursement requests. I had some issues well testing where if I put the wrong number for a refund, I couldn't correct it.
- Less Than half refunded
- Half refunded
- more than half refunded
- [ x] All commits are tagged with the ticket number
- [ x] No linting errors / newline at end of …

Adjusted PercentRefunded calculation to fix Refund bar

---

src/frontend/src/pages/AdminToolsPage/TeamsTools.tsx

Linked team names to respective pages, so when you click on a team in the list of teams on the admin tools page it takes you to the detail page for that team.
No notes.
- Tested for each of the mock teams.
No to-dos.
Closes #1595

#1595: Linked team names to detail pages in admin tools

---

src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/ProjectViewContainer.tsx

Disabled the Actions button in a project page for guests. 
Closes #1785

#1785: Disabled Project Actions Button for Guests

---

src/frontend/src/pages/TeamsPage/TeamMembersPageBlock.tsx

Adjusted the position of the edit pencil button to always stay on the right side for the members on the teams page
Normal sized window:
Small window:
Closes #1767

1767: Right justify edit button for members edit

---

src/frontend/src/pages/SettingsPage/UserSecureSettings/UserSecureSettings.tsx

Added user type checking to prevent guests from editing their secure settings.
None
Compared an admin, lead, team member and guest to make sure that only guests were unable to edit their settings.
Image of admin logged in to FinishLine
Image of Admin User (guest) logged in to FinishLine
Review and receive feedback
Closes #1792

#1792 - added user type checks to prevent guests from editing secure settings

---

src/frontend/src/components/ChangeRequestDropdown.tsx
src/frontend/src/pages/ProjectDetailPage/ProjectForm/ProjectForm.tsx

change the change request id input which used to be a `Select` to an `NERAutocomplete`
default (no specified search)
with a search
submitting with empty search
Closes #1763

#1763 Make change request ID an autocomplete

---

src/frontend/src/tests/app/AppMain.test.tsx

Replaced the any type in AppMain.test.tsx with React.ReactNode
Closes #1500

#1500: Remove any types from AppMain.test.tsx

---

src/frontend/src/pages/FinancePage/ReimbursementRequestForm/ReimbursementFormView.tsx

Added question icon to the right of "Date of Expense" on the reimbursement request form. Tooltip appears on hover stating 'Reimbursement with Different Purchase Dates Should be on Different Requests'.
Closes #1755

#1755: Added Reimbursement Disclaimer

---

src/backend/src/services/work-packages.services.ts

set all change requests to denied when a workPackage is deleted 
No tests failed on backend so no update, lmk if I should make some.
Closes #1441

#1441 associated CR's not deleted on WP delete

---

src/backend/src/prisma/migrations/20240208041850_deleted_date_deleted_from_manufacturer/migration.sql
src/backend/src/prisma/schema.prisma
src/backend/src/services/projects.services.ts
src/backend/src/transformers/manufacturer.transformer.ts
src/backend/src/transformers/material.transformer.ts
src/backend/tests/projects.test.ts
src/backend/tests/test-data/projects.test-data.ts
src/shared/src/types/bom-types.ts

Made the delete manufacturer a hard delete 
- Made a postman test to check if it hard deleted
- made a test to make sure it throws an exception when a manufacturer is trying to get deleted while it still has materials
- Added seed data in projects.test-data
- created local Finishline data on manufacturer and material and changed the original manufacturer to prismaManufacturer
- Deleted dateDeleted attribute of the manufacturer in the schema and created a migration
- We deleted it because we are hard deleting dataDeleted from the manufacturer so we don't need that variable anymore
- Tested on Postman to see if a manufacturer is hard deleted:
Closes #1989

#1989 hard deleted delete manufacturer endpoint

---

src/frontend/src/pages/FinancePage/ReimbursementRequestsSection.tsx
src/frontend/src/utils/reimbursement-request.utils.ts

- added a new column to the request table labeled "Refund Source" that contains either cash or budget
I couldn't figure out a way to change the reimbursement request to show "BUDGET". I can go back and figure that out, but for now I am assuming that since it is able to display "CASH" it would also be able to display "BUDGET".
- Case A: Refund Source column displays "CASH" in browser window
- Case B: Refund source column displays "CASH" in smaller window …

#2079- added budget/cash refund source column to the request table

---

src/backend/src/services/users.services.ts
src/backend/tests/change-requests.test.ts

Ensures that when updating a user's secure settings, the method checks for the uniqueness of the phone number while excluding the current user from the duplicate check
Closes #2087

#2087 fixed phonenumber error throwing

---

src/frontend/src/pages/AdminToolsPage/BOMConfig/CreateManufacturerFormModal.tsx
src/frontend/src/pages/AdminToolsPage/BOMConfig/CreateMaterialTypeFormModal.tsx

changed 'vendor' to 'manufacturer' in manufacturer modal and changed 'manufacturer' to 'material type' in material type modal"
Closes #1876

#1876: Add Material Type Modal Shouldn't Say 'Manufacturer Name'

---

src/frontend/src/pages/ChangeRequestDetailPage/ReviewChangeRequestView.tsx

Changed the change request timeline warning from appearing when the request is denied by a reviewer.
Closes #1779

#1779 jake hensley change request review timeline warning showing up on deny

---

src/frontend/src/components/Link/LinksEditView.tsx
src/frontend/src/pages/ProjectDetailPage/ProjectForm/LinksEditView.tsx
src/frontend/src/pages/ProjectDetailPage/ProjectForm/ProjectForm.tsx

Replaced all occurrences of type 'any' with the appropriate interface and string.
Closes #1486

#1486 - Remove 'any' type from LinksEditView.tsx

---

src/frontend/src/components/ReimbursementRequestStatusPill.tsx
src/frontend/src/layouts/PageTitle/PageTitle.tsx
src/frontend/src/pages/FinancePage/ReimbursementRequestDetailPage/ReimbursementRequestDetailsView.tsx
src/frontend/src/utils/enum-pipes.ts

Showed chips corresponding to reimbursed status on the request details page.
Created component type, ReimbursementRequestStatusPill similar to ChangeRequestStatusPill.
Edited ReimbursementRequestDetailsView to include chips if a request has a status
Added new enum-pipe ReimbursementRequestTypeTextPipe converting status type to string.
Pending Finance should be a yellow chip
Sabo Submitted should be an orange chip
Advisor_Approved should be a purple chip
Reimbursed should be a green chip
Denied should be a red chip
Default is grey (can't get transparent) only appears on example because has a status with no status type.
- make default color transparent? …

#1872: Added reimbursed status on frontend

---

src/frontend/src/hooks/teams.hooks.ts

Remove the type "any" from the teams.hooks.ts file. The types were either changed to "number[]" or "string."
Closes #1491

remove any from teams.hooks.ts

---

src/backend/src/prisma/migrations/20230629193452_finance/migration.sql
src/backend/src/prisma/migrations/20240129020615_rr_identifier/migration.sql
src/backend/src/prisma/schema.prisma
src/backend/src/prisma/seed.ts
src/backend/src/transformers/reimbursement-requests.transformer.ts
src/backend/tests/test-data/reimbursement-requests.test-data.ts
src/shared/src/types/reimbursement-requests-types.ts

- Added auto-incrementing integer field in RR scheme as an identifier
-  Updated the RR shared type
- Updated all RR getter endpoints to return RR with its identifier field
- Added SQL code in the new migration file so all old RRs get an identifier assigned in the `dateCreated` order
- Confirmed `yarn prisma:reset` works fine
- Case A
- Confirmed all RR getter endpoints return RR with its identifier field
- Case B
- Confirmed RR seed data gets identifier field …

#1661: added auto-incrementing identifier in RR

---

src/frontend/src/pages/FinancePage/ReimbursementRequestForm/ReimbursementRequestForm.tsx

Changed the receiptFiles part of the yup schema to check if in dev or not and to not have it required if in dev.
Added checking for a frontend environment variable to reenable the requirement for receiptFiles.
- Manually tested creating a RR with no receipt upload
- Manually tested editing a RR and deleting all receipts and saving 
- Manually tested added env var (set as "enabled") and creating a RR with no receipt upload
Closes #2081

#2081 Receipt Upload not Required in RR form locally

---

src/frontend/src/pages/HomePage/UpcomingDeadlines.tsx
src/frontend/src/pages/HomePage/WorkPackagesByTimelineStatus.tsx

Deleted 'Grid container' tag in UpcomingDeadlines.tsx file
- The amount of space underneath the scrollbar in Safari is very small, which doesn't look the nicest, but not sure if this is something that needs to be fixed
- Occasionally when you click on 'Ahead' in Safari for 'Work Packages by Timeline Status', the work package card doesn't show up (only a slice of it shows up), but maybe this is just a glitch or something
- When you zoom out a lot in Safari and Chrome, there is a lot of black space underneath the 'Work Packages by Timeline Status' box, which I'm pretty sure already existed before I did this ticket, but doesn't look the nicest either
- For some reason the scrollbar is much larger than it used to be
- I forgot to take screenshots of the smallest possible views in Safari and …

#1312 scrollbar cutting off wp cards homescreen

---

src/frontend/src/pages/AdminToolsPage/AdminToolsBOMConfig.tsx
src/frontend/src/pages/AdminToolsPage/BOMConfig/CreateUnitFormModal.tsx
src/frontend/src/pages/AdminToolsPage/BOMConfig/UnitTable.tsx
src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/BOM/MaterialForm/MaterialForm.tsx
src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/BOM/MaterialForm/MaterialFormView.tsx

Added the ability to create a new unit to the admin tools page under the Build of Materials Config section. Also removed the create unit functionality from the dropdown of the units select on the material form.
Closes #2121

#2121 moving create unit functionality to admin tools

---

src/backend/src/controllers/design-reviews.controllers.ts
src/backend/src/routes/design-reviews.routes.ts
src/backend/src/services/design-reviews.services.ts
src/backend/src/utils/design-reviews.utils.ts
src/backend/tests/design-reviews.test.ts
src/backend/tests/test-data/design-reviews.test-data.ts
src/backend/tests/test-data/users.test-data.ts

created an endpoint that marks the current user as confirmed for a given design review, and sets their schedule setting's availability to the given availability array
- When the user doesn't have schedule settings
- When the array of availabilities has only 1 element
- given user isn't optional nor required
- availabilities arent between 0 and 83 inclusive
- when the design review doesn't exist
- when the design review has been deleted
Closes #2223

#2223: Design Review mark user confirmation endpoint

---

src/frontend/src/pages/AdminToolsPage/AdminToolsFinanceConfig.tsx

Removed the Page Block from the Finance Configurator. Used a Typography component to retain the styling of the title.
Closes #2141

#2141 - Remove page block from Finance Configurator

---

src/frontend/src/pages/AdminToolsPage/AdminToolsAttendeeDesignReviewInfo.tsx
src/frontend/src/pages/AdminToolsPage/AdminToolsBOMConfig.tsx
src/frontend/src/pages/AdminToolsPage/AdminToolsFinanceConfig.tsx
src/frontend/src/pages/AdminToolsPage/AdminToolsProjectsConfig.tsx
src/frontend/src/pages/AdminToolsPage/AdminToolsSlackUpcomingDeadlines.tsx
src/frontend/src/pages/AdminToolsPage/AdminToolsUserManagement.tsx
src/frontend/src/pages/AdminToolsPage/TeamsTools.tsx

Changed headings in Admin Page to NER Red
The headings Role Management, Team Management, Links Config, Bills of Materials Config, Finance Config, Slack Upcoming Deadlines, Design Review Attendee Info  in the Admin Tools page are changed to the NER Red. Hex Color: "#ef4345"
Closes #2243  (issue #)

#2243 changed headings in Admin Page to NER Red

---

src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/BOM/BOMTableWrapper.tsx
src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/BOM/MaterialForm/MaterialForm.tsx
src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/BOM/MaterialForm/MaterialFormView.tsx
src/frontend/src/utils/bom.utils.ts

All instances with the label 'Price' are renamed to 'Price per Unit' in the frontend 
- ran yarn test:frontend
1) normal sized window 
2) smallest window 
Closes #2119

#2119-BOM-price-label-change

---

src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/BOM/MaterialForm/MaterialFormView.tsx

I have added the info icon tool tip to the manufacturer field for the BOM tab

#issue-2003 added info icon to the manufacturer field

---

src/frontend/src/components/ActionsMenu.tsx

If a user is a guest, then the 'Actions' button when viewing a change request is disabled. Follows the method done for other similar buttons.
Full Screen
Smallest Window
Closes #1789

#1789 - Disabled 'Actions' button for guest roles.

---

src/backend/src/services/work-packages.services.ts

Work package corresponding wbs_elements are now set as active when you edit one
- **all current tests are passing lmk if I should postman or something**
Closes #1247

#1247 all work package edits are now marked as active

---

src/frontend/src/pages/CalendarPage/DesignReviewCreateModal.tsx

Reversed the order of the dropdown menu.
Closes #2311

#2311-reversed-workpackage-dropdown

---

src/backend/src/controllers/projects.controllers.ts
src/frontend/src/apis/bom.api.ts
src/frontend/src/hooks/bom.hooks.ts
src/frontend/src/pages/AdminToolsPage/AdminToolsBOMConfig.tsx
src/frontend/src/pages/AdminToolsPage/BOMConfig/UnitTable.tsx
src/frontend/src/utils/urls.ts

Added a column of trash can icons in the unit table in admin tools that allow for deleting a unit. 
- there is an error occurring and I'm not sure where it's coming from
Closes #2084

#2084 delete unit column

---

src/backend/src/controllers/teams.controllers.ts
src/backend/src/prisma-query-args/teams.query-args.ts
src/backend/src/prisma/migrations/20240411015314_added_team_type_to_team/migration.sql
src/backend/src/prisma/schema.prisma
src/backend/src/prisma/seed.ts
src/backend/src/routes/teams.routes.ts
src/backend/src/services/teams.services.ts
src/backend/src/transformers/teams.transformer.ts
src/backend/tests/mocked/teams.test.ts
src/backend/tests/test-data/teams.test-data.ts
src/shared/src/types/team-types.ts

Created a setTeamType endpoint, where the admin can set a team type for each team in its project. 
This adds the teamType to a Team:
The added teamType in prisma studio:
Testing for exceptions:
Wrong teamTypeId
Wrong Team
Wrong user (not admin)
Closes #2326

2326 drc debugs set team teamtype endpoint

---

src/backend/src/prisma/migrations/20240425034912_auto_implementing_crs/migration.sql
src/backend/src/prisma/schema.prisma
src/backend/src/routes/work-packages.routes.ts

Two bugs were happening. When you created or edited a wp and tried to add a blocked by it would error because we make blockedByInfo have the same relation name 'blockedBy' as regular blockedBy, so prisma was getting upset. Also updated the edit work package route so that it actually works

Fix schema relation name, correct edit wp route

---

src/backend/src/controllers/teams.controllers.ts
src/backend/src/routes/teams.routes.ts
src/backend/src/services/teams.services.ts
src/backend/tests/unmocked/team-type.test.ts

Added a getSingleTeamType Endpoint where it retrieves a single teamType from the database.
Exception Handling:
Closes #2247

#2247 Added a Get Single TeamType Endpoint

---

src/frontend/src/components/SearchBar.tsx
src/frontend/src/pages/GanttPage/GanttChart.tsx
src/frontend/src/pages/GanttPage/GanttChartComponents/GanttChartFilters.tsx
src/frontend/src/pages/GanttPage/GanttChartComponents/GanttChartFiltersButton.tsx
src/frontend/src/pages/GanttPage/GanttChartComponents/GanttTaskBar.tsx
src/frontend/src/pages/GanttPage/GanttChartComponents/GanttToolTip.tsx
src/frontend/src/pages/GanttPage/GanttChartPage.tsx
src/frontend/src/pages/GanttPage/GanttChartSection.tsx
src/frontend/src/utils/gantt.utils.ts
src/frontend/src/utils/urls.ts

Individual projects can be expanded and collapsed, and the buttons near the filters expand and collapse all of them. Resetting also collapses all of them 
Closes #2384

#2384 Expanding and Collapsing work on the Gantt Chart page

---

src/frontend/src/pages/CalendarPage/DesignReviewDetailPage/DesignReviewDetailPage.tsx

…passing in params to objects, and fixed the border problem by making the border slightly bigger
implemented requested changes that peyton requested: created a styling object that we pass parameters in to clean up the code. Also, I fixed the border problem by making the border slightly bigger. I had to switch to this new branch because for some reason the git got messed up on my old branch.
Before:
Now:
Closes #2316

#2316: Standardize Date View 

---

src/backend/src/controllers/projects.controllers.ts

Fixed Error when making a new assembly
Closes #2618

#2618-CaioDaSilva-FixAssemblyError

---

.github/workflows/task-deadline-notifications.yml

GitHub actions cron job now runs at 14 UTC (9 EST) instead of 9 UTC
Closes #2641

#2641 Send notifications at 9am EST

---

src/frontend/src/pages/ChangeRequestDetailPage/DiffSection/DiffPanel.tsx

Added indentation for everything but the section labels
Closes #2630

#2630 added distinction between project and work package proposed changes

---

src/frontend/package.json
src/frontend/src/components/NERAutocomplete.tsx
src/frontend/src/pages/GanttPage/GanttChartComponents/GanttTaskBar/GanttTaskBar.tsx
src/frontend/src/pages/GanttPage/GanttChartComponents/GanttTaskBar/GanttTaskBarDisplay.tsx
src/frontend/src/pages/GanttPage/GanttChartComponents/GanttTaskBar/GanttTaskBarEditView.tsx
src/frontend/src/pages/GanttPage/GanttChartComponents/GanttTaskBar/GanttTaskBarView.tsx
src/frontend/src/pages/GanttPage/GanttChartTeamSection.tsx
src/frontend/src/pages/WorkPackageDetailPage/WorkPackagePage.tsx
src/frontend/src/pages/WorkPackageForm/WorkPackageFormDetails.tsx
src/frontend/src/utils/gantt.utils.ts
yarn.lock

Uses react-archer https://github.com/pierpo/react-archer to draw the arrows
Add relations to the blocking gantt task to all of its blocked by
Works with both edit and viewing the gantt tasks

Display Blocked By Changes
